name: Docker Build
description: Build a container image with Docker.

inputs:
  file:
    description: Path to the Dockerfile.
    required: true
  images:
    description: A list of Docker images to use as base name for tags.
    required: true
  push:
    description: Push the resulting image.
    default: 'false'
  build-args:
    description: Optional build arguments to provide.
  token:
    description: The GITHUB_TOKEN to use for pushing to ghcr.io.
    required: true

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.images }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{major}}
          type=sha

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      if: inputs.push == 'true'
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.token }}

    - uses: docker/build-push-action@v5
      with:
        file: ${{ inputs.file }}
        build-args: ${{ inputs.build-args }}
        provenance: true
        sbom: true
        platforms: linux/amd64,linux/arm64
        push: ${{ inputs.push == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
