schema = 3

[mod]
  [mod.'buf.build/gen/go/bufbuild/protodescriptor/protocolbuffers/go']
    version = 'v1.36.12-20250109164928-1da0de137947.1'
    hash = 'sha256-M/mQKTZnUrCvcFT/Saue2DVRm5/8A8fAwiXODi6IDQU='

  [mod.'buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go']
    version = 'v1.36.12-20260709200747-435963d16310.1'
    hash = 'sha256-ZqFd1TpWPNhTxlYwhT3305ow9ZVqvzfGxlV5z6lxQRY='

  [mod.'github.com/BurntSushi/toml']
    version = 'v1.6.0'
    hash = 'sha256-ptdUJvuc21ixeLt+M5way/na3aCnCO4MYHWulWp8NEY='

  [mod.'github.com/agnivade/levenshtein']
    version = 'v1.2.1'
    hash = 'sha256-3XnCzf7tFgEE0MmjxvjfWaw6qK6mKLabFZ3c23JIH9Y='

  [mod.'github.com/bufbuild/protocompile']
    version = 'v0.14.2-0.20260917202354-386f9fcfc7b9'
    hash = 'sha256-qRlR7huYbDpIy95cF4oTkAT6wuqF28d4h1xXO6HrnW4='

  [mod.'github.com/bytedance/gopkg']
    version = 'v0.1.4'
    hash = 'sha256-GpfG8K5YTWAt5MRg7RvpcemU7jfPV0A+mMbxSfA+2ws='

  [mod.'github.com/cloudwego/gopkg']
    version = 'v0.2.0'
    hash = 'sha256-I7M6OAT71QurwW1ZsEKwE7WQoTcwFLzH+heX9pd3qxU='

  [mod.'github.com/cloudwego/thriftgo']
    version = 'v0.4.5'
    hash = 'sha256-8svpWfJNDlBYBPD6TAeuzVnsxdjlCqQJm2ionSXEWRw='

  [mod.'github.com/go-json-experiment/json']
    version = 'v0.0.0-20260623181947-01eb4420fa68'
    hash = 'sha256-seBJtfIsnvK6iJ7+2nuyMensxDCGCo9770hKzsq+fBw='

  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/petermattis/goid']
    version = 'v0.0.0-20260716134002-a9b348f0a2b9'
    hash = 'sha256-TIiIFuxmQKvSYPkbdQP3FaiiuRTbOxujmt2mQNaGMHw='

  [mod.'github.com/rivo/uniseg']
    version = 'v0.4.7'
    hash = 'sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo='

  [mod.'github.com/santhosh-tekuri/jsonschema/v6']
    version = 'v6.0.2'
    hash = 'sha256-rPRYeV00NRyt6rb+gFJRK1K4TlVxy92cocRK/X9Wef4='

  [mod.'github.com/spf13/cobra']
    version = 'v1.10.2'
    hash = 'sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.10'
    hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

  [mod.'github.com/tidwall/btree']
    version = 'v1.8.1'
    hash = 'sha256-QsYonFnbD/zaxUYAJMzDNI3ju0TjcBJrh8/DBhaJfbM='

  [mod.'github.com/vektah/gqlparser/v2']
    version = 'v2.5.60'
    hash = 'sha256-kki+oeLmChfbCy0nwK8PHiQMyUfNRaCvZISbxZMWP0U='

  [mod.'go.lsp.dev/jsonrpc2']
    version = 'v1.0.1'
    hash = 'sha256-Vy+kHaEK44/GTyVS8an2jVwUK0w0Cq8PYepV4XkE97A='

  [mod.'go.lsp.dev/protocol']
    version = 'v1.0.1'
    hash = 'sha256-AWI7Sx4s+775mtV66Sn03WXzVLvboosWRRGtEPDNfgc='

  [mod.'go.lsp.dev/uri']
    version = 'v1.0.1'
    hash = 'sha256-CtRJbhTw/TlvSxoYzmU5zMh5JGpoq1O4GSqX2wzL/IQ='

  [mod.'go.yaml.in/yaml/v3']
    version = 'v3.0.5'
    hash = 'sha256-ygho+GU5kE7vPMx+dZYyNfCaeMjNxj66XmrcVf3afFE='

  [mod.'golang.org/x/exp']
    version = 'v0.0.0-20261005173118-76772065c9b0'
    hash = 'sha256-fUIMzHbfZDKihbK0oUGtBk2xId07eus3Z9k4sFU24h0='

  [mod.'golang.org/x/sync']
    version = 'v0.23.0'
    hash = 'sha256-nF8YZFVC+TitjkderlqgGwJkuMqJCxI+fIElVLjBT2M='

  [mod.'golang.org/x/text']
    version = 'v0.36.0'
    hash = 'sha256-/0t9C6Mc8kYjxweFB0us2lGKo8GovHhBiq5nlMOppC0='

  [mod.'google.golang.org/protobuf']
    version = 'v1.36.12'
    hash = 'sha256-MKd0AdkWEe2A79mGPzOY5I76nMqTsGJKQNPJOKyOwkQ='
