// @generated by protoc-gen-es v2.2.0 with parameter "target=ts,import_extension=none"
// @generated from file unmango/dev/tdl/v1alpha1/conformance.proto (package unmango.dev.tdl.v1alpha1, syntax proto3)
/* eslint-disable */

import type { Message } from '@bufbuild/protobuf';
import type { GenFile, GenMessage, GenService } from '@bufbuild/protobuf/codegenv1';
import { fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv1';

/**
 * Describes the file unmango/dev/tdl/v1alpha1/conformance.proto.
 */
export const file_unmango_dev_tdl_v1alpha1_conformance: GenFile = /*@__PURE__*/
	fileDesc(
		'Cip1bm1hbmdvL2Rldi90ZGwvdjFhbHBoYTEvY29uZm9ybWFuY2UucHJvdG8SGHVubWFuZ28uZGV2LnRkbC52MWFscGhhMSINCgtUZXN0UmVxdWVzdCIOCgxUZXN0UmVzcG9uc2UyawoSQ29uZm9ybWFuY2VTZXJ2aWNlElUKBFRlc3QSJS51bm1hbmdvLmRldi50ZGwudjFhbHBoYTEuVGVzdFJlcXVlc3QaJi51bm1hbmdvLmRldi50ZGwudjFhbHBoYTEuVGVzdFJlc3BvbnNlQv0BChxjb20udW5tYW5nby5kZXYudGRsLnYxYWxwaGExQhBDb25mb3JtYW5jZVByb3RvUAFaSGdpdGh1Yi5jb20vdW5zdG9wcGFibGVtYW5nby90ZGwvcGtnL3VubWFuZ28vZGV2L3RkbC92MWFscGhhMTt0ZGx2MWFscGhhMaICA1VEVKoCGFVubWFuZ28uRGV2LlRkbC5WMWFscGhhMcoCGFVubWFuZ29cRGV2XFRkbFxWMWFscGhhMeICJFVubWFuZ29cRGV2XFRkbFxWMWFscGhhMVxHUEJNZXRhZGF0YeoCG1VubWFuZ286OkRldjo6VGRsOjpWMWFscGhhMWIGcHJvdG8z',
	);

/**
 * @generated from message unmango.dev.tdl.v1alpha1.TestRequest
 */
export type TestRequest = Message<'unmango.dev.tdl.v1alpha1.TestRequest'> & {};

/**
 * Describes the message unmango.dev.tdl.v1alpha1.TestRequest.
 * Use `create(TestRequestSchema)` to create a new message.
 */
export const TestRequestSchema: GenMessage<TestRequest> = /*@__PURE__*/
	messageDesc(file_unmango_dev_tdl_v1alpha1_conformance, 0);

/**
 * @generated from message unmango.dev.tdl.v1alpha1.TestResponse
 */
export type TestResponse = Message<'unmango.dev.tdl.v1alpha1.TestResponse'> & {};

/**
 * Describes the message unmango.dev.tdl.v1alpha1.TestResponse.
 * Use `create(TestResponseSchema)` to create a new message.
 */
export const TestResponseSchema: GenMessage<TestResponse> = /*@__PURE__*/
	messageDesc(file_unmango_dev_tdl_v1alpha1_conformance, 1);

/**
 * @generated from service unmango.dev.tdl.v1alpha1.ConformanceService
 */
export const ConformanceService: GenService<{
	/**
	 * @generated from rpc unmango.dev.tdl.v1alpha1.ConformanceService.Test
	 */
	test: {
		methodKind: 'unary';
		input: typeof TestRequestSchema;
		output: typeof TestResponseSchema;
	};
}> = /*@__PURE__*/
	serviceDesc(file_unmango_dev_tdl_v1alpha1_conformance, 0);
