// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file unmango/dev/tdl/v1alpha1/gen.proto (package unmango.dev.tdl.v1alpha1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GenRequest, GenResponse } from "./gen_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service unmango.dev.tdl.v1alpha1.GenService
 */
export const GenService = {
  typeName: "unmango.dev.tdl.v1alpha1.GenService",
  methods: {
    /**
     * @generated from rpc unmango.dev.tdl.v1alpha1.GenService.Gen
     */
    gen: {
      name: "Gen",
      I: GenRequest,
      O: GenResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

