{
  description = "tdl - Type Description Language";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
    systems.url = "github:nix-systems/triplet";

    flake-parts = {
      url = "github:hercules-ci/flake-parts";
      inputs.nixpkgs-lib.follows = "nixpkgs";
    };

    treefmt-nix = {
      url = "github:numtide/treefmt-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    gomod2nix = {
      url = "github:nix-community/gomod2nix";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.flake-utils.inputs.systems.follows = "systems";
    };
  };

  outputs =
    inputs@{ flake-parts, ... }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      systems = import inputs.systems;
      imports = with inputs; [ treefmt-nix.flakeModule ];

      perSystem =
        { pkgs, system, ... }:
        let
          version = "0.1.3"; # x-release-please-version
          go = pkgs.go_1_27;
        in
        {
          _module.args.pkgs = import inputs.nixpkgs {
            inherit system;
            overlays = with inputs; [ gomod2nix.overlays.default ];
          };

          packages.default = pkgs.callPackage ./nix { inherit version go; };

          devShells.default = pkgs.mkShellNoCC {
            packages = [
              pkgs.direnv
              go
              pkgs.gomod2nix
              pkgs.gopls
              pkgs.golangci-lint
              pkgs.gnumake
              pkgs.nixfmt
              pkgs.buf
              pkgs.markdownlint-cli2
              pkgs.protoc-gen-go
            ];
          };

          treefmt = {
            programs = {
              actionlint.enable = true;
              buf.enable = true;
              gofmt.enable = true;
              jsonfmt.enable = true;
              mdformat = {
                enable = true;
                # Keep 1. 2. 3. rather than rewriting every item to `1.`, and
                # keep the line breaks the author chose: prose here is one
                # sentence per line so diffs stay readable.
                settings.number = true;
                settings.wrap = "keep";
              };
              nixfmt.enable = true;
              taplo.enable = true;
              yamlfmt = {
                enable = true;
                # Blank lines between workflow steps are how a job stays
                # readable; the default drops all of them.
                settings.formatter.retain_line_breaks_single = true;
              };
            };

            # .editorconfig asks for tabs everywhere except yaml and nix, and
            # jsonfmt indents with spaces unless told otherwise.
            settings.formatter.jsonfmt.options = [
              "--indent"
              "\t"
            ];

            settings.global.excludes = [
              # Agent skills are authored prose with their own conventions.
              ".claude/**"
              # Generated: `go test ./internal/sema -update` writes these.
              "*.golden"
              # Generated by release-please, which would fight the formatter
              # over it every release.
              "CHANGELOG.md"
              # Generated: gomod2nix and nix own these.
              "nix/gomod2nix.toml"
              "flake.lock"
              # `tdl fmt` formats these; wiring it in is in docs/backlog.md.
              "*.tdl"
              # mdformat rewrites YAML frontmatter as a thematic break, and
              # the frontmatter is how Copilot decides when to load a skill.
              ".github/skills/**/SKILL.md"
            ];
          };
        };
    };
}
