// Package textmate turns the annotated grammar into a TextMate grammar
// for VS Code.
//
// It is the second emitter beside internal/treesitter, and it reads the
// same file: internal/ebnf reads docs/grammar.ebnf and knows nothing about
// either target. What it writes is a lexical approximation rather than a
// translation, because TextMate is regular expressions over lines and
// cannot express the grammar's structure; docs/design/editors.md says why
// that is the right trade.
//
// The whole input is the lexical layer lex already states for a program:
// the token shapes docs/grammar.ebnf binds by annotation, lex.Keywords,
// lex.Punctuation, and the quoted terminals the grammar spells that the
// lexer scans as identifiers. Nothing here is restated, so a keyword added
// to lex reaches the colors or fails the golden check.
package textmate

import (
	"bytes"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"

	xebnf "golang.org/x/exp/ebnf"

	"github.com/unstoppablemango/tdl/internal/ebnf"
	"github.com/unstoppablemango/tdl/lex"
)

// scopeName is what tree-sitter/tree-sitter.json already declares, so both
// grammars name the language the same thing.
const scopeName = "source.tdl"

// languageName is what the grammar calls itself in an editor's grammar list.
const languageName = "TDL"

// contributors is the header. JSON carries no comments, and this is the key
// VS Code's own grammars use to say the same thing.
var contributors = []string{
	"Code generated by tools/textmate from docs/grammar.ebnf. DO NOT EDIT.",
	"The grammar is derived rather than written: docs/design/editors.md says why,",
	"and docs/grammar.ebnf and lex/table.go are the files to change.",
	"TextMate is regular expressions over lines, so this colors the lexical layer",
	"and nothing needing a parse: a declaration name reads as an identifier.",
}

// constants are the keywords that name a value rather than introduce a
// declaration. The split is a judgment TextMate cannot derive, so it is
// written here and TestEveryKeywordIsColored holds every other keyword to
// the other group.
var constants = map[string]bool{
	"true":  true,
	"false": true,
	"null":  true,
}

// operators are the punctuation that reads as arithmetic or as a relation
// rather than as a delimiter. The split is tree-sitter/queries/highlights.scm's,
// so the two grammars agree on what an operator is.
var operators = map[string]bool{
	"*": true, "/": true, "^": true,
	"=": true, "->": true, "=>": true, "..": true,
}

// tokens is the name each shape is bound to in docs/grammar.ebnf, in the
// order the rules are emitted.
const (
	docComment  = "doc_comment"
	lineComment = "line_comment"
	stringLit   = "string_lit"
	regexLit    = "regex_lit"
	floatLit    = "float_lit"
	intLit      = "int_lit"
)

// A grammar is the tmLanguage file.
type grammar struct {
	Contributors []string `json:"information_for_contributors"`
	Name         string   `json:"name"`
	ScopeName    string   `json:"scopeName"`
	FileTypes    []string `json:"fileTypes"`
	Patterns     []rule   `json:"patterns"`
}

// A rule is one match and the scope it names. Every rule here is a match
// rather than a begin/end pair: no construct in the lexical layer spans
// lines, so none of them needs one.
type rule struct {
	Name     string             `json:"name,omitempty"`
	Match    string             `json:"match"`
	Captures map[string]capture `json:"captures,omitempty"`
}

type capture struct {
	Name string `json:"name"`
}

// Emit writes the tmLanguage for a grammar internal/ebnf has already read
// and found clean.
func Emit(file *ebnf.File) ([]byte, error) {
	patterns, err := rules(file)
	if err != nil {
		return nil, err
	}

	out := grammar{
		Contributors: contributors,
		Name:         languageName,
		ScopeName:    scopeName,
		FileTypes:    []string{"tdl"},
		Patterns:     patterns,
	}

	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	// Tabs, because .editorconfig asks for them everywhere but yaml and nix.
	enc.SetIndent("", "\t")
	// The patterns are regular expressions full of `<`, `>`, and `&`, and
	// escaping those as < would make the file unreadable.
	enc.SetEscapeHTML(false)
	if err := enc.Encode(out); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// rules is the whole grammar, in the order TextMate reads them.
//
// Order settles a tie rather than a race: TextMate takes the rule matching
// earliest in the line and the first of those listed here. Only two pairs
// tie, and both are a prefix of the other: `///` before `//`, and a float
// before the integer that starts it.
func rules(file *ebnf.File) ([]rule, error) {
	shapes := map[string]string{}
	for _, name := range []string{docComment, lineComment, stringLit, regexLit, floatLit, intLit} {
		pattern, err := token(file, name)
		if err != nil {
			return nil, err
		}
		shapes[name] = pattern
	}

	var keywords, values []string
	for _, kw := range lex.Keywords() {
		if constants[kw] {
			values = append(values, kw)
		} else {
			keywords = append(keywords, kw)
		}
	}

	var ops, delims []string
	for _, p := range lex.Punctuation() {
		if operators[p] {
			ops = append(ops, regexp.QuoteMeta(p))
		} else {
			delims = append(delims, regexp.QuoteMeta(p))
		}
	}

	modifiers := contextual(file.Grammar)

	return []rule{{
		Name:  "comment.line.documentation.tdl",
		Match: shapes[docComment],
	}, {
		Name:  "comment.line.double-slash.tdl",
		Match: shapes[lineComment],
	}, {
		Name:  "string.quoted.double.tdl",
		Match: shapes[stringLit],
	}, {
		// A regex and a unit division are both `/`, and no token-local
		// rule separates them; docs/grammar.ebnf says as much where it
		// declares regex_lit external. What separates them here is
		// position: a regex is only ever a ConstraintArg, so it follows
		// `(` or `,`, and a unit expression lives inside `<...>` where
		// neither appears.
		Match: "([(,])\\s*(" + shapes[regexLit] + ")",
		Captures: map[string]capture{
			"1": {Name: "punctuation.separator.tdl"},
			"2": {Name: "string.regexp.tdl"},
		},
	}, {
		Name:  "constant.numeric.tdl",
		Match: word(shapes[floatLit]),
	}, {
		Name:  "constant.numeric.tdl",
		Match: word(shapes[intLit]),
	}, {
		Name:  "constant.language.tdl",
		Match: name(alternation(values)),
	}, {
		Name:  "keyword.control.tdl",
		Match: name(alternation(keywords)),
	}, {
		// Contextual rather than reserved: each is usable as a field name
		// without the `:` test below, and each reads as an annotation on
		// the declaration it precedes.
		Name:  "storage.modifier.tdl",
		Match: name(alternation(modifiers)),
	}, {
		Name:  "keyword.operator.tdl",
		Match: spellings(ops),
	}, {
		Name:  "punctuation.tdl",
		Match: spellings(delims),
	}}, nil
}

// token is the pattern bound to a name, wherever docs/grammar.ebnf binds
// it. A shape the grammar names in a production carries the annotation on
// the production; a comment terminal is named by an extra and bound at
// file level, since the grammar itself never mentions one.
//
// The patterns are lex's, copied rather than translated: TextMate is
// Oniguruma and these six use only what it and Go's regexp spell the same
// way. TestPatternsComeFromLex is what holds the copy to the original.
func token(file *ebnf.File, name string) (string, error) {
	if pattern := file.Annotations.Prods[name].Token; pattern != "" {
		return pattern, nil
	}
	if pattern := file.Annotations.Tokens[name]; pattern != "" {
		return pattern, nil
	}
	return "", fmt.Errorf("%s: no token annotation binds it to a lex pattern", name)
}

// contextual is every quoted terminal the lexer scans as an identifier:
// the modifiers `key`, `owned`, and `deprecated`, which are spellings the
// grammar reserves in a position and lex does not reserve at all.
//
// Read from the grammar rather than listed, so a modifier added there is
// colored without touching this file.
//
// A word, since `_` is identifier-shaped and is the blank import alias in
// ImportDecl: a name the source declines to give rather than a modifier.
func contextual(g xebnf.Grammar) []string {
	ident := regexp.MustCompile("^(?:" + lex.IdentPattern + ")$")
	word := regexp.MustCompile(`[A-Za-z]`)

	seen := map[string]bool{}
	for _, name := range names(g) {
		walk(g[name].Expr, func(x xebnf.Expression) {
			tok, ok := x.(*xebnf.Token)
			if !ok || !ident.MatchString(tok.String) || !word.MatchString(tok.String) {
				return
			}
			if _, reserved := lex.Lookup(tok.String); !reserved {
				seen[tok.String] = true
			}
		})
	}

	out := make([]string, 0, len(seen))
	for text := range seen {
		out = append(out, text)
	}
	sort.Strings(out)
	return out
}

// alternation matches any of a set of words, whole.
func alternation(words []string) string {
	return "\\b(?:" + strings.Join(longestFirst(words), "|") + ")\\b"
}

// spellings matches any of a set of fixed spellings, already escaped.
// Unlike a word, punctuation takes no boundary: `->` is two characters
// neither of which is one.
func spellings(escaped []string) string {
	return "(?:" + strings.Join(longestFirst(escaped), "|") + ")"
}

// name declines to color a word a `:` turns into a field name.
//
// It is the rule docs/spec.md states for the parser: `include Foo` is an
// include and `include: Foo` is a field, and a contextual modifier reads
// the same way. TextMate has no parse to ask, and the lookahead is the
// whole of what it needs.
func name(alternation string) string {
	return alternation + "(?!\\s*:)"
}

// word keeps a numeric literal out of the middle of an identifier, which
// is what `x1` would otherwise be. \b will not do it: the boundary before
// the digit in `x1` is not one.
func word(pattern string) string {
	return "(?<![_A-Za-z0-9])(?:" + pattern + ")(?![_A-Za-z0-9])"
}

// longestFirst orders an alternation so a spelling that starts with
// another is tried first. Oniguruma takes the leftmost alternative that
// matches, so `-` listed before `->` would color the arrow as a minus.
func longestFirst(items []string) []string {
	out := append([]string(nil), items...)
	sort.Slice(out, func(i, j int) bool {
		if len(out[i]) != len(out[j]) {
			return len(out[i]) > len(out[j])
		}
		return out[i] < out[j]
	})
	return out
}

func names(g xebnf.Grammar) []string {
	out := make([]string, 0, len(g))
	for name := range g {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

func walk(x xebnf.Expression, fn func(xebnf.Expression)) {
	if x == nil {
		return
	}
	fn(x)
	switch n := x.(type) {
	case xebnf.Alternative:
		for _, part := range n {
			walk(part, fn)
		}
	case xebnf.Sequence:
		for _, part := range n {
			walk(part, fn)
		}
	case *xebnf.Group:
		walk(n.Body, fn)
	case *xebnf.Option:
		walk(n.Body, fn)
	case *xebnf.Repetition:
		walk(n.Body, fn)
	case *xebnf.Range:
		walk(n.Begin, fn)
		walk(n.End, fn)
	}
}
