// Package textmate turns the annotated grammar into a TextMate grammar
// for VS Code.
//
// TextMate is regular expressions over lines, so the output is a lexical
// approximation of docs/grammar.ebnf (see docs/design/editors.md). Its
// inputs are the token shapes the grammar binds by annotation,
// lex.Keywords, lex.Punctuation, and the quoted terminals lex scans as
// identifiers, so a keyword added to lex reaches the colors.
package textmate

import (
	"bytes"
	"cmp"
	"encoding/json"
	"fmt"
	"maps"
	"regexp"
	"slices"
	"strings"

	xebnf "golang.org/x/exp/ebnf"

	"github.com/unstoppablemango/tdl/internal/ebnf"
	"github.com/unstoppablemango/tdl/lex"
)

// scopeName matches the scope in tree-sitter/tree-sitter.json.
const scopeName = "source.tdl"

const languageName = "TDL"

// contributors is the header, under the key VS Code's grammars use, since
// JSON has no comments.
var contributors = []string{
	"Code generated by tools/textmate from docs/grammar.ebnf. DO NOT EDIT.",
	"The grammar is derived rather than written: docs/design/editors.md says why,",
	"and docs/grammar.ebnf and lex/table.go are the files to change.",
	"TextMate is regular expressions over lines, so this colors the lexical layer",
	"and nothing needing a parse: a declaration name reads as an identifier.",
}

// constants are the keywords that name a value; every other keyword is
// colored as a keyword.
var constants = map[string]bool{
	"true":  true,
	"false": true,
	"null":  true,
}

// operators are the punctuation colored as operators rather than
// delimiters, matching tree-sitter/queries/highlights.scm.
var operators = map[string]bool{
	"*": true, "/": true, "^": true,
	"=": true, "->": true, "=>": true, "..": true,
}

// valueBlock is the declaration whose body holds bare-named values. Named
// rather than derived, since the notation says a production's shape and not
// its meaning.
const valueBlock = "EnumDecl"

// typeValued are the productions that reference a declared type, as
// against `identifier` (a name being declared) and `DottedIdent` (a
// package path). Named for the same reason as valueBlock.
var typeValued = map[string]bool{
	"NamedType": true,
	"ClassRef":  true,
	"TypeRef":   true,
}

// The names docs/grammar.ebnf binds each token shape to.
const (
	identifier  = "identifier"
	docComment  = "doc_comment"
	lineComment = "line_comment"
	stringLit   = "string_lit"
	regexLit    = "regex_lit"
	floatLit    = "float_lit"
	intLit      = "int_lit"
)

// A grammar is the tmLanguage file.
type grammar struct {
	Contributors []string `json:"information_for_contributors"`
	Name         string   `json:"name"`
	ScopeName    string   `json:"scopeName"`
	FileTypes    []string `json:"fileTypes"`
	Patterns     []rule   `json:"patterns"`
}

// A rule is one match and the scope it names, or a region between a begin
// and an end with rules of its own.
type rule struct {
	Name          string             `json:"name,omitempty"`
	Match         string             `json:"match,omitempty"`
	Begin         string             `json:"begin,omitempty"`
	End           string             `json:"end,omitempty"`
	Include       string             `json:"include,omitempty"`
	Captures      map[string]capture `json:"captures,omitempty"`
	BeginCaptures map[string]capture `json:"beginCaptures,omitempty"`
	EndCaptures   map[string]capture `json:"endCaptures,omitempty"`
	Patterns      []rule             `json:"patterns,omitempty"`
}

type capture struct {
	Name string `json:"name,omitempty"`

	// Patterns colors the inside of a capture, such as an enum header's
	// type parameters.
	Patterns []rule `json:"patterns,omitempty"`
}

// self includes the whole grammar inside a region.
var self = rule{Include: "$self"}

// Emit writes the tmLanguage for a grammar internal/ebnf has read clean.
func Emit(file *ebnf.File) ([]byte, error) {
	patterns, err := rules(file)
	if err != nil {
		return nil, err
	}

	out := grammar{
		Contributors: contributors,
		Name:         languageName,
		ScopeName:    scopeName,
		FileTypes:    []string{"tdl"},
		Patterns:     patterns,
	}

	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetIndent("", "\t")
	// Keeps `<`, `>`, and `&` in the regexes readable.
	enc.SetEscapeHTML(false)
	if err := enc.Encode(out); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// rules is the whole grammar. TextMate takes the earliest match in the
// line and, on a tie, the first rule listed, so order matters wherever two
// rules can start at the same character (`///` before `//`, a float before
// an integer).
func rules(file *ebnf.File) ([]rule, error) {
	shapes := map[string]string{}
	for _, name := range []string{identifier, docComment, lineComment, stringLit, regexLit, floatLit, intLit} {
		pattern, err := token(file, name)
		if err != nil {
			return nil, err
		}
		shapes[name] = pattern
	}

	var keywords, values []string
	for _, kw := range lex.Keywords() {
		if constants[kw] {
			values = append(values, kw)
		} else {
			keywords = append(keywords, kw)
		}
	}

	var ops, delims []string
	for _, p := range lex.Punctuation() {
		if operators[p] {
			ops = append(ops, regexp.QuoteMeta(p))
		} else {
			delims = append(delims, regexp.QuoteMeta(p))
		}
	}

	modifiers := contextual(file.Grammar)

	variants, err := variantBlock(file, shapes[identifier], keywords, modifiers)
	if err != nil {
		return nil, err
	}

	return []rule{{
		Name:  "comment.line.documentation.tdl",
		Match: shapes[docComment],
	}, {
		Name:  "comment.line.double-slash.tdl",
		Match: shapes[lineComment],
	}, {
		Name:  "string.quoted.double.tdl",
		Match: shapes[stringLit],
	}, {
		// A regex is only a ConstraintArg, after `(` or `,`, which keeps
		// unit division inside `<...>` from matching.
		Match: "([(,])\\s*(" + shapes[regexLit] + ")",
		Captures: map[string]capture{
			"1": {Name: "punctuation.separator.tdl"},
			"2": {Name: "string.regexp.tdl"},
		},
	}, {
		Name:  "constant.numeric.tdl",
		Match: word(shapes[floatLit]),
	}, {
		Name:  "constant.numeric.tdl",
		Match: word(shapes[intLit]),
	}, variants, {
		// A declared name, after its keyword. Before the keyword rule,
		// which would otherwise win the tie.
		Match: capturing(declares(file.Grammar)) + "\\s+(" + shapes[identifier] + ")",
		Captures: map[string]capture{
			"1": {Name: "keyword.control.tdl"},
			"2": {Name: "entity.name.type.tdl"},
		},
	}, {
		// A referenced type after its keyword: `include Auditable`,
		// `requires Eq`. Before the keyword rule.
		Match: capturing(refers(file.Grammar)) + "\\s+(" + dotted(shapes[identifier]) + ")",
		Captures: map[string]capture{
			"1": {Name: "keyword.control.tdl"},
			"2": {Name: "support.type.tdl"},
		},
	}, {
		// Before the call rule, so `deprecated("gone")` reads as a
		// modifier rather than a directive.
		Name:  "storage.modifier.tdl",
		Match: name(alternation(modifiers)),
	}, {
		// A target entry: a path followed by `{` or `=>`, colored whole
		// as tree-sitter/queries/highlights.scm does.
		Name:  "entity.name.namespace.tdl",
		Match: notKeyword(keywords) + notKeyword(modifiers) + "(?:" + dotted(shapes[identifier]) + ")(?=\\s*(?:=>|\\{))",
	}, {
		// A directive after `=>` with no arguments, which the call rule
		// below misses.
		Match: "(=>)\\s*" + notKeyword(keywords) + "(" + dotted(shapes[identifier]) + ")",
		Captures: map[string]capture{
			"1": {Name: "keyword.operator.tdl"},
			"2": {Name: "entity.name.function.tdl"},
		},
	}, {
		// A constraint or directive call. Before the keyword rule, since a
		// directive name may be a reserved word.
		Name:  "entity.name.function.tdl",
		Match: "(?:" + shapes[identifier] + ")(?=\\s*\\()",
	}, {
		// A type reference after the punctuation opening a type position.
		// Reserved words are excluded so the kinds in `List: type -> type`
		// stay keywords.
		Match: "([:<,\\[])\\s*" + notKeyword(keywords) + "(" + dotted(shapes[identifier]) + ")",
		Captures: map[string]capture{
			"1": {Name: "punctuation.tdl"},
			"2": {Name: "support.type.tdl"},
		},
	}, {
		// A type after `->` or `=`. The keyword guard skips kind atoms;
		// a unit or an enum variant after `=` is colored as a type too.
		Match: "(->|=)\\s*" + notKeyword(keywords) + "(" + dotted(shapes[identifier]) + ")",
		Captures: map[string]capture{
			"1": {Name: "keyword.operator.tdl"},
			"2": {Name: "support.type.tdl"},
		},
	}, {
		// A set or map type, told from a block by canonical form having no
		// space after the brace. A region so its `}` cannot end an
		// enclosing variant.
		Begin: "(\\{)" + notKeyword(keywords) + "(" + dotted(shapes[identifier]) + ")",
		BeginCaptures: map[string]capture{
			"1": {Name: "punctuation.tdl"},
			"2": {Name: "support.type.tdl"},
		},
		End:         "\\}",
		EndCaptures: map[string]capture{"0": {Name: "punctuation.tdl"}},
		Patterns:    []rule{self},
	}, {
		Name:  "constant.language.tdl",
		Match: name(alternation(values)),
	}, {
		Name:  "keyword.control.tdl",
		Match: name(alternation(keywords)),
	}, {
		// A field name: any name followed by `:`.
		Name:  "variable.other.property.tdl",
		Match: "(?:" + shapes[identifier] + ")(?=\\s*:)",
	}, {
		// Every other `{`, as a region so a nested `}` cannot end an
		// enclosing region early.
		Begin:         "\\{",
		BeginCaptures: map[string]capture{"0": {Name: "punctuation.tdl"}},
		End:           "\\}",
		EndCaptures:   map[string]capture{"0": {Name: "punctuation.tdl"}},
		Patterns:      []rule{self},
	}, {
		Name:  "keyword.operator.tdl",
		Match: spellings(ops),
	}, {
		Name:  "punctuation.tdl",
		Match: spellings(delims),
	}}, nil
}

// variantBlock colors an enum body as a region, since a variant has no
// neighboring token to identify it. The keyword is read from valueBlock.
func variantBlock(file *ebnf.File, ident string, keywords, modifiers []string) (rule, error) {
	prod, ok := file.Grammar[valueBlock]
	if !ok {
		return rule{}, fmt.Errorf("%s: no such production, and it is what spells the enum keyword", valueBlock)
	}
	seq, ok := prod.Expr.(xebnf.Sequence)
	if !ok || len(seq) == 0 {
		return rule{}, fmt.Errorf("%s: expected a sequence", valueBlock)
	}
	keyword, ok := seq[0].(*xebnf.Token)
	if !ok {
		return rule{}, fmt.Errorf("%s: expected a keyword first", valueBlock)
	}

	const variant = "variable.other.enummember.tdl"

	return rule{
		// Group 3 is the header between the name and `{`.
		Begin: capturing([]string{keyword.String}) + "\\s+(" + ident + ")([^{]*)\\{",
		BeginCaptures: map[string]capture{
			"1": {Name: "keyword.control.tdl"},
			"2": {Name: "entity.name.type.tdl"},
			"3": {Patterns: []rule{self}},
		},
		End: "\\}",
		Patterns: []rule{
			// A variant with fields, ahead of the target-path rule.
			{
				Begin:         "(" + ident + ")\\s*\\{",
				BeginCaptures: map[string]capture{"1": {Name: variant}},
				End:           "\\}",
				Patterns:      []rule{self},
			},
			self,
			{
				Name:  variant,
				Match: notKeyword(keywords) + notKeyword(modifiers) + "(?:" + ident + ")",
			},
		},
	}, nil
}

// token is the lex pattern docs/grammar.ebnf binds to name, on a
// production or, for comments, at file level. The patterns are used
// verbatim, since they need only syntax Oniguruma and Go's regexp share.
func token(file *ebnf.File, name string) (string, error) {
	if pattern := file.Annotations.Prods[name].Token; pattern != "" {
		return pattern, nil
	}
	if pattern := file.Annotations.Tokens[name]; pattern != "" {
		return pattern, nil
	}
	return "", fmt.Errorf("%s: no token annotation binds it to a lex pattern", name)
}

// declares is every keyword a production spells immediately before the
// identifier it declares: `type Order`, `unit kg`.
func declares(g xebnf.Grammar) []string {
	return keywordsBefore(g, func(next string) bool { return next == identifier })
}

// refers is every keyword a production spells immediately before one of
// typeValued: `include Auditable`, `requires Eq`.
func refers(g xebnf.Grammar) []string {
	return keywordsBefore(g, func(next string) bool { return typeValued[next] })
}

// keywordsBefore is every keyword a production starts with when the
// production after it satisfies next, sorted and deduplicated.
func keywordsBefore(g xebnf.Grammar, next func(name string) bool) []string {
	var out []string
	for _, prodName := range slices.Sorted(maps.Keys(g)) {
		seq, ok := g[prodName].Expr.(xebnf.Sequence)
		if !ok || len(seq) < 2 {
			continue
		}
		keyword, ok := seq[0].(*xebnf.Token)
		if !ok || !lex.IsKeyword(keyword.String) {
			continue
		}
		if named, ok := seq[1].(*xebnf.Name); ok && next(named.String) {
			out = append(out, keyword.String)
		}
	}

	slices.Sort(out)
	return slices.Compact(out)
}

// contextual is every quoted terminal lex scans as an identifier, such as
// `owned` and `deprecated`. The letter check excludes `_`, the blank
// import alias.
func contextual(g xebnf.Grammar) []string {
	ident := regexp.MustCompile("^(?:" + lex.IdentPattern + ")$")
	word := regexp.MustCompile(`[A-Za-z]`)

	seen := map[string]bool{}
	for _, name := range slices.Sorted(maps.Keys(g)) {
		ebnf.Walk(g[name].Expr, func(x xebnf.Expression) {
			tok, ok := x.(*xebnf.Token)
			if !ok || !ident.MatchString(tok.String) || !word.MatchString(tok.String) {
				return
			}
			if _, reserved := lex.Lookup(tok.String); !reserved {
				seen[tok.String] = true
			}
		})
	}

	return slices.Sorted(maps.Keys(seen))
}

// alternation matches any of a set of words, whole.
func alternation(words []string) string {
	return "\\b(?:" + strings.Join(longestFirst(words), "|") + ")\\b"
}

// capturing is alternation as a capture group.
func capturing(words []string) string {
	return "\\b(" + strings.Join(longestFirst(words), "|") + ")\\b"
}

// spellings matches any of a set of escaped punctuation, without word
// boundaries.
func spellings(escaped []string) string {
	return "(?:" + strings.Join(longestFirst(escaped), "|") + ")"
}

// dotted matches a name with an optional package path.
func dotted(ident string) string {
	return "(?:" + ident + ")(?:\\.(?:" + ident + "))*"
}

// notKeyword is a zero-width guard rejecting a reserved word.
func notKeyword(keywords []string) string {
	return "(?!" + alternation(keywords) + ")"
}

// name declines a word followed by `:`, which docs/spec.md makes a field
// name: `include: Foo` is a field.
func name(alternation string) string {
	return alternation + "(?!\\s*:)"
}

// word keeps a numeric literal from matching inside an identifier such as
// `x1`, where \b finds no boundary to stop it.
func word(pattern string) string {
	return "(?<![_A-Za-z0-9])(?:" + pattern + ")(?![_A-Za-z0-9])"
}

// longestFirst sorts longest first, since Oniguruma takes the first
// alternative that matches.
func longestFirst(items []string) []string {
	out := slices.Clone(items)
	slices.SortFunc(out, func(a, b string) int {
		return cmp.Or(cmp.Compare(len(b), len(a)), cmp.Compare(a, b))
	})
	return out
}
