// Code generated by tdl. DO NOT EDIT.

/**
 * One place in a source file.
 */
export interface Point {
  /**
   * The 1-indexed line.
   */
  line: number;
  /**
   * The 1-indexed column.
   */
  column: number;
  /**
   * The 0-indexed offset into the file.
   */
  offset?: number;
}

/**
 * The span of a node in its source file. A generated node has none.
 */
export interface Position {
  /**
   * The place of the first character of the node.
   */
  start: Point;
  /**
   * The place after the last character of the node.
   */
  end: Point;
}

/**
 * Information from the ecosystem. It is empty here, and a plugin
 * extends it.
 */
export interface Data {
}

/**
 * How a table column aligns its cells.
 */
export type AlignType = "left" | "right" | "center";

/**
 * How explicit a reference is.
 */
export type ReferenceType = "shortcut" | "collapsed" | "full";

/**
 * Every mdast node.
 */
export type Nodes = Root | Blockquote | Break | Code | Definition | Delete | Emphasis | FootnoteDefinition | FootnoteReference | Heading | Html | Image | ImageReference | InlineCode | Link | LinkReference | List | ListItem | Paragraph | Strong | Table | TableCell | TableRow | Text | ThematicBreak | Yaml;

/**
 * The whole document.
 */
export interface Root {
  type: "root";
  /**
   * Any content. https://github.com/syntax-tree/mdast#rootcontent
   */
  children: Nodes[];
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * A section quoted from somewhere else.
 */
export interface Blockquote {
  type: "blockquote";
  /**
   * Flow content: block content and definitions.
   */
  children: Nodes[];
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * A line break, as in poems or addresses.
 */
export interface Break {
  type: "break";
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * A block of preformatted text, such as code.
 */
export interface Code {
  type: "code";
  /**
   * The language of the code, from the info string.
   */
  lang?: string | null;
  /**
   * The rest of the info string, after lang.
   */
  meta?: string | null;
  /**
   * The text of the node.
   */
  value: string;
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * A resource, referenced by a linkReference or imageReference.
 */
export interface Definition {
  type: "definition";
  /**
   * The normalized identifier the association matches on.
   */
  identifier: string;
  /**
   * The identifier as written in the source.
   */
  label?: string | null;
  /**
   * A URL to the referenced resource.
   */
  url: string;
  /**
   * Advisory information for the resource, such as a tooltip.
   */
  title?: string | null;
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * Content that is no longer accurate or relevant.
 */
export interface Delete {
  type: "delete";
  /**
   * Phrasing content: text and its markup.
   */
  children: Nodes[];
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * Stress emphasis of its contents.
 */
export interface Emphasis {
  type: "emphasis";
  /**
   * Phrasing content: text and its markup.
   */
  children: Nodes[];
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * Content of a footnote, referenced by a footnoteReference.
 */
export interface FootnoteDefinition {
  type: "footnoteDefinition";
  /**
   * The normalized identifier the association matches on.
   */
  identifier: string;
  /**
   * The identifier as written in the source.
   */
  label?: string | null;
  /**
   * Flow content: block content and definitions.
   */
  children: Nodes[];
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * A marker associated with a footnoteDefinition.
 */
export interface FootnoteReference {
  type: "footnoteReference";
  /**
   * The normalized identifier the association matches on.
   */
  identifier: string;
  /**
   * The identifier as written in the source.
   */
  label?: string | null;
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * The heading of a section.
 */
export interface Heading {
  type: "heading";
  /**
   * The rank of the heading, 1 the highest.
   */
  depth: number;
  /**
   * Phrasing content: text and its markup.
   */
  children: Nodes[];
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * A fragment of raw HTML.
 */
export interface Html {
  type: "html";
  /**
   * The text of the node.
   */
  value: string;
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * An image.
 */
export interface Image {
  type: "image";
  /**
   * A URL to the referenced resource.
   */
  url: string;
  /**
   * Advisory information for the resource, such as a tooltip.
   */
  title?: string | null;
  /**
   * Equivalent content for environments that cannot show the node.
   */
  alt?: string | null;
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * An image through association, or its original source when there is no association.
 */
export interface ImageReference {
  type: "imageReference";
  /**
   * The normalized identifier the association matches on.
   */
  identifier: string;
  /**
   * The identifier as written in the source.
   */
  label?: string | null;
  /**
   * The explicitness of the reference.
   */
  referenceType: ReferenceType;
  /**
   * Equivalent content for environments that cannot show the node.
   */
  alt?: string | null;
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * A fragment of computer code, such as a file name or a command.
 */
export interface InlineCode {
  type: "inlineCode";
  /**
   * The text of the node.
   */
  value: string;
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * A hyperlink.
 */
export interface Link {
  type: "link";
  /**
   * A URL to the referenced resource.
   */
  url: string;
  /**
   * Advisory information for the resource, such as a tooltip.
   */
  title?: string | null;
  /**
   * Phrasing content: text and its markup.
   */
  children: Nodes[];
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * A hyperlink through association, or its original source when there is no association.
 */
export interface LinkReference {
  type: "linkReference";
  /**
   * The normalized identifier the association matches on.
   */
  identifier: string;
  /**
   * The identifier as written in the source.
   */
  label?: string | null;
  /**
   * The explicitness of the reference.
   */
  referenceType: ReferenceType;
  /**
   * Phrasing content: text and its markup.
   */
  children: Nodes[];
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * A list of items.
 */
export interface List {
  type: "list";
  /**
   * Whether the items are in order rather than unordered.
   */
  ordered?: boolean | null;
  /**
   * The number of the first item of an ordered list.
   */
  start?: number | null;
  /**
   * Whether items are separated by blank lines.
   */
  spread?: boolean | null;
  /**
   * List items.
   */
  children: Nodes[];
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * An item in a list.
 */
export interface ListItem {
  type: "listItem";
  /**
   * Whether the item is done, when it is a task; absent otherwise.
   */
  checked?: boolean | null;
  /**
   * Whether items are separated by blank lines.
   */
  spread?: boolean | null;
  /**
   * Flow content: block content and definitions.
   */
  children: Nodes[];
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * A unit of discourse dealing with a particular point or idea.
 */
export interface Paragraph {
  type: "paragraph";
  /**
   * Phrasing content: text and its markup.
   */
  children: Nodes[];
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * Strong importance, seriousness, or urgency for its contents.
 */
export interface Strong {
  type: "strong";
  /**
   * Phrasing content: text and its markup.
   */
  children: Nodes[];
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * Two-dimensional data.
 */
export interface Table {
  type: "table";
  /**
   * How each column aligns; null for a column with no alignment.
   */
  align?: (AlignType | null)[] | null;
  /**
   * Table rows.
   */
  children: Nodes[];
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * A header cell in a table, if its row is the first, or a data cell otherwise.
 */
export interface TableCell {
  type: "tableCell";
  /**
   * Phrasing content: text and its markup.
   */
  children: Nodes[];
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * A row of cells in a table.
 */
export interface TableRow {
  type: "tableRow";
  /**
   * Table cells.
   */
  children: Nodes[];
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * Everything that is just text.
 */
export interface Text {
  type: "text";
  /**
   * The text of the node.
   */
  value: string;
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * A thematic break, such as a scene change in a story.
 */
export interface ThematicBreak {
  type: "thematicBreak";
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}

/**
 * A collection of metadata for the document in YAML.
 */
export interface Yaml {
  type: "yaml";
  /**
   * The text of the node.
   */
  value: string;
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}
