// Package typescript generates TypeScript declarations of JSON wire types
// from a resolved model: interfaces and type aliases, with no runtime code.
// The mapping is in docs/design/schema-backends.md.
package typescript

import (
	"context"
	"fmt"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"github.com/unstoppablemango/tdl/backend/internal/emit"
	"github.com/unstoppablemango/tdl/ir"
	"github.com/unstoppablemango/tdl/plugin"
)

// Name names this backend in a target block and as tdl-gen-typescript.
const Name = "typescript"

// Backend implements [plugin.Backend].
type Backend struct{}

func (Backend) Describe() plugin.Description {
	str := []ir.LiteralKind{ir.LiteralKind_LITERAL_KIND_STRING}
	return plugin.Description{
		Name:    Name,
		Version: "0.1.0",
		// Each request stands alone.
		Reuse: true,
		Directives: []*plugin.DirectiveSpec{
			// The TypeScript name for a type, property, or variant interface.
			{Name: "name", MinArgs: 1, MaxArgs: 1, ArgKinds: str},
			// The property a discriminated union switches on: the default on
			// the target block, an override on an enum.
			{Name: "discriminant", MinArgs: 1, MaxArgs: 1, ArgKinds: str},
			// Writes, as JSDoc @tdl tags, every fact the declarations alone
			// would lose, so import rebuilds the model.
			{Name: "roundtrip"},
		},
		Reverse: true,
	}
}

// scalars maps a TDL primitive to the TypeScript type of its JSON value.
// Every numeric is a number, exact only to 2^53.
var scalars = map[string]string{
	"string":   "string",
	"int":      "number",
	"int32":    "number",
	"int64":    "number",
	"uint32":   "number",
	"uint64":   "number",
	"float32":  "number",
	"float64":  "number",
	"bool":     "boolean",
	"bytes":    "string",
	"decimal":  "string",
	"uuid":     "string",
	"instant":  "string",
	"date":     "string",
	"duration": "string",
}

// reserved is the words TypeScript refuses as a type name, `await`
// included, since an emitted file is a module.
var reserved = map[string]bool{}

func init() {
	for _, w := range strings.Fields(`
		any as await boolean break case catch class const continue debugger default
		delete do else enum export extends false finally for function if
		implements import in instanceof interface let never new null number
		object package private protected public return static string super
		switch symbol this throw true try type typeof undefined unknown var
		void while with yield`) {
		reserved[w] = true
	}
}

var ident = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

type generator struct {
	*emit.Session

	// names maps each declared type name to the declaration declaring it.
	names map[string]string

	// enforced holds each constraint a literal union enforces.
	enforced map[*ir.Constraint]bool

	// lost is whether the declaration being rendered loses a fact, and
	// tags the @tdl tags its JSDoc carries.
	lost bool
	tags []string
}

// Generate returns one .ts file holding the model's declarations.
func (Backend) Generate(_ context.Context, req *plugin.Request) (*plugin.Response, error) {
	g := &generator{
		Session:  emit.NewSession(req, "TypeScript"),
		names:    map[string]string{},
		enforced: map[*ir.Constraint]bool{},
	}

	g.Roundtrip = g.Bare("roundtrip")

	pkg := req.GetModel().GetPackage()
	path := defaultFile + ".ts"
	if pkg != "" {
		path = emit.LastSegment(pkg) + ".ts"
	}
	if back := packageBack(path); back != pkg {
		g.Lose(emit.LossName, nil, "package %s is written %s, which reads back as package %q", pkg, path, back)
	}
	if len(req.GetModel().GetDoc()) > 0 {
		g.Lose(emit.LossDoc, nil, "TypeScript has no place for the package's doc comment")
	}

	own := g.Own()
	texts := map[*ir.Decl]string{}
	skipped := map[*ir.Decl]bool{}
	// Each declaration's warnings are held until the cascade decides
	// whether it is emitted, since a skipped one loses everything at once.
	held := map[*ir.Decl][]*plugin.Diagnostic{}
	for _, d := range own {
		mark := len(g.Diags)
		text, err := g.decl(d)
		if err != nil {
			g.Diags = g.Diags[:mark]
			g.Skip(err)
			skipped[d] = true
			continue
		}
		held[d] = slices.Clone(g.Diags[mark:])
		g.Diags = g.Diags[:mark]
		texts[d] = text
	}
	mark := len(g.Diags)
	g.Cascade(own, skipped)
	if g.Roundtrip {
		// A skipped declaration is carried as TDL, so nothing is lost.
		g.Diags = g.Diags[:mark]
	}
	for _, d := range own {
		if !skipped[d] {
			g.Diags = append(g.Diags, held[d]...)
		}
	}

	var blocks []string
	emitted := map[string]bool{}
	for _, d := range own {
		if text := texts[d]; text != "" && !skipped[d] {
			blocks = append(blocks, text)
			emitted[d.GetMeta().GetName()] = true
		}
	}
	if footer := g.footer(path, emitted); footer != "" {
		blocks = append(blocks, footer)
	}
	if len(blocks) == 0 {
		return g.Response(nil), nil
	}

	var b strings.Builder
	b.WriteString("// Code generated by tdl. DO NOT EDIT.\n")
	for _, block := range blocks {
		b.WriteString("\n")
		b.WriteString(block)
	}
	return g.Response([]*plugin.File{{Path: path, Content: []byte(b.String())}}), nil
}

// decl renders one declaration, or "" for one that declares nothing.
func (g *generator) decl(d *ir.Decl) (string, error) {
	pos := d.GetMeta().GetPosition()
	name := d.GetMeta().GetName()

	switch {
	case d.GetClass() != nil:
		return "", emit.Lost(emit.LossClass, pos, "%s is a class, and classes are not generated yet", name)
	case d.GetUnit() != nil:
		return "", emit.Lost(emit.LossUnit, pos, "%s is a unit, and units are not generated yet", name)
	case d.GetAlias() != nil:
		if len(d.Params()) == 0 {
			g.Lose(emit.LossAlias, pos, "alias %s is expanded where used", name)
			g.typeLosses(d.GetAlias().GetTarget(), nil, modeProperty)
		}
		return "", nil
	case d.GetStructure() == nil && d.GetEnumeration() == nil && d.GetNewtype() == nil:
		// A primitive declares nothing.
		return "", nil
	}
	if len(d.Params()) > 0 {
		return "", emit.Lost(emit.LossGeneric, pos, "%s is parameterized, and generics are not generated yet", name)
	}

	g.lost, g.tags = false, nil
	text, declared, err := g.render(d)
	if err != nil {
		return "", err
	}
	g.losses(d)
	if tags := g.source(d); tags != nil {
		g.tags = tags
		if text, declared, err = g.render(d); err != nil {
			return "", err
		}
		g.tags = nil
	}

	local := map[string]bool{}
	for _, n := range declared {
		if !ident.MatchString(n) || reserved[n] {
			return "", emit.Unsupported(pos, "%s would be named %s in TypeScript, which cannot name a type", name, n)
		}
		if local[n] {
			return "", emit.Unsupported(pos, "%s would declare %s in TypeScript twice", name, n)
		}
		local[n] = true
		if other, ok := g.names[n]; ok {
			return "", emit.Unsupported(pos, "%s would declare %s in TypeScript, and %s already does", name, n, other)
		}
	}
	for _, n := range declared {
		g.names[n] = name
	}
	if !g.Roundtrip {
		g.WarnUnenforced(d, func(c *ir.Constraint) bool { return g.enforced[c] })
	}
	return text, nil
}

// render writes a declaration, returning the type names it declares.
func (g *generator) render(d *ir.Decl) (string, []string, error) {
	var b strings.Builder
	var declared []string
	var err error
	switch e := d.GetEnumeration(); {
	case d.GetNewtype() != nil:
		declared, err = g.newtype(&b, d)
	case d.GetStructure() != nil:
		declared, err = g.iface(&b, g.DeclName(d, emit.Pascal), d.GetMeta(), g.tags, "", "", d.Fields())
	case emit.Fielded(e):
		declared, err = g.union(&b, d)
	default:
		declared = g.literals(&b, d)
	}
	return b.String(), declared, err
}

// losses warns about each fact a declaration loses, and records whether
// it loses any.
func (g *generator) losses(d *ir.Decl) {
	name := d.GetMeta().GetName()
	written := g.DeclName(d, emit.Pascal)
	g.declLosses(d, written)

	fields := d.Fields()
	switch e := d.GetEnumeration(); {
	case d.GetNewtype() != nil:
		if ref, err := g.Resolve(d.GetNewtype().GetBase()); err == nil {
			g.newtypeLosses(d, ref)
		}
	case d.GetStructure() != nil:
		g.includeLosses(name, fields)
		g.fieldsLosses(name, fields)
	case emit.Fielded(e):
		disc := g.Discriminant(d)
		dir, own := g.Find(d.GetDirectives(), "discriminant")
		switch {
		case own && disc == emit.DefaultDiscriminant:
			g.lose(emit.LossName, dir.GetPosition(), "%s's discriminant directive restates the default, and does not read back", name)
		case !own && disc != emit.DefaultDiscriminant:
			g.lose(emit.LossName, d.GetMeta().GetPosition(), "%s's discriminant %s reads back as a directive on the enum", name, disc)
		}
		for _, v := range e.GetVariants() {
			vname := v.GetMeta().GetName()
			member := g.VariantName(v, func(s string) string { return written + emit.Pascal(s) })
			g.renamed(v.GetDirectives(), member != written+emit.Pascal(vname), "%s.%s", name, vname)
			g.docLoss(v.GetMeta())
			g.fieldsLosses(name+"."+vname, v.GetFields())
			fields = append(fields, v.GetFields()...)
		}
	default:
		for _, v := range e.GetVariants() {
			vname, pos := v.GetMeta().GetName(), v.GetMeta().GetPosition()
			if len(v.GetMeta().GetDoc()) > 0 || v.GetMeta().GetDeprecated() != nil {
				g.lose(emit.LossDoc, pos, "%s.%s's doc comment has no place in a union of string literals", name, vname)
			}
			if dir, ok := g.Find(v.GetDirectives(), "name"); ok {
				g.lose(emit.LossName, dir.GetPosition(), "%s.%s is written by its name, and its name directive does not read back", name, vname)
			}
		}
	}

	cs := slices.Clone(d.GetNewtype().GetValueConstraints())
	for _, f := range fields {
		cs = append(cs, f.GetConstraints()...)
	}
	for _, c := range cs {
		if !g.enforced[c] {
			// WarnUnenforced warns about each.
			g.lost = true
		}
	}
}

// fieldsLosses runs [generator.fieldLosses] over each field.
func (g *generator) fieldsLosses(owner string, fields []*ir.Field) {
	for _, f := range fields {
		ref, err := g.Resolve(f.GetType())
		if err != nil {
			continue
		}
		if f.GetIncludedFrom() != nil {
			// The mixin warns about its own fields; the include is lost.
			g.lost = true
			continue
		}
		g.fieldLosses(owner, f, ref)
	}
}

// newtype renders a newtype as an alias for its base, or for the literal
// union its constraints spell. A branded type would make every value parsed
// from JSON need a cast.
func (g *generator) newtype(b *strings.Builder, d *ir.Decl) ([]string, error) {
	ref, err := g.Resolve(d.GetNewtype().GetBase())
	if err != nil {
		return nil, err
	}
	base, err := g.typ(ref)
	if err != nil {
		return nil, err
	}
	if lits := g.narrow(ref, d.GetNewtype().GetValueConstraints(), nil); lits != "" {
		base = lits
	}
	name := g.DeclName(d, emit.Pascal)
	docComment(b, d.GetMeta(), g.tags...)
	fmt.Fprintf(b, "export type %s = %s;\n", name, base)
	return []string{name}, nil
}

// iface renders an entity, a value, or a mixin as an interface. A variant
// passes the discriminant and its value, which come first.
func (g *generator) iface(b *strings.Builder, name string, meta *ir.Meta, tags []string, disc, tag string, fields []*ir.Field) ([]string, error) {
	var body strings.Builder
	seen := map[string]bool{}
	if disc != "" {
		seen[disc] = true
		fmt.Fprintf(&body, "  %s: %s;\n", property(disc), strconv.Quote(tag))
	}

	for _, f := range fields {
		ref, err := g.Resolve(f.GetType())
		if err != nil {
			return nil, err
		}
		prop := g.FieldName(f, asWritten)
		if seen[prop] {
			if prop == disc {
				return nil, emit.Unsupported(f.GetMeta().GetPosition(),
					"%s.%s takes the name of the discriminant, and a discriminant directive can rename it", name, prop)
			}
			return nil, emit.Unsupported(f.GetMeta().GetPosition(), "%s has two properties named %s in TypeScript", name, prop)
		}
		seen[prop] = true

		line, err := g.property(prop, ref, f.GetConstraints())
		if err != nil {
			return nil, err
		}
		emit.DocComment(&body, "  ", f.GetMeta())
		fmt.Fprintf(&body, "  %s\n", line)
	}

	docComment(b, meta, tags...)
	fmt.Fprintf(b, "export interface %s {\n%s}\n", name, body.String())
	return []string{name}, nil
}

// literals renders a fieldless enum as a union of its variant names.
func (g *generator) literals(b *strings.Builder, d *ir.Decl) []string {
	name := g.DeclName(d, emit.Pascal)
	variants := d.GetEnumeration().GetVariants()

	values := make([]string, len(variants))
	for i, v := range variants {
		values[i] = strconv.Quote(v.GetMeta().GetName())
	}
	typ := strings.Join(values, " | ")
	if typ == "" {
		typ = "never"
	}

	docComment(b, d.GetMeta(), g.tags...)
	fmt.Fprintf(b, "export type %s = %s;\n", name, typ)
	return []string{name}
}

// union renders an enum where any variant carries fields: a union of one
// interface per variant, each with the discriminant set to its name.
func (g *generator) union(b *strings.Builder, d *ir.Decl) ([]string, error) {
	name := g.DeclName(d, emit.Pascal)
	disc := g.Discriminant(d)

	declared := []string{name}
	var members []string
	var ifaces strings.Builder
	for _, v := range d.GetEnumeration().GetVariants() {
		member := g.VariantName(v, func(s string) string { return name + emit.Pascal(s) })
		ifaces.WriteString("\n")
		if _, err := g.iface(&ifaces, member, v.GetMeta(), nil, disc, emit.Tag(v), v.GetFields()); err != nil {
			return nil, err
		}
		members = append(members, member)
		declared = append(declared, member)
	}

	docComment(b, d.GetMeta(), g.tags...)
	fmt.Fprintf(b, "export type %s = %s;\n", name, strings.Join(members, " | "))
	b.WriteString(ifaces.String())
	return declared, nil
}

// property renders a property: `?` when the key may be absent, and
// `| null` when the value may be null. A constraint spelling a literal
// union narrows the value.
func (g *generator) property(name string, r *emit.Ref, cs []*ir.Constraint) (string, error) {
	optional, nullable := false, false
	for r.Form == emit.Option || r.Form == emit.Nullable {
		if r.Form == emit.Option {
			optional = true
		} else {
			nullable = true
		}
		r = r.Elem
	}

	typ, err := g.typ(r)
	if err != nil {
		return "", err
	}
	if lits := g.narrow(r, cs, r.Decl.GetNewtype().GetValueConstraints()); lits != "" {
		typ = lits
	}
	if nullable {
		typ += " | null"
	}
	q := ""
	if optional {
		q = "?"
	}
	return fmt.Sprintf("%s%s: %s;", property(name), q, typ), nil
}

// typ is the TypeScript type for a reference. An optional collection
// element may be null, since JSON has no absent element.
func (g *generator) typ(r *emit.Ref) (string, error) {
	switch r.Form {
	case emit.Prim:
		typ, ok := scalars[r.Name]
		if !ok {
			return "", emit.Unsupported(r.Pos, "primitive %s has no TypeScript type", r.Name)
		}
		return typ, nil
	case emit.List, emit.Set:
		elem, err := g.typ(r.Elem)
		if err != nil {
			return "", err
		}
		if strings.Contains(elem, " | ") {
			elem = "(" + elem + ")"
		}
		return elem + "[]", nil
	case emit.Map:
		return g.record(r)
	case emit.Option, emit.Nullable:
		inner, err := g.typ(r.Elem)
		if err != nil {
			return "", err
		}
		if strings.HasSuffix(inner, " | null") {
			return inner, nil
		}
		return inner + " | null", nil
	}
	return g.DeclName(r.Decl, emit.Pascal), nil
}

// record renders a map as a Record keyed by a string, a number, or a
// fieldless enum, whose Record is Partial.
func (g *generator) record(r *emit.Ref) (string, error) {
	kx, err := g.Expand(r.Key)
	if err != nil {
		return "", err
	}
	key, err := g.typ(r.Key)
	if err != nil {
		return "", err
	}
	val, err := g.typ(r.Elem)
	if err != nil {
		return "", err
	}

	switch {
	case kx.Form == emit.Prim && (scalars[kx.Name] == "string" || scalars[kx.Name] == "number"):
		return "Record<" + key + ", " + val + ">", nil
	case kx.Form == emit.Named && kx.Decl.GetEnumeration() != nil && !emit.Fielded(kx.Decl.GetEnumeration()):
		return "Partial<Record<" + key + ", " + val + ">>", nil
	}
	return "", emit.Unsupported(r.Pos, "a TypeScript record key is a string, a number, or a fieldless enum, and this one is %s", key)
}

func asWritten(name string) string { return name }

// property quotes a property name that is not an identifier.
func property(name string) string {
	if ident.MatchString(name) {
		return name
	}
	return strconv.Quote(name)
}
