package typescript_test

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/unstoppablemango/tdl/backend/internal/irtest"
	"github.com/unstoppablemango/tdl/backend/typescript"
	"github.com/unstoppablemango/tdl/ir"
	"github.com/unstoppablemango/tdl/plugin"
)

func generate(t *testing.T, b *irtest.Builder) *plugin.Response {
	t.Helper()
	resp, err := typescript.Backend{}.Generate(context.Background(), &plugin.Request{
		Target: typescript.Name,
		Model:  b.Model,
	})
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	return resp
}

// check returns the response's one file, type checked by tsc when it is on
// PATH.
func check(t *testing.T, resp *plugin.Response) string {
	t.Helper()
	if len(resp.GetFiles()) != 1 {
		t.Fatalf("files = %d, diagnostics = %+v", len(resp.GetFiles()), resp.GetDiagnostics())
	}
	f := resp.GetFiles()[0]
	typecheck(t, f)
	return string(f.GetContent())
}

// typecheck runs `tsc --noEmit --strict` over a file.
//
// TypeScript has no Go implementation, so without tsc these tests check
// declarations by substring alone. The devShell puts it on PATH, and the
// nix check gen-typescript runs it over the smoke fixture whether or not
// anyone ran these tests with it.
func typecheck(t *testing.T, f *plugin.File) {
	t.Helper()
	tsc, err := exec.LookPath("tsc")
	if err != nil {
		return
	}
	path := filepath.Join(t.TempDir(), filepath.Base(f.GetPath()))
	if err := os.WriteFile(path, f.GetContent(), 0o644); err != nil {
		t.Fatal(err)
	}
	if out, err := exec.Command(tsc, "--noEmit", "--strict", path).CombinedOutput(); err != nil {
		t.Errorf("tsc rejects %s: %v\n%s\n%s", f.GetPath(), err, out, f.GetContent())
	}
}

func contains(t *testing.T, src string, wants ...string) {
	t.Helper()
	flat := collapse(src)
	for _, want := range wants {
		if !strings.Contains(flat, collapse(want)) {
			t.Errorf("output missing %q:\n%s", want, src)
		}
	}
}

func absent(t *testing.T, src string, unwanted ...string) {
	t.Helper()
	for _, u := range unwanted {
		if strings.Contains(src, u) {
			t.Errorf("output has %q:\n%s", u, src)
		}
	}
}

func collapse(s string) string { return strings.Join(strings.Fields(s), " ") }

func value(name string, fields ...*ir.Field) *ir.Decl {
	return &ir.Decl{
		Meta: &ir.Meta{Name: name},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{Kind: ir.StructKind_STRUCT_KIND_VALUE, Fields: fields}},
	}
}

func enum(name string, variants ...*ir.Variant) *ir.Decl {
	return &ir.Decl{
		Meta: &ir.Meta{Name: name},
		Node: &ir.Decl_Enumeration{Enumeration: &ir.Enum{Variants: variants}},
	}
}

func variant(name string, fields ...*ir.Field) *ir.Variant {
	return &ir.Variant{Meta: &ir.Meta{Name: name}, Fields: fields}
}

func newtype(name string, base *ir.ID) *ir.Decl {
	return &ir.Decl{Meta: &ir.Meta{Name: name}, Node: &ir.Decl_Newtype{Newtype: &ir.Newtype{Base: base}}}
}

func directive(name, arg string) *ir.Directive {
	return &ir.Directive{Name: name, Target: typescript.Name, Args: []*ir.Literal{irtest.Text(arg)}}
}

func TestDescribe(t *testing.T) {
	d := typescript.Backend{}.Describe()
	if d.Name != "typescript" || !d.Reuse {
		t.Errorf("description = %+v", d)
	}
	declared := map[string]bool{}
	for _, spec := range d.Directives {
		declared[spec.GetName()] = true
	}
	for _, want := range []string{"name", "discriminant"} {
		if !declared[want] {
			t.Errorf("directive %q is acted on but not declared", want)
		}
	}
}

func TestInterfaces(t *testing.T) {
	b := irtest.New("shop.billing")
	b.Own(value("LineItem", irtest.Field("sku", b.Named("string")), irtest.Field("quantity", b.Named("int"))))
	b.Own(value("Order",
		irtest.Field("id", b.Named("uuid")),
		irtest.Field("items", b.Named("List", b.Named("LineItem"))),
		irtest.Field("tags", b.Named("Set", b.Named("string"))),
		irtest.Field("totals", b.Named("Map", b.Named("string"), b.Named("decimal"))),
		irtest.Field("note", b.Named("Option", b.Named("string"))),
		irtest.Field("shipOn", b.Named("Nullable", b.Named("date"))),
		irtest.Field("either", b.Named("Nullable", b.Named("Option", b.Named("string")))),
		irtest.Field("gaps", b.Named("List", b.Named("Option", b.Named("int")))),
		irtest.Field("grid", b.Named("List", b.Named("List", b.Named("int")))),
		irtest.Field("paid", b.Named("bool")),
		irtest.Field("content-type", b.Named("string")),
	))

	resp := generate(t, b)
	if len(resp.GetDiagnostics()) != 0 {
		t.Errorf("diagnostics = %+v", resp.GetDiagnostics())
	}
	src := check(t, resp)
	if path := resp.GetFiles()[0].GetPath(); path != "billing.ts" {
		t.Errorf("path = %q", path)
	}
	contains(t, src,
		"// Code generated by tdl. DO NOT EDIT.",
		"export interface LineItem { sku: string; quantity: number; }",
		"id: string;",
		"items: LineItem[];",
		"tags: string[];",
		"totals: Record<string, string>;",
		"note?: string;",
		"shipOn: string | null;",
		"either?: string | null;",
		"gaps: (number | null)[];",
		"grid: number[][];",
		"paid: boolean;",
		`"content-type": string;`,
	)
}

func TestEnums(t *testing.T) {
	b := irtest.New("shop")
	b.Own(enum("Status", variant("Active"), variant("InProgress")))
	b.Own(enum("Payment", variant("Card", irtest.Field("last4", b.Named("string"))), variant("Cash")))
	b.Own(value("Ticket", irtest.Field("status", b.Named("Status")), irtest.Field("payment", b.Named("Payment"))))

	contains(t, check(t, generate(t, b)),
		`export type Status = "Active" | "InProgress";`,
		"export type Payment = PaymentCard | PaymentCash;",
		`export interface PaymentCard { kind: "Card"; last4: string; }`,
		`export interface PaymentCash { kind: "Cash"; }`,
		"status: Status;",
		"payment: Payment;",
	)
}

// The discriminant is `kind` unless the target block says otherwise, and
// an enum's own directive beats the block's.
func TestDiscriminant(t *testing.T) {
	b := irtest.New("shop")
	b.Own(enum("Payment", variant("Card", irtest.Field("last4", b.Named("string"))), variant("Cash")))
	shape := enum("Shape", variant("Circle", irtest.Field("radius", b.Named("int"))), variant("Point"))
	shape.Directives = []*ir.Directive{directive("discriminant", "$type")}
	b.Own(shape)
	b.Model.Targets = []*ir.TargetBlock{{
		Meta:       &ir.Meta{Name: typescript.Name},
		Directives: []*ir.Directive{directive("discriminant", "type")},
	}}

	contains(t, check(t, generate(t, b)),
		`export interface PaymentCard { type: "Card"; last4: string; }`,
		`export interface ShapeCircle { $type: "Circle"; radius: number; }`,
	)
}

func TestAFieldTakingTheDiscriminantIsSkipped(t *testing.T) {
	b := irtest.New("shop")
	b.Own(enum("Broken", variant("A", irtest.Field("kind", b.Named("string"))), variant("B")))
	b.Own(value("Fine", irtest.Field("a", b.Named("string"))))

	resp := generate(t, b)
	if len(resp.GetDiagnostics()) != 1 {
		t.Errorf("diagnostics = %+v", resp.GetDiagnostics())
	}
	src := check(t, resp)
	absent(t, src, "Broken")
	contains(t, src, "export interface Fine")
}

func TestNewtypes(t *testing.T) {
	b := irtest.New("shop")
	b.Own(newtype("Email", b.Named("string")))
	b.Own(newtype("WorkEmail", b.Named("Email")))
	b.Own(newtype("Skus", b.Named("List", b.Named("WorkEmail"))))
	b.Own(value("Contact", irtest.Field("email", b.Named("WorkEmail")), irtest.Field("all", b.Named("Skus"))))

	contains(t, check(t, generate(t, b)),
		"export type Email = string;",
		"export type WorkEmail = Email;",
		"export type Skus = WorkEmail[];",
		"email: WorkEmail;",
		"all: Skus;",
	)
}

func TestRecordKeys(t *testing.T) {
	b := irtest.New("shop")
	b.Own(enum("Status", variant("Open"), variant("Closed")))
	b.Own(newtype("Sku", b.Named("string")))
	b.Own(value("Counts",
		irtest.Field("byStatus", b.Named("Map", b.Named("Status"), b.Named("int"))),
		irtest.Field("bySku", b.Named("Map", b.Named("Sku"), b.Named("int"))),
		irtest.Field("byNumber", b.Named("Map", b.Named("int"), b.Named("string"))),
	))
	b.Own(value("Broken", irtest.Field("byFlag", b.Named("Map", b.Named("bool"), b.Named("string")))))

	resp := generate(t, b)
	if len(resp.GetDiagnostics()) != 1 {
		t.Errorf("diagnostics = %+v", resp.GetDiagnostics())
	}
	src := check(t, resp)
	contains(t, src,
		"byStatus: Partial<Record<Status, number>>;",
		"bySku: Record<Sku, number>;",
		"byNumber: Record<number, string>;",
	)
	absent(t, src, "Broken")
}

func TestAReservedNameIsSkipped(t *testing.T) {
	b := irtest.New("shop")
	broken := value("Broken", irtest.Field("a", b.Named("string")))
	broken.Directives = []*ir.Directive{directive("name", "interface")}
	b.Own(broken)
	b.Own(value("Fine", irtest.Field("a", b.Named("string"))))

	resp := generate(t, b)
	if len(resp.GetDiagnostics()) != 1 {
		t.Errorf("diagnostics = %+v", resp.GetDiagnostics())
	}
	absent(t, check(t, resp), "interface interface")
}

func TestConstraintsWarn(t *testing.T) {
	b := irtest.New("shop")
	qty := irtest.Field("quantity", b.Named("int"))
	qty.Constraints = []*ir.Constraint{{Name: "min"}}
	b.Own(value("Line", qty))

	resp := generate(t, b)
	if len(resp.GetDiagnostics()) != 1 {
		t.Errorf("diagnostics = %+v", resp.GetDiagnostics())
	}
	contains(t, check(t, resp), "quantity: number;")
}

func TestDocsAndDeprecation(t *testing.T) {
	b := irtest.New("shop")
	old := irtest.Field("fax", b.Named("string"))
	old.Meta.Deprecated = &ir.Deprecation{Reason: "nobody has one"}
	b.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Contact", Doc: []string{"How to reach someone."}, Deprecated: &ir.Deprecation{}},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{Fields: []*ir.Field{old}}},
	})

	contains(t, check(t, generate(t, b)),
		"/** * How to reach someone. * * @deprecated */ export interface Contact {",
		"/** * @deprecated nobody has one */ fax: string;",
	)
}

// Every case in the conformance corpus, and the smoke fixture, generates
// declarations tsc accepts, whatever this backend warned about.
func TestConformance(t *testing.T) {
	corpus := filepath.Join("..", "..", "testdata", "conformance")
	dirs := []string{filepath.Join("..", "..", "testdata", "gen", "smoke")}
	for _, c := range []string{
		"aliases", "collections", "comments", "constraints", "deprecated", "entity",
		"enum_variants", "mixin_include", "newtype", "targets", "targets_variants", "value",
	} {
		dirs = append(dirs, filepath.Join(corpus, c))
	}

	for _, dir := range dirs {
		t.Run(filepath.Base(dir), func(t *testing.T) {
			model := irtest.Conformance(t, dir)
			resp, err := typescript.Backend{}.Generate(context.Background(), &plugin.Request{Target: typescript.Name, Model: model})
			if err != nil {
				t.Fatal(err)
			}
			for _, d := range resp.GetDiagnostics() {
				if d.GetSeverity() == plugin.Severity_SEVERITY_ERROR {
					t.Errorf("error: %s", d.GetMessage())
				}
			}
			if len(resp.GetFiles()) > 0 {
				check(t, resp)
			}
		})
	}
}
