// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file unmango/dev/ux/v1alpha1/ux.proto (package unmango.dev.ux.v1alpha1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GenRequest, GenResponse } from "./ux_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service unmango.dev.ux.v1alpha1.UxService
 */
export const UxService = {
  typeName: "unmango.dev.ux.v1alpha1.UxService",
  methods: {
    /**
     * @generated from rpc unmango.dev.ux.v1alpha1.UxService.Gen
     */
    gen: {
      name: "Gen",
      I: GenRequest,
      O: GenResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

