// Code generated by tdl. DO NOT EDIT.

/**
 * One place in a source file.
 */
export interface Point {
  /**
   * The 1-indexed line.
   */
  line: number;
  /**
   * The 1-indexed column.
   */
  column: number;
  /**
   * The 0-indexed offset into the file.
   */
  offset?: number;
}

/**
 * The span of a node in its source file. A generated node has none.
 */
export interface Position {
  /**
   * The place of the first character of the node.
   */
  start: Point;
  /**
   * The place after the last character of the node.
   */
  end: Point;
}

/**
 * Information from the ecosystem. It is empty here, and a plugin
 * extends it.
 */
export interface Data {
}

/**
 * The fields every node carries besides its `type`.
 */
export interface Node {
  /**
   * Information from the ecosystem.
   */
  data?: Data;
  /**
   * Where the node came from. Absent when it was generated.
   */
  position?: Position;
}
