name: Build proto
description: Builds proto files

inputs:
  path:
    description: The path to the module
    required: true

runs:
  using: composite
  steps:
    - name: Setup buf
      uses: bufbuild/buf-setup-action@v1
      with:
        version: latest
        github_token: ${{ github.token }}

    - name: Lint
      uses: bufbuild/buf-lint-action@v1
      with:
        input: ${{ inputs.path }}

    - name: Buf breaking
      uses: bufbuild/buf-breaking-action@v1
      with:
        input: ${{ inputs.path }}
        against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1,subdir=${{ inputs.path }}"
