#!/bin/bash
set -e

root="$(git rev-parse --show-toplevel)"
name='tdl-dev-broker'
tag='unstoppablemango/tdl-broker:local'

if docker inspect "$name" &>/dev/null; then
	echo 'The broker is already running'
	exit 0
fi

make -C "$root/docker" broker BROKER_TAG="$tag"

echo "Running '$name' as '$tag'"
docker run --rm -it \
	--volume "$root/hack/run:/var/run/tdl" \
	--mount type=tmpfs,destination=/app/plugins \
	--name "$name" "$tag"

# docker logs "$name"
