// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: unmango/dev/ux/v1alpha1/ux.proto

package uxv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UxService_Gen_FullMethodName = "/unmango.dev.ux.v1alpha1.UxService/Gen"
)

// UxServiceClient is the client API for UxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UxServiceClient interface {
	Gen(ctx context.Context, in *GenRequest, opts ...grpc.CallOption) (*GenResponse, error)
}

type uxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUxServiceClient(cc grpc.ClientConnInterface) UxServiceClient {
	return &uxServiceClient{cc}
}

func (c *uxServiceClient) Gen(ctx context.Context, in *GenRequest, opts ...grpc.CallOption) (*GenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenResponse)
	err := c.cc.Invoke(ctx, UxService_Gen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UxServiceServer is the server API for UxService service.
// All implementations must embed UnimplementedUxServiceServer
// for forward compatibility.
type UxServiceServer interface {
	Gen(context.Context, *GenRequest) (*GenResponse, error)
	mustEmbedUnimplementedUxServiceServer()
}

// UnimplementedUxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUxServiceServer struct{}

func (UnimplementedUxServiceServer) Gen(context.Context, *GenRequest) (*GenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Gen not implemented")
}
func (UnimplementedUxServiceServer) mustEmbedUnimplementedUxServiceServer() {}
func (UnimplementedUxServiceServer) testEmbeddedByValue()                   {}

// UnsafeUxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UxServiceServer will
// result in compilation errors.
type UnsafeUxServiceServer interface {
	mustEmbedUnimplementedUxServiceServer()
}

func RegisterUxServiceServer(s grpc.ServiceRegistrar, srv UxServiceServer) {
	// If the following call pancis, it indicates UnimplementedUxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UxService_ServiceDesc, srv)
}

func _UxService_Gen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UxServiceServer).Gen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UxService_Gen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UxServiceServer).Gen(ctx, req.(*GenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UxService_ServiceDesc is the grpc.ServiceDesc for UxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "unmango.dev.ux.v1alpha1.UxService",
	HandlerType: (*UxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Gen",
			Handler:    _UxService_Gen_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "unmango/dev/ux/v1alpha1/ux.proto",
}
