// The TDL plugin protocol: the messages a backend exchanges with tdl,
// whether it is compiled in or run as a subprocess.
//
// See docs/design/plugins.md for the protocol and
// docs/design/plugins-plan.md for what is implemented so far.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tdl/plugin/v1/plugin.proto

package plugin

import (
	ir "github.com/unstoppablemango/tdl/ir"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity is how much a diagnostic matters.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_ERROR       Severity = 1
	Severity_SEVERITY_WARNING     Severity = 2
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_ERROR",
		2: "SEVERITY_WARNING",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_ERROR":       1,
		"SEVERITY_WARNING":     2,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_tdl_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_tdl_plugin_v1_plugin_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_tdl_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

// Handshake is what tdl sends first, before any request.
//
// A plugin that cannot read what is coming refuses here rather than
// silently ignoring fields it was compiled before and emitting subtly
// wrong code with no diagnostic anywhere.
type Handshake struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// framing_version is the wire framing this connection uses. Version 1 is
	// a varint length prefix followed by an encoded message, in both
	// directions. It exists so a later version can offer something else and
	// an older plugin can decline.
	FramingVersion int32 `protobuf:"varint,1,opt,name=framing_version,json=framingVersion" json:"framing_version,omitempty"`
	// ir_version is the protobuf package the model is encoded with, such as
	// "tdl.ir.v1". Within a version, field numbers are never reused and new
	// fields are additive.
	IrVersion string `protobuf:"bytes,2,opt,name=ir_version,json=irVersion" json:"ir_version,omitempty"`
	// watch says this connection may serve more than one request, which a
	// plugin declaring reuse should expect.
	Watch         bool `protobuf:"varint,3,opt,name=watch" json:"watch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_tdl_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_tdl_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Handshake) GetFramingVersion() int32 {
	if x != nil {
		return x.FramingVersion
	}
	return 0
}

func (x *Handshake) GetIrVersion() string {
	if x != nil {
		return x.IrVersion
	}
	return ""
}

func (x *Handshake) GetWatch() bool {
	if x != nil {
		return x.Watch
	}
	return false
}

// HandshakeReply is the plugin's answer.
type HandshakeReply struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted" json:"accepted,omitempty"`
	// refusal says what the plugin needed, when accepted is false. A
	// refusal naming both versions is the point of the handshake.
	Refusal string `protobuf:"bytes,2,opt,name=refusal" json:"refusal,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Version string `protobuf:"bytes,4,opt,name=version" json:"version,omitempty"`
	// directives are what this backend understands. tdl checks the target
	// block against them before generating; see DirectiveSpec.
	Directives    []*DirectiveSpec `protobuf:"bytes,5,rep,name=directives" json:"directives,omitempty"`
	Features      *Features        `protobuf:"bytes,6,opt,name=features" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeReply) Reset() {
	*x = HandshakeReply{}
	mi := &file_tdl_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeReply) ProtoMessage() {}

func (x *HandshakeReply) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeReply.ProtoReflect.Descriptor instead.
func (*HandshakeReply) Descriptor() ([]byte, []int) {
	return file_tdl_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeReply) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandshakeReply) GetRefusal() string {
	if x != nil {
		return x.Refusal
	}
	return ""
}

func (x *HandshakeReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HandshakeReply) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HandshakeReply) GetDirectives() []*DirectiveSpec {
	if x != nil {
		return x.Directives
	}
	return nil
}

func (x *HandshakeReply) GetFeatures() *Features {
	if x != nil {
		return x.Features
	}
	return nil
}

// DirectiveSpec is the shape of one directive a backend accepts.
//
// A directive tdl finds in a target block and does not find here is a
// warning and is passed through anyway: under-declaring is a plugin bug
// that should not break a working project.
type DirectiveSpec struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	MinArgs int32                  `protobuf:"varint,2,opt,name=min_args,json=minArgs" json:"min_args,omitempty"`
	// max_args is the largest number of arguments accepted, or -1 for any
	// number.
	MaxArgs int32 `protobuf:"varint,3,opt,name=max_args,json=maxArgs" json:"max_args,omitempty"`
	// arg_kinds constrains each argument by position. An empty list accepts
	// any kind, and a list shorter than the argument count constrains only
	// the arguments it covers.
	ArgKinds      []ir.LiteralKind `protobuf:"varint,4,rep,packed,name=arg_kinds,json=argKinds,enum=tdl.ir.v1.LiteralKind" json:"arg_kinds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectiveSpec) Reset() {
	*x = DirectiveSpec{}
	mi := &file_tdl_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectiveSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectiveSpec) ProtoMessage() {}

func (x *DirectiveSpec) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectiveSpec.ProtoReflect.Descriptor instead.
func (*DirectiveSpec) Descriptor() ([]byte, []int) {
	return file_tdl_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *DirectiveSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirectiveSpec) GetMinArgs() int32 {
	if x != nil {
		return x.MinArgs
	}
	return 0
}

func (x *DirectiveSpec) GetMaxArgs() int32 {
	if x != nil {
		return x.MaxArgs
	}
	return 0
}

func (x *DirectiveSpec) GetArgKinds() []ir.LiteralKind {
	if x != nil {
		return x.ArgKinds
	}
	return nil
}

// Features are the optional parts of the protocol a backend supports.
type Features struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reuse says the plugin can serve more than one request on a
	// connection. It must treat each as independent.
	Reuse         bool `protobuf:"varint,1,opt,name=reuse" json:"reuse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Features) Reset() {
	*x = Features{}
	mi := &file_tdl_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Features) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Features) ProtoMessage() {}

func (x *Features) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Features.ProtoReflect.Descriptor instead.
func (*Features) Descriptor() ([]byte, []int) {
	return file_tdl_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Features) GetReuse() bool {
	if x != nil {
		return x.Reuse
	}
	return false
}

// Request is everything a backend needs for one generation. Nothing
// travels in argv or environment variables.
type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target names the block being served. The model carries directives for
	// every target block in it, each tagged with the block it came from, so
	// a backend keeps the ones matching this name.
	Target string `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	// model is one package, with the prelude's declarations merged into it.
	// See docs/design/plugins.md for what that means for a backend.
	Model *ir.Model `protobuf:"bytes,2,opt,name=model" json:"model,omitempty"`
	// out is the directory the response's paths are relative to.
	Out string `protobuf:"bytes,3,opt,name=out" json:"out,omitempty"`
	// dry_run says tdl will diff the response against disk rather than
	// write it. A backend that would do expensive work it knows cannot
	// affect the answer may skip it; one that ignores the flag is correct,
	// only slower.
	DryRun        bool `protobuf:"varint,4,opt,name=dry_run,json=dryRun" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_tdl_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_tdl_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Request) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Request) GetModel() *ir.Model {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *Request) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

func (x *Request) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

// Response is what a backend returns. It returns file contents rather
// than writing files, which is what lets tdl enforce path confinement,
// --verify, and --clean rather than asking every backend to honour them.
type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Files []*File                `protobuf:"bytes,1,rep,name=files" json:"files,omitempty"`
	// post names commands to run over the written files, by name only. The
	// project decides what a name maps to; a name it has not declared is
	// skipped with a warning.
	Post          []string      `protobuf:"bytes,2,rep,name=post" json:"post,omitempty"`
	Diagnostics   []*Diagnostic `protobuf:"bytes,3,rep,name=diagnostics" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_tdl_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_tdl_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Response) GetPost() []string {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *Response) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

// File is one generated file, with a path relative to Request.out. An
// absolute path, or one containing "..", is an error and nothing is
// written.
type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_tdl_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_tdl_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// Diagnostic is a problem a backend found.
//
// It carries a position rather than a node ID: ir has three ID spaces,
// into declarations, types, and externs, and an ID alone does not say
// which. Every ir node carries its own position, so a backend copies the
// one it is complaining about.
type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      Severity               `protobuf:"varint,1,opt,name=severity,enum=tdl.plugin.v1.Severity" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Position      *ir.Position           `protobuf:"bytes,3,opt,name=position" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_tdl_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_tdl_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *Diagnostic) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetPosition() *ir.Position {
	if x != nil {
		return x.Position
	}
	return nil
}

var File_tdl_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_tdl_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1atdl/plugin/v1/plugin.proto\x12\rtdl.plugin.v1\x1a!google/protobuf/go_features.proto\x1a\x12tdl/ir/v1/ir.proto\"i\n" +
	"\tHandshake\x12'\n" +
	"\x0fframing_version\x18\x01 \x01(\x05R\x0eframingVersion\x12\x1d\n" +
	"\n" +
	"ir_version\x18\x02 \x01(\tR\tirVersion\x12\x14\n" +
	"\x05watch\x18\x03 \x01(\bR\x05watch\"\xe7\x01\n" +
	"\x0eHandshakeReply\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\arefusal\x18\x02 \x01(\tR\arefusal\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12<\n" +
	"\n" +
	"directives\x18\x05 \x03(\v2\x1c.tdl.plugin.v1.DirectiveSpecR\n" +
	"directives\x123\n" +
	"\bfeatures\x18\x06 \x01(\v2\x17.tdl.plugin.v1.FeaturesR\bfeatures\"\x8e\x01\n" +
	"\rDirectiveSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bmin_args\x18\x02 \x01(\x05R\aminArgs\x12\x19\n" +
	"\bmax_args\x18\x03 \x01(\x05R\amaxArgs\x123\n" +
	"\targ_kinds\x18\x04 \x03(\x0e2\x16.tdl.ir.v1.LiteralKindR\bargKinds\" \n" +
	"\bFeatures\x12\x14\n" +
	"\x05reuse\x18\x01 \x01(\bR\x05reuse\"t\n" +
	"\aRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12&\n" +
	"\x05model\x18\x02 \x01(\v2\x10.tdl.ir.v1.ModelR\x05model\x12\x10\n" +
	"\x03out\x18\x03 \x01(\tR\x03out\x12\x17\n" +
	"\adry_run\x18\x04 \x01(\bR\x06dryRun\"\x86\x01\n" +
	"\bResponse\x12)\n" +
	"\x05files\x18\x01 \x03(\v2\x13.tdl.plugin.v1.FileR\x05files\x12\x12\n" +
	"\x04post\x18\x02 \x03(\tR\x04post\x12;\n" +
	"\vdiagnostics\x18\x03 \x03(\v2\x19.tdl.plugin.v1.DiagnosticR\vdiagnostics\"4\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\x8c\x01\n" +
	"\n" +
	"Diagnostic\x123\n" +
	"\bseverity\x18\x01 \x01(\x0e2\x17.tdl.plugin.v1.SeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\bposition\x18\x03 \x01(\v2\x13.tdl.ir.v1.PositionR\bposition*N\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x01\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x02B\xa8\x01\n" +
	"\x11com.tdl.plugin.v1B\vPluginProtoP\x01Z&github.com/unstoppablemango/tdl/plugin\xa2\x02\x03TPX\xaa\x02\rTdl.Plugin.V1\xca\x02\rTdl\\Plugin\\V1\xe2\x02\x19Tdl\\Plugin\\V1\\GPBMetadata\xea\x02\x0fTdl::Plugin::V1\x92\x03\a\xd2>\x02\x10\x01\b\x02b\beditionsp\xe9\a"

var (
	file_tdl_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_tdl_plugin_v1_plugin_proto_rawDescData []byte
)

func file_tdl_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_tdl_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_tdl_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tdl_plugin_v1_plugin_proto_rawDesc), len(file_tdl_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_tdl_plugin_v1_plugin_proto_rawDescData
}

var file_tdl_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tdl_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_tdl_plugin_v1_plugin_proto_goTypes = []any{
	(Severity)(0),          // 0: tdl.plugin.v1.Severity
	(*Handshake)(nil),      // 1: tdl.plugin.v1.Handshake
	(*HandshakeReply)(nil), // 2: tdl.plugin.v1.HandshakeReply
	(*DirectiveSpec)(nil),  // 3: tdl.plugin.v1.DirectiveSpec
	(*Features)(nil),       // 4: tdl.plugin.v1.Features
	(*Request)(nil),        // 5: tdl.plugin.v1.Request
	(*Response)(nil),       // 6: tdl.plugin.v1.Response
	(*File)(nil),           // 7: tdl.plugin.v1.File
	(*Diagnostic)(nil),     // 8: tdl.plugin.v1.Diagnostic
	(ir.LiteralKind)(0),    // 9: tdl.ir.v1.LiteralKind
	(*ir.Model)(nil),       // 10: tdl.ir.v1.Model
	(*ir.Position)(nil),    // 11: tdl.ir.v1.Position
}
var file_tdl_plugin_v1_plugin_proto_depIdxs = []int32{
	3,  // 0: tdl.plugin.v1.HandshakeReply.directives:type_name -> tdl.plugin.v1.DirectiveSpec
	4,  // 1: tdl.plugin.v1.HandshakeReply.features:type_name -> tdl.plugin.v1.Features
	9,  // 2: tdl.plugin.v1.DirectiveSpec.arg_kinds:type_name -> tdl.ir.v1.LiteralKind
	10, // 3: tdl.plugin.v1.Request.model:type_name -> tdl.ir.v1.Model
	7,  // 4: tdl.plugin.v1.Response.files:type_name -> tdl.plugin.v1.File
	8,  // 5: tdl.plugin.v1.Response.diagnostics:type_name -> tdl.plugin.v1.Diagnostic
	0,  // 6: tdl.plugin.v1.Diagnostic.severity:type_name -> tdl.plugin.v1.Severity
	11, // 7: tdl.plugin.v1.Diagnostic.position:type_name -> tdl.ir.v1.Position
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_tdl_plugin_v1_plugin_proto_init() }
func file_tdl_plugin_v1_plugin_proto_init() {
	if File_tdl_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tdl_plugin_v1_plugin_proto_rawDesc), len(file_tdl_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tdl_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_tdl_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_tdl_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_tdl_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_tdl_plugin_v1_plugin_proto = out.File
	file_tdl_plugin_v1_plugin_proto_goTypes = nil
	file_tdl_plugin_v1_plugin_proto_depIdxs = nil
}
