// The TDL intermediate representation: the resolved semantic model that
// backends consume, in-process and over the plugin protocol.
//
// See docs/design/ir.md for the decisions this schema encodes and
// docs/design/ir-plan.md for what is implemented so far. The schema grows
// one phase at a time; constraints, defaults, classes, instances, imports,
// and target directives are not here yet.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tdl/ir/v1/ir.proto

package ir

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StructKind distinguishes the three declarations that share a body.
type StructKind int32

const (
	StructKind_STRUCT_KIND_UNSPECIFIED StructKind = 0
	StructKind_STRUCT_KIND_ENTITY      StructKind = 1 // identity that survives changes to its contents
	StructKind_STRUCT_KIND_VALUE       StructKind = 2 // defined entirely by its contents
	StructKind_STRUCT_KIND_MIXIN       StructKind = 3 // reuse, copied into the including declaration
)

// Enum value maps for StructKind.
var (
	StructKind_name = map[int32]string{
		0: "STRUCT_KIND_UNSPECIFIED",
		1: "STRUCT_KIND_ENTITY",
		2: "STRUCT_KIND_VALUE",
		3: "STRUCT_KIND_MIXIN",
	}
	StructKind_value = map[string]int32{
		"STRUCT_KIND_UNSPECIFIED": 0,
		"STRUCT_KIND_ENTITY":      1,
		"STRUCT_KIND_VALUE":       2,
		"STRUCT_KIND_MIXIN":       3,
	}
)

func (x StructKind) Enum() *StructKind {
	p := new(StructKind)
	*p = x
	return p
}

func (x StructKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StructKind) Descriptor() protoreflect.EnumDescriptor {
	return file_tdl_ir_v1_ir_proto_enumTypes[0].Descriptor()
}

func (StructKind) Type() protoreflect.EnumType {
	return &file_tdl_ir_v1_ir_proto_enumTypes[0]
}

func (x StructKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StructKind.Descriptor instead.
func (StructKind) EnumDescriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{0}
}

// KindAtom is a base kind.
type KindAtom int32

const (
	KindAtom_KIND_ATOM_UNSPECIFIED KindAtom = 0
	KindAtom_KIND_ATOM_TYPE        KindAtom = 1
	KindAtom_KIND_ATOM_UNIT        KindAtom = 2
)

// Enum value maps for KindAtom.
var (
	KindAtom_name = map[int32]string{
		0: "KIND_ATOM_UNSPECIFIED",
		1: "KIND_ATOM_TYPE",
		2: "KIND_ATOM_UNIT",
	}
	KindAtom_value = map[string]int32{
		"KIND_ATOM_UNSPECIFIED": 0,
		"KIND_ATOM_TYPE":        1,
		"KIND_ATOM_UNIT":        2,
	}
)

func (x KindAtom) Enum() *KindAtom {
	p := new(KindAtom)
	*p = x
	return p
}

func (x KindAtom) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KindAtom) Descriptor() protoreflect.EnumDescriptor {
	return file_tdl_ir_v1_ir_proto_enumTypes[1].Descriptor()
}

func (KindAtom) Type() protoreflect.EnumType {
	return &file_tdl_ir_v1_ir_proto_enumTypes[1]
}

func (x KindAtom) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KindAtom.Descriptor instead.
func (KindAtom) EnumDescriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{1}
}

// SyntacticForm records how a type reference was written.
//
// Lowering is authoritative: `[T]` is `List<T>` and `T?` is `Option<T>`
// whatever this says. The form is advisory, for a backend that wants `*T`
// for `T?` and a wrapper for an explicit `Option<T>`. A backend that treats
// them alike ignores it.
type SyntacticForm int32

const (
	SyntacticForm_SYNTACTIC_FORM_UNSPECIFIED SyntacticForm = 0
	SyntacticForm_SYNTACTIC_FORM_NAMED       SyntacticForm = 1 // User, List<T>
	SyntacticForm_SYNTACTIC_FORM_BRACKETS    SyntacticForm = 2 // [T]
	SyntacticForm_SYNTACTIC_FORM_BRACES      SyntacticForm = 3 // {T}
	SyntacticForm_SYNTACTIC_FORM_ARROW       SyntacticForm = 4 // {K -> V}
	SyntacticForm_SYNTACTIC_FORM_QUESTION    SyntacticForm = 5 // T?
	SyntacticForm_SYNTACTIC_FORM_OR_NULL     SyntacticForm = 6 // T | null
)

// Enum value maps for SyntacticForm.
var (
	SyntacticForm_name = map[int32]string{
		0: "SYNTACTIC_FORM_UNSPECIFIED",
		1: "SYNTACTIC_FORM_NAMED",
		2: "SYNTACTIC_FORM_BRACKETS",
		3: "SYNTACTIC_FORM_BRACES",
		4: "SYNTACTIC_FORM_ARROW",
		5: "SYNTACTIC_FORM_QUESTION",
		6: "SYNTACTIC_FORM_OR_NULL",
	}
	SyntacticForm_value = map[string]int32{
		"SYNTACTIC_FORM_UNSPECIFIED": 0,
		"SYNTACTIC_FORM_NAMED":       1,
		"SYNTACTIC_FORM_BRACKETS":    2,
		"SYNTACTIC_FORM_BRACES":      3,
		"SYNTACTIC_FORM_ARROW":       4,
		"SYNTACTIC_FORM_QUESTION":    5,
		"SYNTACTIC_FORM_OR_NULL":     6,
	}
)

func (x SyntacticForm) Enum() *SyntacticForm {
	p := new(SyntacticForm)
	*p = x
	return p
}

func (x SyntacticForm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyntacticForm) Descriptor() protoreflect.EnumDescriptor {
	return file_tdl_ir_v1_ir_proto_enumTypes[2].Descriptor()
}

func (SyntacticForm) Type() protoreflect.EnumType {
	return &file_tdl_ir_v1_ir_proto_enumTypes[2]
}

func (x SyntacticForm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyntacticForm.Descriptor instead.
func (SyntacticForm) EnumDescriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{2}
}

// ID references a node by its index into a table and by its fully qualified
// name.
//
// The index is what lookups use. The name is what appears in diagnostics,
// in dumps, and in target paths, and it is stable across edits in a way the
// index is not. Which table an ID indexes is fixed by the field holding it.
//
// An index of -1 means the name did not resolve. Name resolution turns that
// into a diagnostic; until then it records what was written.
type ID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ID) Reset() {
	*x = ID{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{0}
}

func (x *ID) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Position is a location in a source file.
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Line          int32                  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{1}
}

func (x *Position) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Position) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Position) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

// Deprecation marks a node as on its way out.
type Deprecation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // empty when written without one
	Position      *Position              `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deprecation) Reset() {
	*x = Deprecation{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deprecation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deprecation) ProtoMessage() {}

func (x *Deprecation) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deprecation.ProtoReflect.Descriptor instead.
func (*Deprecation) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{2}
}

func (x *Deprecation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Deprecation) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// Meta is the source fidelity every node carries: what it is called, what
// was written about it, where it came from, whether it is deprecated, and
// where it sat among its siblings.
//
// Declaration order is kept so generated output is stable and diffable.
type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // fully qualified for a declaration, bare for a member
	Doc           []string               `protobuf:"bytes,2,rep,name=doc,proto3" json:"doc,omitempty"`
	Position      *Position              `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Deprecated    *Deprecation           `protobuf:"bytes,4,opt,name=deprecated,proto3" json:"deprecated,omitempty"` // unset when not deprecated
	Order         int32                  `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{3}
}

func (x *Meta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Meta) GetDoc() []string {
	if x != nil {
		return x.Doc
	}
	return nil
}

func (x *Meta) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Meta) GetDeprecated() *Deprecation {
	if x != nil {
		return x.Deprecated
	}
	return nil
}

func (x *Meta) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

// Model is one package: every declaration in it, and every type reference
// those declarations use.
//
// Two flat tables, two ID spaces. Declarations from imported packages are
// not inlined; a reference into a dependency is an ID whose name carries
// that package.
type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Decls         []*Decl                `protobuf:"bytes,2,rep,name=decls,proto3" json:"decls,omitempty"`
	Types         []*Type                `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"`
	Imports       []*Import              `protobuf:"bytes,4,rep,name=imports,proto3" json:"imports,omitempty"`
	Externs       []*Extern              `protobuf:"bytes,5,rep,name=externs,proto3" json:"externs,omitempty"`
	Instances     []*Instance            `protobuf:"bytes,6,rep,name=instances,proto3" json:"instances,omitempty"`
	Satisfies     []*Satisfaction        `protobuf:"bytes,7,rep,name=satisfies,proto3" json:"satisfies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{4}
}

func (x *Model) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Model) GetDecls() []*Decl {
	if x != nil {
		return x.Decls
	}
	return nil
}

func (x *Model) GetTypes() []*Type {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *Model) GetImports() []*Import {
	if x != nil {
		return x.Imports
	}
	return nil
}

func (x *Model) GetExterns() []*Extern {
	if x != nil {
		return x.Externs
	}
	return nil
}

func (x *Model) GetInstances() []*Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *Model) GetSatisfies() []*Satisfaction {
	if x != nil {
		return x.Satisfies
	}
	return nil
}

// Instance declares that a type satisfies a class.
//
// `instance C for T` is sugar for `instance C<T>`, and lowering normalizes
// it: by here there is one form. An instance is not a type name, so it
// lives in its own table rather than among the declarations.
type Instance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Params        []*Param               `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	Class         *ClassRef              `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	Requires      []*ClassRef            `protobuf:"bytes,4,rep,name=requires,proto3" json:"requires,omitempty"` // conditions on this instance
	Binds         []*AssocBind           `protobuf:"bytes,5,rep,name=binds,proto3" json:"binds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{5}
}

func (x *Instance) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Instance) GetParams() []*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Instance) GetClass() *ClassRef {
	if x != nil {
		return x.Class
	}
	return nil
}

func (x *Instance) GetRequires() []*ClassRef {
	if x != nil {
		return x.Requires
	}
	return nil
}

func (x *Instance) GetBinds() []*AssocBind {
	if x != nil {
		return x.Binds
	}
	return nil
}

// AssocBind supplies a type for one of a class's associated type
// requirements.
type AssocBind struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          *ID                    `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // indexes Model.types
	Position      *Position              `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssocBind) Reset() {
	*x = AssocBind{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssocBind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssocBind) ProtoMessage() {}

func (x *AssocBind) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssocBind.ProtoReflect.Descriptor instead.
func (*AssocBind) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{6}
}

func (x *AssocBind) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssocBind) GetType() *ID {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *AssocBind) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// ClassRef names a class, applied to arguments.
type ClassRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         *ID                    `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`   // indexes Model.decls; unset when extern is set
	Extern        *ID                    `protobuf:"bytes,2,opt,name=extern,proto3" json:"extern,omitempty"` // indexes Model.externs
	Args          []*ID                  `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`     // indexes Model.types
	Position      *Position              `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassRef) Reset() {
	*x = ClassRef{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassRef) ProtoMessage() {}

func (x *ClassRef) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassRef.ProtoReflect.Descriptor instead.
func (*ClassRef) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{7}
}

func (x *ClassRef) GetClass() *ID {
	if x != nil {
		return x.Class
	}
	return nil
}

func (x *ClassRef) GetExtern() *ID {
	if x != nil {
		return x.Extern
	}
	return nil
}

func (x *ClassRef) GetArgs() []*ID {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ClassRef) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// Satisfaction is the computed answer to "what satisfies this class",
// closed over the classes a class requires.
//
// A backend applying a class-scoped target directive reads this and never
// reasons about instances. The declared instances are still in the model
// for one that wants them.
type Satisfaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         *ID                    `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"` // indexes Model.decls
	Decls         []*ID                  `protobuf:"bytes,2,rep,name=decls,proto3" json:"decls,omitempty"` // indexes Model.decls
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Satisfaction) Reset() {
	*x = Satisfaction{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Satisfaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Satisfaction) ProtoMessage() {}

func (x *Satisfaction) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Satisfaction.ProtoReflect.Descriptor instead.
func (*Satisfaction) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{8}
}

func (x *Satisfaction) GetClass() *ID {
	if x != nil {
		return x.Class
	}
	return nil
}

func (x *Satisfaction) GetDecls() []*ID {
	if x != nil {
		return x.Decls
	}
	return nil
}

// Import is one `import "path" as alias` in the file.
type Import struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`       // as written
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`     // "_" merges the imported names into this scope
	Package       string                 `protobuf:"bytes,3,opt,name=package,proto3" json:"package,omitempty"` // the package the imported file declares
	Position      *Position              `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Import) Reset() {
	*x = Import{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Import) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Import) ProtoMessage() {}

func (x *Import) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Import.ProtoReflect.Descriptor instead.
func (*Import) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{9}
}

func (x *Import) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Import) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Import) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Import) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// Extern is a declaration in another package that this one refers to.
//
// Dependencies are not inlined: a backend either resolves an extern
// through the import table and generates a reference, or treats it as
// foreign and maps it with a target directive.
type Extern struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`   // the declaring package
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`         // the declaration's name within it
	Position      *Position              `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"` // where this model first referred to it
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extern) Reset() {
	*x = Extern{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extern) ProtoMessage() {}

func (x *Extern) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extern.ProtoReflect.Descriptor instead.
func (*Extern) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{10}
}

func (x *Extern) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Extern) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Extern) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// Decl is one declaration. The forms split by nature rather than
// collapsing into one tagged message or fragmenting into eight: everything
// with fields shares a shape, and a form that has no fields does not carry
// the machinery for them.
type Decl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Meta  *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Types that are valid to be assigned to Node:
	//
	//	*Decl_Primitive
	//	*Decl_Alias
	//	*Decl_Newtype
	//	*Decl_Structure
	//	*Decl_Enumeration
	//	*Decl_Class
	Node          isDecl_Node `protobuf_oneof:"node"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decl) Reset() {
	*x = Decl{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decl) ProtoMessage() {}

func (x *Decl) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decl.ProtoReflect.Descriptor instead.
func (*Decl) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{11}
}

func (x *Decl) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Decl) GetNode() isDecl_Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Decl) GetPrimitive() *Primitive {
	if x != nil {
		if x, ok := x.Node.(*Decl_Primitive); ok {
			return x.Primitive
		}
	}
	return nil
}

func (x *Decl) GetAlias() *Alias {
	if x != nil {
		if x, ok := x.Node.(*Decl_Alias); ok {
			return x.Alias
		}
	}
	return nil
}

func (x *Decl) GetNewtype() *Newtype {
	if x != nil {
		if x, ok := x.Node.(*Decl_Newtype); ok {
			return x.Newtype
		}
	}
	return nil
}

func (x *Decl) GetStructure() *Struct {
	if x != nil {
		if x, ok := x.Node.(*Decl_Structure); ok {
			return x.Structure
		}
	}
	return nil
}

func (x *Decl) GetEnumeration() *Enum {
	if x != nil {
		if x, ok := x.Node.(*Decl_Enumeration); ok {
			return x.Enumeration
		}
	}
	return nil
}

func (x *Decl) GetClass() *Class {
	if x != nil {
		if x, ok := x.Node.(*Decl_Class); ok {
			return x.Class
		}
	}
	return nil
}

type isDecl_Node interface {
	isDecl_Node()
}

type Decl_Primitive struct {
	Primitive *Primitive `protobuf:"bytes,2,opt,name=primitive,proto3,oneof"`
}

type Decl_Alias struct {
	Alias *Alias `protobuf:"bytes,3,opt,name=alias,proto3,oneof"`
}

type Decl_Newtype struct {
	Newtype *Newtype `protobuf:"bytes,4,opt,name=newtype,proto3,oneof"`
}

type Decl_Structure struct {
	Structure *Struct `protobuf:"bytes,5,opt,name=structure,proto3,oneof"`
}

type Decl_Enumeration struct {
	Enumeration *Enum `protobuf:"bytes,6,opt,name=enumeration,proto3,oneof"`
}

type Decl_Class struct {
	Class *Class `protobuf:"bytes,7,opt,name=class,proto3,oneof"`
}

func (*Decl_Primitive) isDecl_Node() {}

func (*Decl_Alias) isDecl_Node() {}

func (*Decl_Newtype) isDecl_Node() {}

func (*Decl_Structure) isDecl_Node() {}

func (*Decl_Enumeration) isDecl_Node() {}

func (*Decl_Class) isDecl_Node() {}

// Class is a contract. It declares nothing into the types that satisfy it;
// conformance is nominal and always declared.
type Class struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Params          []*Param               `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`
	FunDeps         []*FunDep              `protobuf:"bytes,2,rep,name=fun_deps,json=funDeps,proto3" json:"fun_deps,omitempty"`
	RequiresClasses []*ClassRef            `protobuf:"bytes,3,rep,name=requires_classes,json=requiresClasses,proto3" json:"requires_classes,omitempty"` // classes an implementor must also satisfy
	Constraints     []*ClassRef            `protobuf:"bytes,4,rep,name=constraints,proto3" json:"constraints,omitempty"`                                // the `requires` clause on this class's parameters
	Fields          []*Field               `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	RequiresKey     bool                   `protobuf:"varint,6,opt,name=requires_key,json=requiresKey,proto3" json:"requires_key,omitempty"` // a bare `key` in the body
	AssocTypes      []*AssocType           `protobuf:"bytes,7,rep,name=assoc_types,json=assocTypes,proto3" json:"assoc_types,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Class) Reset() {
	*x = Class{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Class) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Class) ProtoMessage() {}

func (x *Class) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Class.ProtoReflect.Descriptor instead.
func (*Class) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{12}
}

func (x *Class) GetParams() []*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Class) GetFunDeps() []*FunDep {
	if x != nil {
		return x.FunDeps
	}
	return nil
}

func (x *Class) GetRequiresClasses() []*ClassRef {
	if x != nil {
		return x.RequiresClasses
	}
	return nil
}

func (x *Class) GetConstraints() []*ClassRef {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *Class) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Class) GetRequiresKey() bool {
	if x != nil {
		return x.RequiresKey
	}
	return false
}

func (x *Class) GetAssocTypes() []*AssocType {
	if x != nil {
		return x.AssocTypes
	}
	return nil
}

// FunDep states that some parameters determine others, which makes a
// multi-parameter class a function rather than a table.
type FunDep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          []string               `protobuf:"bytes,1,rep,name=from,proto3" json:"from,omitempty"`
	To            []string               `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Position      *Position              `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunDep) Reset() {
	*x = FunDep{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunDep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunDep) ProtoMessage() {}

func (x *FunDep) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunDep.ProtoReflect.Descriptor instead.
func (*FunDep) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{13}
}

func (x *FunDep) GetFrom() []string {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *FunDep) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *FunDep) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// AssocType is a type an implementor must supply and an instance binds.
type AssocType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Kind          *Kind                  `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssocType) Reset() {
	*x = AssocType{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssocType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssocType) ProtoMessage() {}

func (x *AssocType) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssocType.ProtoReflect.Descriptor instead.
func (*AssocType) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{14}
}

func (x *AssocType) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AssocType) GetKind() *Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

// Primitive is an opaque, irreducible root type.
type Primitive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          *Kind                  `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // unset when the kind is left to inference
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Primitive) Reset() {
	*x = Primitive{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Primitive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Primitive) ProtoMessage() {}

func (x *Primitive) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Primitive.ProtoReflect.Descriptor instead.
func (*Primitive) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{15}
}

func (x *Primitive) GetKind() *Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

// Alias is a transparent abbreviation, expanded rather than referenced.
type Alias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        []*Param               `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`
	Target        *ID                    `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // indexes Model.types
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alias) Reset() {
	*x = Alias{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alias) ProtoMessage() {}

func (x *Alias) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alias.ProtoReflect.Descriptor instead.
func (*Alias) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{16}
}

func (x *Alias) GetParams() []*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Alias) GetTarget() *ID {
	if x != nil {
		return x.Target
	}
	return nil
}

// Newtype is a distinct type over another, not interchangeable with it.
type Newtype struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        []*Param               `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`
	Base          *ID                    `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`               // indexes Model.types
	Constraints   []*ClassRef            `protobuf:"bytes,3,rep,name=constraints,proto3" json:"constraints,omitempty"` // the `requires` clause on its parameters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Newtype) Reset() {
	*x = Newtype{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Newtype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Newtype) ProtoMessage() {}

func (x *Newtype) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Newtype.ProtoReflect.Descriptor instead.
func (*Newtype) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{17}
}

func (x *Newtype) GetParams() []*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Newtype) GetBase() *ID {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Newtype) GetConstraints() []*ClassRef {
	if x != nil {
		return x.Constraints
	}
	return nil
}

// Struct is an entity, a value, or a mixin.
type Struct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          StructKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=tdl.ir.v1.StructKind" json:"kind,omitempty"`
	Params        []*Param               `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	Fields        []*Field               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Conforms      []*ClassRef            `protobuf:"bytes,4,rep,name=conforms,proto3" json:"conforms,omitempty"`       // classes this declaration says it satisfies
	Constraints   []*ClassRef            `protobuf:"bytes,5,rep,name=constraints,proto3" json:"constraints,omitempty"` // the `requires` clause on its parameters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Struct) Reset() {
	*x = Struct{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct) ProtoMessage() {}

func (x *Struct) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Struct.ProtoReflect.Descriptor instead.
func (*Struct) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{18}
}

func (x *Struct) GetKind() StructKind {
	if x != nil {
		return x.Kind
	}
	return StructKind_STRUCT_KIND_UNSPECIFIED
}

func (x *Struct) GetParams() []*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Struct) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Struct) GetConforms() []*ClassRef {
	if x != nil {
		return x.Conforms
	}
	return nil
}

func (x *Struct) GetConstraints() []*ClassRef {
	if x != nil {
		return x.Constraints
	}
	return nil
}

// Enum is a closed set of variants. A variant may carry fields, which makes
// enum the language's sum type.
type Enum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        []*Param               `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`
	Variants      []*Variant             `protobuf:"bytes,2,rep,name=variants,proto3" json:"variants,omitempty"`
	Conforms      []*ClassRef            `protobuf:"bytes,3,rep,name=conforms,proto3" json:"conforms,omitempty"`
	Constraints   []*ClassRef            `protobuf:"bytes,4,rep,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enum) Reset() {
	*x = Enum{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enum) ProtoMessage() {}

func (x *Enum) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enum.ProtoReflect.Descriptor instead.
func (*Enum) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{19}
}

func (x *Enum) GetParams() []*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Enum) GetVariants() []*Variant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *Enum) GetConforms() []*ClassRef {
	if x != nil {
		return x.Conforms
	}
	return nil
}

func (x *Enum) GetConstraints() []*ClassRef {
	if x != nil {
		return x.Constraints
	}
	return nil
}

// Variant is one alternative in an Enum.
type Variant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Fields        []*Field               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variant) Reset() {
	*x = Variant{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variant) ProtoMessage() {}

func (x *Variant) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variant.ProtoReflect.Descriptor instead.
func (*Variant) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{20}
}

func (x *Variant) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Variant) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Field is a named, typed member.
type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Meta  *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Type  *ID                    `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`    // indexes Model.types
	Key   bool                   `protobuf:"varint,3,opt,name=key,proto3" json:"key,omitempty"`     // part of the entity's identity
	Owned bool                   `protobuf:"varint,4,opt,name=owned,proto3" json:"owned,omitempty"` // composition rather than reference
	// included_from names the mixin a field was copied from, so a backend
	// that can express the grouping does not have to reconstruct it. Unset
	// for a field the declaration wrote itself.
	IncludedFrom  *ID `protobuf:"bytes,5,opt,name=included_from,json=includedFrom,proto3" json:"included_from,omitempty"` // indexes Model.decls
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{21}
}

func (x *Field) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Field) GetType() *ID {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Field) GetKey() bool {
	if x != nil {
		return x.Key
	}
	return false
}

func (x *Field) GetOwned() bool {
	if x != nil {
		return x.Owned
	}
	return false
}

func (x *Field) GetIncludedFrom() *ID {
	if x != nil {
		return x.IncludedFrom
	}
	return nil
}

// Param is one type parameter.
type Param struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          *Kind                  `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // unset when inferred from use
	Position      *Position              `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Param) Reset() {
	*x = Param{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{22}
}

func (x *Param) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Param) GetKind() *Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Param) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// Kind is a kind expression: an atom, a parenthesized kind, or either of
// those followed by an arrow. Arrows associate to the right.
type Kind struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Atom          KindAtom               `protobuf:"varint,1,opt,name=atom,proto3,enum=tdl.ir.v1.KindAtom" json:"atom,omitempty"` // unset when paren is set
	Paren         *Kind                  `protobuf:"bytes,2,opt,name=paren,proto3" json:"paren,omitempty"`
	Arrow         *Kind                  `protobuf:"bytes,3,opt,name=arrow,proto3" json:"arrow,omitempty"` // unset for a bare atom
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kind) Reset() {
	*x = Kind{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kind) ProtoMessage() {}

func (x *Kind) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kind.ProtoReflect.Descriptor instead.
func (*Kind) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{23}
}

func (x *Kind) GetAtom() KindAtom {
	if x != nil {
		return x.Atom
	}
	return KindAtom_KIND_ATOM_UNSPECIFIED
}

func (x *Kind) GetParen() *Kind {
	if x != nil {
		return x.Paren
	}
	return nil
}

func (x *Kind) GetArrow() *Kind {
	if x != nil {
		return x.Arrow
	}
	return nil
}

// Type is one interned type reference: a constructor applied to arguments,
// or a reference to a type parameter.
//
// Lowering interns, so two occurrences of the same type share an entry and
// an ID comparison is a type comparison.
type Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctor          *ID                    `protobuf:"bytes,1,opt,name=ctor,proto3" json:"ctor,omitempty"` // indexes Model.decls; unset when param or extern is set
	Args          []*ID                  `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"` // indexes Model.types
	Wrote         SyntacticForm          `protobuf:"varint,3,opt,name=wrote,proto3,enum=tdl.ir.v1.SyntacticForm" json:"wrote,omitempty"`
	Position      *Position              `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Param         *ParamRef              `protobuf:"bytes,5,opt,name=param,proto3" json:"param,omitempty"`   // set instead of ctor for a type parameter
	Extern        *ID                    `protobuf:"bytes,6,opt,name=extern,proto3" json:"extern,omitempty"` // set instead of ctor; indexes Model.externs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{24}
}

func (x *Type) GetCtor() *ID {
	if x != nil {
		return x.Ctor
	}
	return nil
}

func (x *Type) GetArgs() []*ID {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Type) GetWrote() SyntacticForm {
	if x != nil {
		return x.Wrote
	}
	return SyntacticForm_SYNTACTIC_FORM_UNSPECIFIED
}

func (x *Type) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Type) GetParam() *ParamRef {
	if x != nil {
		return x.Param
	}
	return nil
}

func (x *Type) GetExtern() *ID {
	if x != nil {
		return x.Extern
	}
	return nil
}

// ParamRef is a use of a type parameter.
//
// Parameters survive rather than being monomorphized away, so a backend
// with native generics emits them and one without instantiates on its own
// terms.
type ParamRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // into the declaring node's params
	Owner         *ID                    `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`  // the declaration that declares it
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamRef) Reset() {
	*x = ParamRef{}
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamRef) ProtoMessage() {}

func (x *ParamRef) ProtoReflect() protoreflect.Message {
	mi := &file_tdl_ir_v1_ir_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamRef.ProtoReflect.Descriptor instead.
func (*ParamRef) Descriptor() ([]byte, []int) {
	return file_tdl_ir_v1_ir_proto_rawDescGZIP(), []int{25}
}

func (x *ParamRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParamRef) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ParamRef) GetOwner() *ID {
	if x != nil {
		return x.Owner
	}
	return nil
}

var File_tdl_ir_v1_ir_proto protoreflect.FileDescriptor

const file_tdl_ir_v1_ir_proto_rawDesc = "" +
	"\n" +
	"\x12tdl/ir/v1/ir.proto\x12\ttdl.ir.v1\".\n" +
	"\x02ID\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"R\n" +
	"\bPosition\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x03 \x01(\x05R\x06column\"V\n" +
	"\vDeprecation\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12/\n" +
	"\bposition\x18\x02 \x01(\v2\x13.tdl.ir.v1.PositionR\bposition\"\xab\x01\n" +
	"\x04Meta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03doc\x18\x02 \x03(\tR\x03doc\x12/\n" +
	"\bposition\x18\x03 \x01(\v2\x13.tdl.ir.v1.PositionR\bposition\x126\n" +
	"\n" +
	"deprecated\x18\x04 \x01(\v2\x16.tdl.ir.v1.DeprecationR\n" +
	"deprecated\x12\x14\n" +
	"\x05order\x18\x05 \x01(\x05R\x05order\"\xb3\x02\n" +
	"\x05Model\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12%\n" +
	"\x05decls\x18\x02 \x03(\v2\x0f.tdl.ir.v1.DeclR\x05decls\x12%\n" +
	"\x05types\x18\x03 \x03(\v2\x0f.tdl.ir.v1.TypeR\x05types\x12+\n" +
	"\aimports\x18\x04 \x03(\v2\x11.tdl.ir.v1.ImportR\aimports\x12+\n" +
	"\aexterns\x18\x05 \x03(\v2\x11.tdl.ir.v1.ExternR\aexterns\x121\n" +
	"\tinstances\x18\x06 \x03(\v2\x13.tdl.ir.v1.InstanceR\tinstances\x125\n" +
	"\tsatisfies\x18\a \x03(\v2\x17.tdl.ir.v1.SatisfactionR\tsatisfies\"\xe1\x01\n" +
	"\bInstance\x12#\n" +
	"\x04meta\x18\x01 \x01(\v2\x0f.tdl.ir.v1.MetaR\x04meta\x12(\n" +
	"\x06params\x18\x02 \x03(\v2\x10.tdl.ir.v1.ParamR\x06params\x12)\n" +
	"\x05class\x18\x03 \x01(\v2\x13.tdl.ir.v1.ClassRefR\x05class\x12/\n" +
	"\brequires\x18\x04 \x03(\v2\x13.tdl.ir.v1.ClassRefR\brequires\x12*\n" +
	"\x05binds\x18\x05 \x03(\v2\x14.tdl.ir.v1.AssocBindR\x05binds\"s\n" +
	"\tAssocBind\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\x04type\x18\x02 \x01(\v2\r.tdl.ir.v1.IDR\x04type\x12/\n" +
	"\bposition\x18\x03 \x01(\v2\x13.tdl.ir.v1.PositionR\bposition\"\xaa\x01\n" +
	"\bClassRef\x12#\n" +
	"\x05class\x18\x01 \x01(\v2\r.tdl.ir.v1.IDR\x05class\x12%\n" +
	"\x06extern\x18\x02 \x01(\v2\r.tdl.ir.v1.IDR\x06extern\x12!\n" +
	"\x04args\x18\x03 \x03(\v2\r.tdl.ir.v1.IDR\x04args\x12/\n" +
	"\bposition\x18\x04 \x01(\v2\x13.tdl.ir.v1.PositionR\bposition\"X\n" +
	"\fSatisfaction\x12#\n" +
	"\x05class\x18\x01 \x01(\v2\r.tdl.ir.v1.IDR\x05class\x12#\n" +
	"\x05decls\x18\x02 \x03(\v2\r.tdl.ir.v1.IDR\x05decls\"}\n" +
	"\x06Import\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x18\n" +
	"\apackage\x18\x03 \x01(\tR\apackage\x12/\n" +
	"\bposition\x18\x04 \x01(\v2\x13.tdl.ir.v1.PositionR\bposition\"g\n" +
	"\x06Extern\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\bposition\x18\x03 \x01(\v2\x13.tdl.ir.v1.PositionR\bposition\"\xd5\x02\n" +
	"\x04Decl\x12#\n" +
	"\x04meta\x18\x01 \x01(\v2\x0f.tdl.ir.v1.MetaR\x04meta\x124\n" +
	"\tprimitive\x18\x02 \x01(\v2\x14.tdl.ir.v1.PrimitiveH\x00R\tprimitive\x12(\n" +
	"\x05alias\x18\x03 \x01(\v2\x10.tdl.ir.v1.AliasH\x00R\x05alias\x12.\n" +
	"\anewtype\x18\x04 \x01(\v2\x12.tdl.ir.v1.NewtypeH\x00R\anewtype\x121\n" +
	"\tstructure\x18\x05 \x01(\v2\x11.tdl.ir.v1.StructH\x00R\tstructure\x123\n" +
	"\venumeration\x18\x06 \x01(\v2\x0f.tdl.ir.v1.EnumH\x00R\venumeration\x12(\n" +
	"\x05class\x18\a \x01(\v2\x10.tdl.ir.v1.ClassH\x00R\x05classB\x06\n" +
	"\x04node\"\xda\x02\n" +
	"\x05Class\x12(\n" +
	"\x06params\x18\x01 \x03(\v2\x10.tdl.ir.v1.ParamR\x06params\x12,\n" +
	"\bfun_deps\x18\x02 \x03(\v2\x11.tdl.ir.v1.FunDepR\afunDeps\x12>\n" +
	"\x10requires_classes\x18\x03 \x03(\v2\x13.tdl.ir.v1.ClassRefR\x0frequiresClasses\x125\n" +
	"\vconstraints\x18\x04 \x03(\v2\x13.tdl.ir.v1.ClassRefR\vconstraints\x12(\n" +
	"\x06fields\x18\x05 \x03(\v2\x10.tdl.ir.v1.FieldR\x06fields\x12!\n" +
	"\frequires_key\x18\x06 \x01(\bR\vrequiresKey\x125\n" +
	"\vassoc_types\x18\a \x03(\v2\x14.tdl.ir.v1.AssocTypeR\n" +
	"assocTypes\"]\n" +
	"\x06FunDep\x12\x12\n" +
	"\x04from\x18\x01 \x03(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x03(\tR\x02to\x12/\n" +
	"\bposition\x18\x03 \x01(\v2\x13.tdl.ir.v1.PositionR\bposition\"U\n" +
	"\tAssocType\x12#\n" +
	"\x04meta\x18\x01 \x01(\v2\x0f.tdl.ir.v1.MetaR\x04meta\x12#\n" +
	"\x04kind\x18\x02 \x01(\v2\x0f.tdl.ir.v1.KindR\x04kind\"0\n" +
	"\tPrimitive\x12#\n" +
	"\x04kind\x18\x01 \x01(\v2\x0f.tdl.ir.v1.KindR\x04kind\"X\n" +
	"\x05Alias\x12(\n" +
	"\x06params\x18\x01 \x03(\v2\x10.tdl.ir.v1.ParamR\x06params\x12%\n" +
	"\x06target\x18\x02 \x01(\v2\r.tdl.ir.v1.IDR\x06target\"\x8d\x01\n" +
	"\aNewtype\x12(\n" +
	"\x06params\x18\x01 \x03(\v2\x10.tdl.ir.v1.ParamR\x06params\x12!\n" +
	"\x04base\x18\x02 \x01(\v2\r.tdl.ir.v1.IDR\x04base\x125\n" +
	"\vconstraints\x18\x03 \x03(\v2\x13.tdl.ir.v1.ClassRefR\vconstraints\"\xef\x01\n" +
	"\x06Struct\x12)\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x15.tdl.ir.v1.StructKindR\x04kind\x12(\n" +
	"\x06params\x18\x02 \x03(\v2\x10.tdl.ir.v1.ParamR\x06params\x12(\n" +
	"\x06fields\x18\x03 \x03(\v2\x10.tdl.ir.v1.FieldR\x06fields\x12/\n" +
	"\bconforms\x18\x04 \x03(\v2\x13.tdl.ir.v1.ClassRefR\bconforms\x125\n" +
	"\vconstraints\x18\x05 \x03(\v2\x13.tdl.ir.v1.ClassRefR\vconstraints\"\xc8\x01\n" +
	"\x04Enum\x12(\n" +
	"\x06params\x18\x01 \x03(\v2\x10.tdl.ir.v1.ParamR\x06params\x12.\n" +
	"\bvariants\x18\x02 \x03(\v2\x12.tdl.ir.v1.VariantR\bvariants\x12/\n" +
	"\bconforms\x18\x03 \x03(\v2\x13.tdl.ir.v1.ClassRefR\bconforms\x125\n" +
	"\vconstraints\x18\x04 \x03(\v2\x13.tdl.ir.v1.ClassRefR\vconstraints\"X\n" +
	"\aVariant\x12#\n" +
	"\x04meta\x18\x01 \x01(\v2\x0f.tdl.ir.v1.MetaR\x04meta\x12(\n" +
	"\x06fields\x18\x02 \x03(\v2\x10.tdl.ir.v1.FieldR\x06fields\"\xab\x01\n" +
	"\x05Field\x12#\n" +
	"\x04meta\x18\x01 \x01(\v2\x0f.tdl.ir.v1.MetaR\x04meta\x12!\n" +
	"\x04type\x18\x02 \x01(\v2\r.tdl.ir.v1.IDR\x04type\x12\x10\n" +
	"\x03key\x18\x03 \x01(\bR\x03key\x12\x14\n" +
	"\x05owned\x18\x04 \x01(\bR\x05owned\x122\n" +
	"\rincluded_from\x18\x05 \x01(\v2\r.tdl.ir.v1.IDR\fincludedFrom\"q\n" +
	"\x05Param\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\x04kind\x18\x02 \x01(\v2\x0f.tdl.ir.v1.KindR\x04kind\x12/\n" +
	"\bposition\x18\x03 \x01(\v2\x13.tdl.ir.v1.PositionR\bposition\"}\n" +
	"\x04Kind\x12'\n" +
	"\x04atom\x18\x01 \x01(\x0e2\x13.tdl.ir.v1.KindAtomR\x04atom\x12%\n" +
	"\x05paren\x18\x02 \x01(\v2\x0f.tdl.ir.v1.KindR\x05paren\x12%\n" +
	"\x05arrow\x18\x03 \x01(\v2\x0f.tdl.ir.v1.KindR\x05arrow\"\xff\x01\n" +
	"\x04Type\x12!\n" +
	"\x04ctor\x18\x01 \x01(\v2\r.tdl.ir.v1.IDR\x04ctor\x12!\n" +
	"\x04args\x18\x02 \x03(\v2\r.tdl.ir.v1.IDR\x04args\x12.\n" +
	"\x05wrote\x18\x03 \x01(\x0e2\x18.tdl.ir.v1.SyntacticFormR\x05wrote\x12/\n" +
	"\bposition\x18\x04 \x01(\v2\x13.tdl.ir.v1.PositionR\bposition\x12)\n" +
	"\x05param\x18\x05 \x01(\v2\x13.tdl.ir.v1.ParamRefR\x05param\x12%\n" +
	"\x06extern\x18\x06 \x01(\v2\r.tdl.ir.v1.IDR\x06extern\"Y\n" +
	"\bParamRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12#\n" +
	"\x05owner\x18\x03 \x01(\v2\r.tdl.ir.v1.IDR\x05owner*o\n" +
	"\n" +
	"StructKind\x12\x1b\n" +
	"\x17STRUCT_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12STRUCT_KIND_ENTITY\x10\x01\x12\x15\n" +
	"\x11STRUCT_KIND_VALUE\x10\x02\x12\x15\n" +
	"\x11STRUCT_KIND_MIXIN\x10\x03*M\n" +
	"\bKindAtom\x12\x19\n" +
	"\x15KIND_ATOM_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eKIND_ATOM_TYPE\x10\x01\x12\x12\n" +
	"\x0eKIND_ATOM_UNIT\x10\x02*\xd4\x01\n" +
	"\rSyntacticForm\x12\x1e\n" +
	"\x1aSYNTACTIC_FORM_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SYNTACTIC_FORM_NAMED\x10\x01\x12\x1b\n" +
	"\x17SYNTACTIC_FORM_BRACKETS\x10\x02\x12\x19\n" +
	"\x15SYNTACTIC_FORM_BRACES\x10\x03\x12\x18\n" +
	"\x14SYNTACTIC_FORM_ARROW\x10\x04\x12\x1b\n" +
	"\x17SYNTACTIC_FORM_QUESTION\x10\x05\x12\x1a\n" +
	"\x16SYNTACTIC_FORM_OR_NULL\x10\x06B'Z%github.com/unstoppablemango/tdl/ir;irb\x06proto3"

var (
	file_tdl_ir_v1_ir_proto_rawDescOnce sync.Once
	file_tdl_ir_v1_ir_proto_rawDescData []byte
)

func file_tdl_ir_v1_ir_proto_rawDescGZIP() []byte {
	file_tdl_ir_v1_ir_proto_rawDescOnce.Do(func() {
		file_tdl_ir_v1_ir_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tdl_ir_v1_ir_proto_rawDesc), len(file_tdl_ir_v1_ir_proto_rawDesc)))
	})
	return file_tdl_ir_v1_ir_proto_rawDescData
}

var file_tdl_ir_v1_ir_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_tdl_ir_v1_ir_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_tdl_ir_v1_ir_proto_goTypes = []any{
	(StructKind)(0),      // 0: tdl.ir.v1.StructKind
	(KindAtom)(0),        // 1: tdl.ir.v1.KindAtom
	(SyntacticForm)(0),   // 2: tdl.ir.v1.SyntacticForm
	(*ID)(nil),           // 3: tdl.ir.v1.ID
	(*Position)(nil),     // 4: tdl.ir.v1.Position
	(*Deprecation)(nil),  // 5: tdl.ir.v1.Deprecation
	(*Meta)(nil),         // 6: tdl.ir.v1.Meta
	(*Model)(nil),        // 7: tdl.ir.v1.Model
	(*Instance)(nil),     // 8: tdl.ir.v1.Instance
	(*AssocBind)(nil),    // 9: tdl.ir.v1.AssocBind
	(*ClassRef)(nil),     // 10: tdl.ir.v1.ClassRef
	(*Satisfaction)(nil), // 11: tdl.ir.v1.Satisfaction
	(*Import)(nil),       // 12: tdl.ir.v1.Import
	(*Extern)(nil),       // 13: tdl.ir.v1.Extern
	(*Decl)(nil),         // 14: tdl.ir.v1.Decl
	(*Class)(nil),        // 15: tdl.ir.v1.Class
	(*FunDep)(nil),       // 16: tdl.ir.v1.FunDep
	(*AssocType)(nil),    // 17: tdl.ir.v1.AssocType
	(*Primitive)(nil),    // 18: tdl.ir.v1.Primitive
	(*Alias)(nil),        // 19: tdl.ir.v1.Alias
	(*Newtype)(nil),      // 20: tdl.ir.v1.Newtype
	(*Struct)(nil),       // 21: tdl.ir.v1.Struct
	(*Enum)(nil),         // 22: tdl.ir.v1.Enum
	(*Variant)(nil),      // 23: tdl.ir.v1.Variant
	(*Field)(nil),        // 24: tdl.ir.v1.Field
	(*Param)(nil),        // 25: tdl.ir.v1.Param
	(*Kind)(nil),         // 26: tdl.ir.v1.Kind
	(*Type)(nil),         // 27: tdl.ir.v1.Type
	(*ParamRef)(nil),     // 28: tdl.ir.v1.ParamRef
}
var file_tdl_ir_v1_ir_proto_depIdxs = []int32{
	4,  // 0: tdl.ir.v1.Deprecation.position:type_name -> tdl.ir.v1.Position
	4,  // 1: tdl.ir.v1.Meta.position:type_name -> tdl.ir.v1.Position
	5,  // 2: tdl.ir.v1.Meta.deprecated:type_name -> tdl.ir.v1.Deprecation
	14, // 3: tdl.ir.v1.Model.decls:type_name -> tdl.ir.v1.Decl
	27, // 4: tdl.ir.v1.Model.types:type_name -> tdl.ir.v1.Type
	12, // 5: tdl.ir.v1.Model.imports:type_name -> tdl.ir.v1.Import
	13, // 6: tdl.ir.v1.Model.externs:type_name -> tdl.ir.v1.Extern
	8,  // 7: tdl.ir.v1.Model.instances:type_name -> tdl.ir.v1.Instance
	11, // 8: tdl.ir.v1.Model.satisfies:type_name -> tdl.ir.v1.Satisfaction
	6,  // 9: tdl.ir.v1.Instance.meta:type_name -> tdl.ir.v1.Meta
	25, // 10: tdl.ir.v1.Instance.params:type_name -> tdl.ir.v1.Param
	10, // 11: tdl.ir.v1.Instance.class:type_name -> tdl.ir.v1.ClassRef
	10, // 12: tdl.ir.v1.Instance.requires:type_name -> tdl.ir.v1.ClassRef
	9,  // 13: tdl.ir.v1.Instance.binds:type_name -> tdl.ir.v1.AssocBind
	3,  // 14: tdl.ir.v1.AssocBind.type:type_name -> tdl.ir.v1.ID
	4,  // 15: tdl.ir.v1.AssocBind.position:type_name -> tdl.ir.v1.Position
	3,  // 16: tdl.ir.v1.ClassRef.class:type_name -> tdl.ir.v1.ID
	3,  // 17: tdl.ir.v1.ClassRef.extern:type_name -> tdl.ir.v1.ID
	3,  // 18: tdl.ir.v1.ClassRef.args:type_name -> tdl.ir.v1.ID
	4,  // 19: tdl.ir.v1.ClassRef.position:type_name -> tdl.ir.v1.Position
	3,  // 20: tdl.ir.v1.Satisfaction.class:type_name -> tdl.ir.v1.ID
	3,  // 21: tdl.ir.v1.Satisfaction.decls:type_name -> tdl.ir.v1.ID
	4,  // 22: tdl.ir.v1.Import.position:type_name -> tdl.ir.v1.Position
	4,  // 23: tdl.ir.v1.Extern.position:type_name -> tdl.ir.v1.Position
	6,  // 24: tdl.ir.v1.Decl.meta:type_name -> tdl.ir.v1.Meta
	18, // 25: tdl.ir.v1.Decl.primitive:type_name -> tdl.ir.v1.Primitive
	19, // 26: tdl.ir.v1.Decl.alias:type_name -> tdl.ir.v1.Alias
	20, // 27: tdl.ir.v1.Decl.newtype:type_name -> tdl.ir.v1.Newtype
	21, // 28: tdl.ir.v1.Decl.structure:type_name -> tdl.ir.v1.Struct
	22, // 29: tdl.ir.v1.Decl.enumeration:type_name -> tdl.ir.v1.Enum
	15, // 30: tdl.ir.v1.Decl.class:type_name -> tdl.ir.v1.Class
	25, // 31: tdl.ir.v1.Class.params:type_name -> tdl.ir.v1.Param
	16, // 32: tdl.ir.v1.Class.fun_deps:type_name -> tdl.ir.v1.FunDep
	10, // 33: tdl.ir.v1.Class.requires_classes:type_name -> tdl.ir.v1.ClassRef
	10, // 34: tdl.ir.v1.Class.constraints:type_name -> tdl.ir.v1.ClassRef
	24, // 35: tdl.ir.v1.Class.fields:type_name -> tdl.ir.v1.Field
	17, // 36: tdl.ir.v1.Class.assoc_types:type_name -> tdl.ir.v1.AssocType
	4,  // 37: tdl.ir.v1.FunDep.position:type_name -> tdl.ir.v1.Position
	6,  // 38: tdl.ir.v1.AssocType.meta:type_name -> tdl.ir.v1.Meta
	26, // 39: tdl.ir.v1.AssocType.kind:type_name -> tdl.ir.v1.Kind
	26, // 40: tdl.ir.v1.Primitive.kind:type_name -> tdl.ir.v1.Kind
	25, // 41: tdl.ir.v1.Alias.params:type_name -> tdl.ir.v1.Param
	3,  // 42: tdl.ir.v1.Alias.target:type_name -> tdl.ir.v1.ID
	25, // 43: tdl.ir.v1.Newtype.params:type_name -> tdl.ir.v1.Param
	3,  // 44: tdl.ir.v1.Newtype.base:type_name -> tdl.ir.v1.ID
	10, // 45: tdl.ir.v1.Newtype.constraints:type_name -> tdl.ir.v1.ClassRef
	0,  // 46: tdl.ir.v1.Struct.kind:type_name -> tdl.ir.v1.StructKind
	25, // 47: tdl.ir.v1.Struct.params:type_name -> tdl.ir.v1.Param
	24, // 48: tdl.ir.v1.Struct.fields:type_name -> tdl.ir.v1.Field
	10, // 49: tdl.ir.v1.Struct.conforms:type_name -> tdl.ir.v1.ClassRef
	10, // 50: tdl.ir.v1.Struct.constraints:type_name -> tdl.ir.v1.ClassRef
	25, // 51: tdl.ir.v1.Enum.params:type_name -> tdl.ir.v1.Param
	23, // 52: tdl.ir.v1.Enum.variants:type_name -> tdl.ir.v1.Variant
	10, // 53: tdl.ir.v1.Enum.conforms:type_name -> tdl.ir.v1.ClassRef
	10, // 54: tdl.ir.v1.Enum.constraints:type_name -> tdl.ir.v1.ClassRef
	6,  // 55: tdl.ir.v1.Variant.meta:type_name -> tdl.ir.v1.Meta
	24, // 56: tdl.ir.v1.Variant.fields:type_name -> tdl.ir.v1.Field
	6,  // 57: tdl.ir.v1.Field.meta:type_name -> tdl.ir.v1.Meta
	3,  // 58: tdl.ir.v1.Field.type:type_name -> tdl.ir.v1.ID
	3,  // 59: tdl.ir.v1.Field.included_from:type_name -> tdl.ir.v1.ID
	26, // 60: tdl.ir.v1.Param.kind:type_name -> tdl.ir.v1.Kind
	4,  // 61: tdl.ir.v1.Param.position:type_name -> tdl.ir.v1.Position
	1,  // 62: tdl.ir.v1.Kind.atom:type_name -> tdl.ir.v1.KindAtom
	26, // 63: tdl.ir.v1.Kind.paren:type_name -> tdl.ir.v1.Kind
	26, // 64: tdl.ir.v1.Kind.arrow:type_name -> tdl.ir.v1.Kind
	3,  // 65: tdl.ir.v1.Type.ctor:type_name -> tdl.ir.v1.ID
	3,  // 66: tdl.ir.v1.Type.args:type_name -> tdl.ir.v1.ID
	2,  // 67: tdl.ir.v1.Type.wrote:type_name -> tdl.ir.v1.SyntacticForm
	4,  // 68: tdl.ir.v1.Type.position:type_name -> tdl.ir.v1.Position
	28, // 69: tdl.ir.v1.Type.param:type_name -> tdl.ir.v1.ParamRef
	3,  // 70: tdl.ir.v1.Type.extern:type_name -> tdl.ir.v1.ID
	3,  // 71: tdl.ir.v1.ParamRef.owner:type_name -> tdl.ir.v1.ID
	72, // [72:72] is the sub-list for method output_type
	72, // [72:72] is the sub-list for method input_type
	72, // [72:72] is the sub-list for extension type_name
	72, // [72:72] is the sub-list for extension extendee
	0,  // [0:72] is the sub-list for field type_name
}

func init() { file_tdl_ir_v1_ir_proto_init() }
func file_tdl_ir_v1_ir_proto_init() {
	if File_tdl_ir_v1_ir_proto != nil {
		return
	}
	file_tdl_ir_v1_ir_proto_msgTypes[11].OneofWrappers = []any{
		(*Decl_Primitive)(nil),
		(*Decl_Alias)(nil),
		(*Decl_Newtype)(nil),
		(*Decl_Structure)(nil),
		(*Decl_Enumeration)(nil),
		(*Decl_Class)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tdl_ir_v1_ir_proto_rawDesc), len(file_tdl_ir_v1_ir_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tdl_ir_v1_ir_proto_goTypes,
		DependencyIndexes: file_tdl_ir_v1_ir_proto_depIdxs,
		EnumInfos:         file_tdl_ir_v1_ir_proto_enumTypes,
		MessageInfos:      file_tdl_ir_v1_ir_proto_msgTypes,
	}.Build()
	File_tdl_ir_v1_ir_proto = out.File
	file_tdl_ir_v1_ir_proto_goTypes = nil
	file_tdl_ir_v1_ir_proto_depIdxs = nil
}
