package protobuf_test

import (
	"context"
	"path/filepath"
	"strings"
	"testing"

	"github.com/bufbuild/protocompile"

	"github.com/unstoppablemango/tdl/backend/internal/irtest"
	"github.com/unstoppablemango/tdl/backend/protobuf"
	"github.com/unstoppablemango/tdl/ir"
	"github.com/unstoppablemango/tdl/plugin"
)

func generate(t *testing.T, b *irtest.Builder) *plugin.Response {
	t.Helper()
	resp, err := protobuf.Backend{}.Generate(context.Background(), &plugin.Request{
		Target: protobuf.Name,
		Model:  b.Model,
	})
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	return resp
}

// compile returns the response's one file, and asserts protobuf accepts it.
//
// Compiling rather than parsing is the assertion that matters: a reference
// to a message a skipped declaration left behind parses, and so does a map
// keyed by a message.
func compile(t *testing.T, resp *plugin.Response) string {
	t.Helper()
	if len(resp.GetFiles()) != 1 {
		t.Fatalf("files = %d, diagnostics = %+v", len(resp.GetFiles()), resp.GetDiagnostics())
	}
	f := resp.GetFiles()[0]
	c := protocompile.Compiler{Resolver: protocompile.WithStandardImports(&protocompile.SourceResolver{
		Accessor: protocompile.SourceAccessorFromMap(map[string]string{f.GetPath(): string(f.GetContent())}),
	})}
	if _, err := c.Compile(context.Background(), f.GetPath()); err != nil {
		t.Errorf("%s does not compile: %v\n%s", f.GetPath(), err, f.GetContent())
	}
	return string(f.GetContent())
}

// contains asserts on the output with runs of whitespace collapsed.
func contains(t *testing.T, src string, wants ...string) {
	t.Helper()
	flat := collapse(src)
	for _, want := range wants {
		if !strings.Contains(flat, collapse(want)) {
			t.Errorf("output missing %q:\n%s", want, src)
		}
	}
}

func absent(t *testing.T, src string, unwanted ...string) {
	t.Helper()
	for _, u := range unwanted {
		if strings.Contains(src, u) {
			t.Errorf("output has %q:\n%s", u, src)
		}
	}
}

func collapse(s string) string { return strings.Join(strings.Fields(s), " ") }

func structure(name string, kind ir.StructKind, fields ...*ir.Field) *ir.Decl {
	return &ir.Decl{
		Meta: &ir.Meta{Name: name},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{Kind: kind, Fields: fields}},
	}
}

func value(name string, fields ...*ir.Field) *ir.Decl {
	return structure(name, ir.StructKind_STRUCT_KIND_VALUE, fields...)
}

func enum(name string, variants ...*ir.Variant) *ir.Decl {
	return &ir.Decl{
		Meta: &ir.Meta{Name: name},
		Node: &ir.Decl_Enumeration{Enumeration: &ir.Enum{Variants: variants}},
	}
}

func variant(name string, fields ...*ir.Field) *ir.Variant {
	return &ir.Variant{Meta: &ir.Meta{Name: name}, Fields: fields}
}

func renamed(n string) []*ir.Directive {
	return []*ir.Directive{{
		Name: "name", Target: protobuf.Name, Args: []*ir.Literal{irtest.Text(n)},
		Position: &ir.Position{Filename: "shop.tdl", Line: 7},
	}}
}

func number(n string) *ir.Directive {
	return &ir.Directive{Name: "number", Target: protobuf.Name, Args: []*ir.Literal{{Kind: ir.LiteralKind_LITERAL_KIND_INT, Text: n}}}
}

func TestDescribe(t *testing.T) {
	d := protobuf.Backend{}.Describe()
	if d.Name != "protobuf" || !d.Reuse {
		t.Errorf("description = %+v", d)
	}
	declared := map[string]bool{}
	for _, spec := range d.Directives {
		declared[spec.GetName()] = true
	}
	for _, want := range []string{"package", "name", "number"} {
		if !declared[want] {
			t.Errorf("directive %q is acted on but not declared", want)
		}
	}
}

func TestMessages(t *testing.T) {
	b := irtest.New("shop.billing")
	b.Own(value("LineItem",
		irtest.Field("sku", b.Named("string")),
		irtest.Field("quantity", b.Named("int")),
	))
	b.Own(structure("Order", ir.StructKind_STRUCT_KIND_ENTITY,
		irtest.Field("id", b.Named("uuid")),
		irtest.Field("placedAt", b.Named("instant")),
		irtest.Field("items", b.Named("List", b.Named("LineItem"))),
		irtest.Field("tags", b.Named("Set", b.Named("string"))),
		irtest.Field("totals", b.Named("Map", b.Named("string"), b.Named("decimal"))),
		irtest.Field("note", b.Named("Option", b.Named("string"))),
		irtest.Field("took", b.Named("duration")),
		irtest.Field("shipOn", b.Named("Nullable", b.Named("date"))),
		irtest.Field("receipt", b.Named("bytes")),
		irtest.Field("paid", b.Named("bool")),
		irtest.Field("first", b.Named("Option", b.Named("LineItem"))),
	))

	resp := generate(t, b)
	if len(resp.GetDiagnostics()) != 0 {
		t.Errorf("diagnostics = %+v", resp.GetDiagnostics())
	}
	src := compile(t, resp)
	if path := resp.GetFiles()[0].GetPath(); path != "shop/billing/billing.proto" {
		t.Errorf("path = %q", path)
	}
	contains(t, src,
		"// Code generated by tdl. DO NOT EDIT.",
		`syntax = "proto3";`,
		"package shop.billing;",
		`import "google/protobuf/duration.proto";`,
		`import "google/protobuf/timestamp.proto";`,
		"message LineItem { string sku = 1; int64 quantity = 2; }",
		"string id = 1;",
		"google.protobuf.Timestamp placed_at = 2;",
		"repeated LineItem items = 3;",
		"repeated string tags = 4;",
		"map<string, string> totals = 5;",
		"optional string note = 6;",
		"google.protobuf.Duration took = 7;",
		"optional string ship_on = 8;",
		"bytes receipt = 9;",
		"bool paid = 10;",
		// A message field already has presence.
		"LineItem first = 11;",
	)
}

func TestImportsOnlyWhatIsUsed(t *testing.T) {
	b := irtest.New("shop")
	b.Own(value("Note", irtest.Field("body", b.Named("string"))))
	absent(t, compile(t, generate(t, b)), "import")
}

func TestFieldlessEnum(t *testing.T) {
	b := irtest.New("shop")
	b.Own(enum("Status", variant("Active"), variant("InProgress")))
	b.Own(value("Ticket", irtest.Field("status", b.Named("Option", b.Named("Status")))))

	contains(t, compile(t, generate(t, b)),
		"enum Status { STATUS_UNSPECIFIED = 0; STATUS_ACTIVE = 1; STATUS_IN_PROGRESS = 2; }",
		"optional Status status = 1;",
	)
}

// An enum whose variants carry fields is a oneof of nested messages, and a
// reference inside one to a declaration sharing a variant's name has to
// reach past the variant.
func TestFieldedEnumIsAOneof(t *testing.T) {
	b := irtest.New("shop")
	b.Own(value("Card", irtest.Field("pan", b.Named("string"))))
	b.Own(enum("Payment",
		variant("Card", irtest.Field("last4", b.Named("string")), irtest.Field("card", b.Named("Card"))),
		variant("Cash"),
	))
	b.Own(value("Checkout", irtest.Field("payment", b.Named("Option", b.Named("Payment")))))

	contains(t, compile(t, generate(t, b)),
		"message Payment {",
		"message Card { string last4 = 1; .shop.Card card = 2; }",
		"message Cash { }",
		"oneof variant { Card card = 1; Cash cash = 2; }",
		"Payment payment = 1;",
	)
}

func TestNewtypesAndAliasesExpand(t *testing.T) {
	b := irtest.New("shop")
	b.Own(&ir.Decl{Meta: &ir.Meta{Name: "Sku"}, Node: &ir.Decl_Newtype{Newtype: &ir.Newtype{Base: b.Named("string")}}})
	b.Own(&ir.Decl{Meta: &ir.Meta{Name: "Email"}, Node: &ir.Decl_Newtype{Newtype: &ir.Newtype{Base: b.Named("Sku")}}})
	b.Own(&ir.Decl{Meta: &ir.Meta{Name: "Tags"}, Node: &ir.Decl_Alias{Alias: &ir.Alias{Target: b.Named("List", b.Named("Sku"))}}})
	b.Own(value("Item",
		irtest.Field("sku", b.Named("Sku")),
		irtest.Field("tags", b.Named("Tags")),
		irtest.Field("byEmail", b.Named("Map", b.Named("Email"), b.Named("int"))),
	))

	src := compile(t, generate(t, b))
	contains(t, src, "string sku = 1;", "repeated string tags = 2;", "map<string, int64> by_email = 3;")
	absent(t, src, "Sku", "Email", "Tags")
}

func TestNumbers(t *testing.T) {
	b := irtest.New("shop")
	pinned := irtest.Field("b", b.Named("string"))
	pinned.Directives = []*ir.Directive{number("10")}
	b.Own(value("Pinned", irtest.Field("a", b.Named("string")), pinned, irtest.Field("c", b.Named("string"))))

	cash := variant("Cash")
	cash.Directives = []*ir.Directive{number("5")}
	b.Own(enum("Payment", variant("Card", irtest.Field("last4", b.Named("string"))), cash))

	closed := variant("Closed")
	closed.Directives = []*ir.Directive{number("9")}
	b.Own(enum("Status", variant("Open"), closed))

	contains(t, compile(t, generate(t, b)),
		"string a = 1; string b = 10; string c = 3;",
		"Card card = 1; Cash cash = 5;",
		"STATUS_OPEN = 1; STATUS_CLOSED = 9;",
	)
}

func TestNumbersProtobufRefuses(t *testing.T) {
	for name, n := range map[string]string{
		"a collision":         "1",
		"the reserved range":  "19500",
		"zero":                "0",
		"past the last field": "536870912",
	} {
		t.Run(name, func(t *testing.T) {
			b := irtest.New("shop")
			pinned := irtest.Field("b", b.Named("string"))
			pinned.Directives = []*ir.Directive{number(n)}
			b.Own(value("Broken", irtest.Field("a", b.Named("string")), pinned))
			b.Own(value("Fine", irtest.Field("a", b.Named("string"))))

			resp := generate(t, b)
			if len(resp.GetDiagnostics()) != 1 {
				t.Errorf("diagnostics = %+v", resp.GetDiagnostics())
			}
			src := compile(t, resp)
			absent(t, src, "message Broken")
			contains(t, src, "message Fine")
		})
	}
}

// A shape protobuf cannot express is a warning, the declaration reaching it
// is skipped, and so is everything naming that declaration.
func TestUnsupportedShapesAreSkipped(t *testing.T) {
	for _, tt := range []struct {
		name string
		typ  func(b *irtest.Builder) *ir.ID
	}{
		{"a list of lists", func(b *irtest.Builder) *ir.ID { return b.Named("List", b.Named("List", b.Named("int"))) }},
		{"a list of optionals", func(b *irtest.Builder) *ir.ID { return b.Named("List", b.Named("Option", b.Named("int"))) }},
		{"an optional list", func(b *irtest.Builder) *ir.ID { return b.Named("Option", b.Named("List", b.Named("int"))) }},
		{"an optional optional", func(b *irtest.Builder) *ir.ID {
			return b.Named("Nullable", b.Named("Option", b.Named("int")))
		}},
		{"a map keyed by bytes", func(b *irtest.Builder) *ir.ID { return b.Named("Map", b.Named("bytes"), b.Named("int")) }},
		{"a map keyed by a message", func(b *irtest.Builder) *ir.ID { return b.Named("Map", b.Named("Fine"), b.Named("int")) }},
		{"a map of lists", func(b *irtest.Builder) *ir.ID {
			return b.Named("Map", b.Named("string"), b.Named("List", b.Named("int")))
		}},
	} {
		t.Run(tt.name, func(t *testing.T) {
			b := irtest.New("shop")
			b.Own(value("Fine", irtest.Field("a", b.Named("string"))))
			b.Own(value("Broken", irtest.Field("x", tt.typ(b))))
			b.Own(value("Holder", irtest.Field("broken", b.Named("Broken"))))

			resp := generate(t, b)
			if len(resp.GetDiagnostics()) != 2 {
				t.Errorf("want a warning for Broken and one for Holder: %+v", resp.GetDiagnostics())
			}
			for _, d := range resp.GetDiagnostics() {
				if d.GetSeverity() != plugin.Severity_SEVERITY_WARNING {
					t.Errorf("severity = %v", d.GetSeverity())
				}
			}
			src := compile(t, resp)
			absent(t, src, "message Broken", "message Holder")
			contains(t, src, "message Fine")
		})
	}
}

func TestClassesAndUnitsWarn(t *testing.T) {
	b := irtest.New("shop")
	b.Own(&ir.Decl{Meta: &ir.Meta{Name: "Auditable", Position: &ir.Position{Filename: "shop.tdl", Line: 4}}, Node: &ir.Decl_Class{Class: &ir.Class{}}})
	b.Own(value("Note", irtest.Field("body", b.Named("string"))))

	resp := generate(t, b)
	if len(resp.GetDiagnostics()) != 1 || resp.GetDiagnostics()[0].GetPosition().GetLine() != 4 {
		t.Errorf("diagnostics = %+v", resp.GetDiagnostics())
	}
	contains(t, compile(t, resp), "message Note")
}

// Constraints are not enforced, and the backend says so rather than letting
// the model believe they are. The declaration is still emitted.
func TestConstraintsWarn(t *testing.T) {
	b := irtest.New("shop")
	b.Own(&ir.Decl{Meta: &ir.Meta{Name: "Email"}, Node: &ir.Decl_Newtype{Newtype: &ir.Newtype{
		Base:             b.Named("string"),
		ValueConstraints: []*ir.Constraint{{Name: "matches"}},
	}}})
	qty := irtest.Field("quantity", b.Named("int"))
	qty.Constraints = []*ir.Constraint{{Name: "min"}}
	b.Own(value("Line", qty, irtest.Field("email", b.Named("Email"))))

	resp := generate(t, b)
	if len(resp.GetDiagnostics()) != 2 {
		t.Errorf("diagnostics = %+v", resp.GetDiagnostics())
	}
	contains(t, compile(t, resp), "int64 quantity = 1;", "string email = 2;")
}

func TestNames(t *testing.T) {
	b := irtest.New("shop")
	user := value("User", irtest.Field("email", b.Named("string")))
	user.Directives = []*ir.Directive{{Name: "name", Target: protobuf.Name, Args: []*ir.Literal{irtest.Text("Account")}}}
	user.GetStructure().GetFields()[0].Directives = []*ir.Directive{
		{Name: "name", Target: protobuf.Name, Args: []*ir.Literal{irtest.Text("email_address")}},
		{Name: "name", Target: "go", Args: []*ir.Literal{irtest.Text("Nope")}},
	}
	b.Own(user)
	b.Own(value("Clash", irtest.Field("userId", b.Named("string")), irtest.Field("user_id", b.Named("string"))))

	resp := generate(t, b)
	if len(resp.GetDiagnostics()) != 1 {
		t.Errorf("want one warning, for the clash: %+v", resp.GetDiagnostics())
	}
	src := compile(t, resp)
	contains(t, src, "message Account { string email_address = 1; }")
	absent(t, src, "Nope", "message Clash")
}

// A `name` directive is a name the model wrote rather than one the backend
// styled, so it is the one place a name protobuf refuses can reach the file.
// Each is a skipped declaration and not output the compiler chokes on.
func TestInvalidNames(t *testing.T) {
	b := irtest.New("shop")

	decl := value("Bad", irtest.Field("body", b.Named("string")))
	decl.Directives = renamed("a-b")
	b.Own(decl)

	field := irtest.Field("second", b.Named("string"))
	field.Directives = renamed("2nd")
	b.Own(value("BadField", field))

	red := variant("Red")
	red.Directives = renamed("RED COLOR")
	b.Own(enum("BadValue", red, variant("Blue")))

	member := variant("Cash", irtest.Field("amount", b.Named("int")))
	member.Directives = renamed("cash.paid")
	b.Own(enum("BadVariant", member, variant("Card")))

	b.Own(value("Good", irtest.Field("body", b.Named("string"))))

	resp := generate(t, b)
	if len(resp.GetDiagnostics()) != 4 {
		t.Errorf("want a warning per invalid name: %+v", resp.GetDiagnostics())
	}
	for _, d := range resp.GetDiagnostics() {
		if d.GetPosition().GetLine() != 7 {
			t.Errorf("a name is reported where it was written: %+v", d)
		}
	}
	src := compile(t, resp)
	contains(t, src, "message Good")
	absent(t, src, "a-b", "2nd", "RED COLOR", "cash.paid")
}

func TestPackageDirective(t *testing.T) {
	block := func(pkg string) []*ir.TargetBlock {
		return []*ir.TargetBlock{{
			Meta: &ir.Meta{Name: protobuf.Name},
			Directives: []*ir.Directive{{
				Name: "package", Target: protobuf.Name, Args: []*ir.Literal{irtest.Text(pkg)},
				Position: &ir.Position{Filename: "shop.tdl", Line: 2},
			}},
		}}
	}

	b := irtest.New("shop")
	b.Own(value("Note", irtest.Field("body", b.Named("string"))))
	b.Model.Targets = block("acme.billing.v1")
	resp := generate(t, b)
	contains(t, compile(t, resp), "package acme.billing.v1;")
	if path := resp.GetFiles()[0].GetPath(); path != "acme/billing/v1/v1.proto" {
		t.Errorf("path = %q", path)
	}

	b.Model.Targets = block("acme-billing")
	resp = generate(t, b)
	if len(resp.GetFiles()) != 0 || len(resp.GetDiagnostics()) != 1 ||
		resp.GetDiagnostics()[0].GetSeverity() != plugin.Severity_SEVERITY_ERROR {
		t.Errorf("a package protobuf refuses should be an error and nothing else: %+v", resp)
	}
}

func TestDocsAndDeprecation(t *testing.T) {
	b := irtest.New("shop")
	old := irtest.Field("fax", b.Named("string"))
	old.Meta.Deprecated = &ir.Deprecation{Reason: "nobody has one"}
	b.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Contact", Doc: []string{"How to reach someone."}, Deprecated: &ir.Deprecation{}},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{Fields: []*ir.Field{old}}},
	})

	contains(t, compile(t, generate(t, b)),
		"// How to reach someone.",
		"message Contact { option deprecated = true;",
		"// Deprecated: nobody has one",
		"string fax = 1 [deprecated = true];",
	)
}

// Every case in the conformance corpus generates something protobuf
// accepts, whatever this backend warned about along the way.
func TestConformance(t *testing.T) {
	for _, c := range []string{
		"aliases", "collections", "comments", "constraints", "deprecated", "entity",
		"enum_variants", "mixin_include", "newtype", "targets", "targets_variants", "value",
	} {
		t.Run(c, func(t *testing.T) {
			model := irtest.Conformance(t, filepath.Join("..", "..", "testdata", "conformance", c))
			resp, err := protobuf.Backend{}.Generate(context.Background(), &plugin.Request{Target: protobuf.Name, Model: model})
			if err != nil {
				t.Fatal(err)
			}
			for _, d := range resp.GetDiagnostics() {
				if d.GetSeverity() == plugin.Severity_SEVERITY_ERROR {
					t.Errorf("error: %s", d.GetMessage())
				}
			}
			if len(resp.GetFiles()) > 0 {
				compile(t, resp)
			}
		})
	}
}
