// Code generated by tdl. DO NOT EDIT.

package unist

import "errors"

// The fields every node carries besides its `type`.
type Node struct {
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

// Validate reports every constraint Node breaks, joined, or nil.
func (n Node) Validate() error {
	return errors.Join(n.validate("Node", nil)...)
}

func (n Node) validate(path string, errs []error) []error {
	if n.Position != nil {
		errs = (*n.Position).validate(path+".position", errs)
	}
	return errs
}
