// Code generated by tdl. DO NOT EDIT.

package mdast

import (
	"errors"
	"fmt"
)

// Every mdast node.
type Nodes interface{ isNodes() }

// The whole document.
type Root struct {
	// Any content. https://github.com/syntax-tree/mdast#rootcontent
	Children []Nodes
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (Root) isNodes() {}

// Validate reports every constraint Nodes.root breaks, joined, or nil.
func (r Root) Validate() error {
	return errors.Join(r.validate("Nodes.root", nil)...)
}

func (r Root) validate(path string, errs []error) []error {
	for idx, elem := range r.Children {
		if inner, ok := elem.(interface{ validate(string, []error) []error }); ok {
			errs = inner.validate(fmt.Sprintf("%s.children[%d]", path, idx), errs)
		}
	}
	if r.Position != nil {
		errs = (*r.Position).validate(path+".position", errs)
	}
	return errs
}

// A section quoted from somewhere else.
type Blockquote struct {
	// Flow content: block content and definitions.
	Children []Nodes
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (Blockquote) isNodes() {}

// Validate reports every constraint Nodes.blockquote breaks, joined, or nil.
func (b Blockquote) Validate() error {
	return errors.Join(b.validate("Nodes.blockquote", nil)...)
}

func (b Blockquote) validate(path string, errs []error) []error {
	for idx, elem := range b.Children {
		if inner, ok := elem.(interface{ validate(string, []error) []error }); ok {
			errs = inner.validate(fmt.Sprintf("%s.children[%d]", path, idx), errs)
		}
	}
	if b.Position != nil {
		errs = (*b.Position).validate(path+".position", errs)
	}
	return errs
}

// A line break, as in poems or addresses.
type Break struct {
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (Break) isNodes() {}

// Validate reports every constraint Nodes.break breaks, joined, or nil.
func (b Break) Validate() error {
	return errors.Join(b.validate("Nodes.break", nil)...)
}

func (b Break) validate(path string, errs []error) []error {
	if b.Position != nil {
		errs = (*b.Position).validate(path+".position", errs)
	}
	return errs
}

// A block of preformatted text, such as code.
type Code struct {
	// The language of the code, from the info string.
	Lang **string
	// The rest of the info string, after lang.
	Meta **string
	// The text of the node.
	Value string
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (Code) isNodes() {}

// Validate reports every constraint Nodes.code breaks, joined, or nil.
func (c Code) Validate() error {
	return errors.Join(c.validate("Nodes.code", nil)...)
}

func (c Code) validate(path string, errs []error) []error {
	if c.Position != nil {
		errs = (*c.Position).validate(path+".position", errs)
	}
	return errs
}

// A resource, referenced by a linkReference or imageReference.
type Definition struct {
	// The normalized identifier the association matches on.
	Identifier string
	// The identifier as written in the source.
	Label **string
	// A URL to the referenced resource.
	Url string
	// Advisory information for the resource, such as a tooltip.
	Title **string
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (Definition) isNodes() {}

// Validate reports every constraint Nodes.definition breaks, joined, or nil.
func (d Definition) Validate() error {
	return errors.Join(d.validate("Nodes.definition", nil)...)
}

func (d Definition) validate(path string, errs []error) []error {
	if d.Position != nil {
		errs = (*d.Position).validate(path+".position", errs)
	}
	return errs
}

// Content that is no longer accurate or relevant.
type Delete struct {
	// Phrasing content: text and its markup.
	Children []Nodes
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (Delete) isNodes() {}

// Validate reports every constraint Nodes.delete breaks, joined, or nil.
func (d Delete) Validate() error {
	return errors.Join(d.validate("Nodes.delete", nil)...)
}

func (d Delete) validate(path string, errs []error) []error {
	for idx, elem := range d.Children {
		if inner, ok := elem.(interface{ validate(string, []error) []error }); ok {
			errs = inner.validate(fmt.Sprintf("%s.children[%d]", path, idx), errs)
		}
	}
	if d.Position != nil {
		errs = (*d.Position).validate(path+".position", errs)
	}
	return errs
}

// Stress emphasis of its contents.
type Emphasis struct {
	// Phrasing content: text and its markup.
	Children []Nodes
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (Emphasis) isNodes() {}

// Validate reports every constraint Nodes.emphasis breaks, joined, or nil.
func (e Emphasis) Validate() error {
	return errors.Join(e.validate("Nodes.emphasis", nil)...)
}

func (e Emphasis) validate(path string, errs []error) []error {
	for idx, elem := range e.Children {
		if inner, ok := elem.(interface{ validate(string, []error) []error }); ok {
			errs = inner.validate(fmt.Sprintf("%s.children[%d]", path, idx), errs)
		}
	}
	if e.Position != nil {
		errs = (*e.Position).validate(path+".position", errs)
	}
	return errs
}

// Content of a footnote, referenced by a footnoteReference.
type FootnoteDefinition struct {
	// The normalized identifier the association matches on.
	Identifier string
	// The identifier as written in the source.
	Label **string
	// Flow content: block content and definitions.
	Children []Nodes
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (FootnoteDefinition) isNodes() {}

// Validate reports every constraint Nodes.footnoteDefinition breaks, joined, or nil.
func (f FootnoteDefinition) Validate() error {
	return errors.Join(f.validate("Nodes.footnoteDefinition", nil)...)
}

func (f FootnoteDefinition) validate(path string, errs []error) []error {
	for idx, elem := range f.Children {
		if inner, ok := elem.(interface{ validate(string, []error) []error }); ok {
			errs = inner.validate(fmt.Sprintf("%s.children[%d]", path, idx), errs)
		}
	}
	if f.Position != nil {
		errs = (*f.Position).validate(path+".position", errs)
	}
	return errs
}

// A marker associated with a footnoteDefinition.
type FootnoteReference struct {
	// The normalized identifier the association matches on.
	Identifier string
	// The identifier as written in the source.
	Label **string
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (FootnoteReference) isNodes() {}

// Validate reports every constraint Nodes.footnoteReference breaks, joined, or nil.
func (f FootnoteReference) Validate() error {
	return errors.Join(f.validate("Nodes.footnoteReference", nil)...)
}

func (f FootnoteReference) validate(path string, errs []error) []error {
	if f.Position != nil {
		errs = (*f.Position).validate(path+".position", errs)
	}
	return errs
}

// The heading of a section.
type Heading struct {
	// The rank of the heading, 1 the highest.
	Depth int64
	// Phrasing content: text and its markup.
	Children []Nodes
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (Heading) isNodes() {}

// Validate reports every constraint Nodes.heading breaks, joined, or nil.
func (h Heading) Validate() error {
	return errors.Join(h.validate("Nodes.heading", nil)...)
}

func (h Heading) validate(path string, errs []error) []error {
	if h.Depth < 1 {
		errs = append(errs, fmt.Errorf("%s.depth: min(1): got %d", path, h.Depth))
	}
	if h.Depth > 6 {
		errs = append(errs, fmt.Errorf("%s.depth: max(6): got %d", path, h.Depth))
	}
	for idx, elem := range h.Children {
		if inner, ok := elem.(interface{ validate(string, []error) []error }); ok {
			errs = inner.validate(fmt.Sprintf("%s.children[%d]", path, idx), errs)
		}
	}
	if h.Position != nil {
		errs = (*h.Position).validate(path+".position", errs)
	}
	return errs
}

// A fragment of raw HTML.
type Html struct {
	// The text of the node.
	Value string
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (Html) isNodes() {}

// Validate reports every constraint Nodes.html breaks, joined, or nil.
func (h Html) Validate() error {
	return errors.Join(h.validate("Nodes.html", nil)...)
}

func (h Html) validate(path string, errs []error) []error {
	if h.Position != nil {
		errs = (*h.Position).validate(path+".position", errs)
	}
	return errs
}

// An image.
type Image struct {
	// A URL to the referenced resource.
	Url string
	// Advisory information for the resource, such as a tooltip.
	Title **string
	// Equivalent content for environments that cannot show the node.
	Alt **string
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (Image) isNodes() {}

// Validate reports every constraint Nodes.image breaks, joined, or nil.
func (i Image) Validate() error {
	return errors.Join(i.validate("Nodes.image", nil)...)
}

func (i Image) validate(path string, errs []error) []error {
	if i.Position != nil {
		errs = (*i.Position).validate(path+".position", errs)
	}
	return errs
}

// An image through association, or its original source when there is no association.
type ImageReference struct {
	// The normalized identifier the association matches on.
	Identifier string
	// The identifier as written in the source.
	Label **string
	// The explicitness of the reference.
	ReferenceType ReferenceType
	// Equivalent content for environments that cannot show the node.
	Alt **string
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (ImageReference) isNodes() {}

// Validate reports every constraint Nodes.imageReference breaks, joined, or nil.
func (i ImageReference) Validate() error {
	return errors.Join(i.validate("Nodes.imageReference", nil)...)
}

func (i ImageReference) validate(path string, errs []error) []error {
	if i.Position != nil {
		errs = (*i.Position).validate(path+".position", errs)
	}
	return errs
}

// A fragment of computer code, such as a file name or a command.
type InlineCode struct {
	// The text of the node.
	Value string
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (InlineCode) isNodes() {}

// Validate reports every constraint Nodes.inlineCode breaks, joined, or nil.
func (i InlineCode) Validate() error {
	return errors.Join(i.validate("Nodes.inlineCode", nil)...)
}

func (i InlineCode) validate(path string, errs []error) []error {
	if i.Position != nil {
		errs = (*i.Position).validate(path+".position", errs)
	}
	return errs
}

// A hyperlink.
type Link struct {
	// A URL to the referenced resource.
	Url string
	// Advisory information for the resource, such as a tooltip.
	Title **string
	// Phrasing content: text and its markup.
	Children []Nodes
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (Link) isNodes() {}

// Validate reports every constraint Nodes.link breaks, joined, or nil.
func (l Link) Validate() error {
	return errors.Join(l.validate("Nodes.link", nil)...)
}

func (l Link) validate(path string, errs []error) []error {
	for idx, elem := range l.Children {
		if inner, ok := elem.(interface{ validate(string, []error) []error }); ok {
			errs = inner.validate(fmt.Sprintf("%s.children[%d]", path, idx), errs)
		}
	}
	if l.Position != nil {
		errs = (*l.Position).validate(path+".position", errs)
	}
	return errs
}

// A hyperlink through association, or its original source when there is no association.
type LinkReference struct {
	// The normalized identifier the association matches on.
	Identifier string
	// The identifier as written in the source.
	Label **string
	// The explicitness of the reference.
	ReferenceType ReferenceType
	// Phrasing content: text and its markup.
	Children []Nodes
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (LinkReference) isNodes() {}

// Validate reports every constraint Nodes.linkReference breaks, joined, or nil.
func (l LinkReference) Validate() error {
	return errors.Join(l.validate("Nodes.linkReference", nil)...)
}

func (l LinkReference) validate(path string, errs []error) []error {
	for idx, elem := range l.Children {
		if inner, ok := elem.(interface{ validate(string, []error) []error }); ok {
			errs = inner.validate(fmt.Sprintf("%s.children[%d]", path, idx), errs)
		}
	}
	if l.Position != nil {
		errs = (*l.Position).validate(path+".position", errs)
	}
	return errs
}

// A list of items.
type List struct {
	// Whether the items are in order rather than unordered.
	Ordered **bool
	// The number of the first item of an ordered list.
	Start **int64
	// Whether items are separated by blank lines.
	Spread **bool
	// List items.
	Children []Nodes
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (List) isNodes() {}

// Validate reports every constraint Nodes.list breaks, joined, or nil.
func (l List) Validate() error {
	return errors.Join(l.validate("Nodes.list", nil)...)
}

func (l List) validate(path string, errs []error) []error {
	for idx, elem := range l.Children {
		if inner, ok := elem.(interface{ validate(string, []error) []error }); ok {
			errs = inner.validate(fmt.Sprintf("%s.children[%d]", path, idx), errs)
		}
	}
	if l.Position != nil {
		errs = (*l.Position).validate(path+".position", errs)
	}
	return errs
}

// An item in a list.
type ListItem struct {
	// Whether the item is done, when it is a task; absent otherwise.
	Checked **bool
	// Whether items are separated by blank lines.
	Spread **bool
	// Flow content: block content and definitions.
	Children []Nodes
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (ListItem) isNodes() {}

// Validate reports every constraint Nodes.listItem breaks, joined, or nil.
func (l ListItem) Validate() error {
	return errors.Join(l.validate("Nodes.listItem", nil)...)
}

func (l ListItem) validate(path string, errs []error) []error {
	for idx, elem := range l.Children {
		if inner, ok := elem.(interface{ validate(string, []error) []error }); ok {
			errs = inner.validate(fmt.Sprintf("%s.children[%d]", path, idx), errs)
		}
	}
	if l.Position != nil {
		errs = (*l.Position).validate(path+".position", errs)
	}
	return errs
}

// A unit of discourse dealing with a particular point or idea.
type Paragraph struct {
	// Phrasing content: text and its markup.
	Children []Nodes
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (Paragraph) isNodes() {}

// Validate reports every constraint Nodes.paragraph breaks, joined, or nil.
func (p Paragraph) Validate() error {
	return errors.Join(p.validate("Nodes.paragraph", nil)...)
}

func (p Paragraph) validate(path string, errs []error) []error {
	for idx, elem := range p.Children {
		if inner, ok := elem.(interface{ validate(string, []error) []error }); ok {
			errs = inner.validate(fmt.Sprintf("%s.children[%d]", path, idx), errs)
		}
	}
	if p.Position != nil {
		errs = (*p.Position).validate(path+".position", errs)
	}
	return errs
}

// Strong importance, seriousness, or urgency for its contents.
type Strong struct {
	// Phrasing content: text and its markup.
	Children []Nodes
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (Strong) isNodes() {}

// Validate reports every constraint Nodes.strong breaks, joined, or nil.
func (s Strong) Validate() error {
	return errors.Join(s.validate("Nodes.strong", nil)...)
}

func (s Strong) validate(path string, errs []error) []error {
	for idx, elem := range s.Children {
		if inner, ok := elem.(interface{ validate(string, []error) []error }); ok {
			errs = inner.validate(fmt.Sprintf("%s.children[%d]", path, idx), errs)
		}
	}
	if s.Position != nil {
		errs = (*s.Position).validate(path+".position", errs)
	}
	return errs
}

// Two-dimensional data.
type Table struct {
	// How each column aligns; null for a column with no alignment.
	Align **[]*AlignType
	// Table rows.
	Children []Nodes
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (Table) isNodes() {}

// Validate reports every constraint Nodes.table breaks, joined, or nil.
func (t Table) Validate() error {
	return errors.Join(t.validate("Nodes.table", nil)...)
}

func (t Table) validate(path string, errs []error) []error {
	for idx, elem := range t.Children {
		if inner, ok := elem.(interface{ validate(string, []error) []error }); ok {
			errs = inner.validate(fmt.Sprintf("%s.children[%d]", path, idx), errs)
		}
	}
	if t.Position != nil {
		errs = (*t.Position).validate(path+".position", errs)
	}
	return errs
}

// A header cell in a table, if its row is the first, or a data cell otherwise.
type TableCell struct {
	// Phrasing content: text and its markup.
	Children []Nodes
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (TableCell) isNodes() {}

// Validate reports every constraint Nodes.tableCell breaks, joined, or nil.
func (t TableCell) Validate() error {
	return errors.Join(t.validate("Nodes.tableCell", nil)...)
}

func (t TableCell) validate(path string, errs []error) []error {
	for idx, elem := range t.Children {
		if inner, ok := elem.(interface{ validate(string, []error) []error }); ok {
			errs = inner.validate(fmt.Sprintf("%s.children[%d]", path, idx), errs)
		}
	}
	if t.Position != nil {
		errs = (*t.Position).validate(path+".position", errs)
	}
	return errs
}

// A row of cells in a table.
type TableRow struct {
	// Table cells.
	Children []Nodes
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (TableRow) isNodes() {}

// Validate reports every constraint Nodes.tableRow breaks, joined, or nil.
func (t TableRow) Validate() error {
	return errors.Join(t.validate("Nodes.tableRow", nil)...)
}

func (t TableRow) validate(path string, errs []error) []error {
	for idx, elem := range t.Children {
		if inner, ok := elem.(interface{ validate(string, []error) []error }); ok {
			errs = inner.validate(fmt.Sprintf("%s.children[%d]", path, idx), errs)
		}
	}
	if t.Position != nil {
		errs = (*t.Position).validate(path+".position", errs)
	}
	return errs
}

// Everything that is just text.
type Text struct {
	// The text of the node.
	Value string
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (Text) isNodes() {}

// Validate reports every constraint Nodes.text breaks, joined, or nil.
func (t Text) Validate() error {
	return errors.Join(t.validate("Nodes.text", nil)...)
}

func (t Text) validate(path string, errs []error) []error {
	if t.Position != nil {
		errs = (*t.Position).validate(path+".position", errs)
	}
	return errs
}

// A thematic break, such as a scene change in a story.
type ThematicBreak struct {
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (ThematicBreak) isNodes() {}

// Validate reports every constraint Nodes.thematicBreak breaks, joined, or nil.
func (t ThematicBreak) Validate() error {
	return errors.Join(t.validate("Nodes.thematicBreak", nil)...)
}

func (t ThematicBreak) validate(path string, errs []error) []error {
	if t.Position != nil {
		errs = (*t.Position).validate(path+".position", errs)
	}
	return errs
}

// A collection of metadata for the document in YAML.
type Yaml struct {
	// The text of the node.
	Value string
	// Information from the ecosystem.
	Data *Data
	// Where the node came from. Absent when it was generated.
	Position *Position
}

func (Yaml) isNodes() {}

// Validate reports every constraint Nodes.yaml breaks, joined, or nil.
func (y Yaml) Validate() error {
	return errors.Join(y.validate("Nodes.yaml", nil)...)
}

func (y Yaml) validate(path string, errs []error) []error {
	if y.Position != nil {
		errs = (*y.Position).validate(path+".position", errs)
	}
	return errs
}
