// Code generated by tdl. DO NOT EDIT.

package mdast

import (
	"errors"
	"fmt"
)

// One place in a source file.
type Point struct {
	// The 1-indexed line.
	Line int64
	// The 1-indexed column.
	Column int64
	// The 0-indexed offset into the file.
	Offset *int64
}

// Validate reports every constraint Point breaks, joined, or nil.
func (p Point) Validate() error {
	return errors.Join(p.validate("Point", nil)...)
}

func (p Point) validate(path string, errs []error) []error {
	if p.Line < 1 {
		errs = append(errs, fmt.Errorf("%s.line: min(1): got %d", path, p.Line))
	}
	if p.Column < 1 {
		errs = append(errs, fmt.Errorf("%s.column: min(1): got %d", path, p.Column))
	}
	if p.Offset != nil {
		if (*p.Offset) < 0 {
			errs = append(errs, fmt.Errorf("%s.offset: min(0): got %d", path, (*p.Offset)))
		}
	}
	return errs
}
