// Code generated by tdl. DO NOT EDIT.

package mdast

// How explicit a reference is.
type ReferenceType string

const (
	ReferenceTypeShortcut  ReferenceType = "shortcut"
	ReferenceTypeCollapsed ReferenceType = "collapsed"
	ReferenceTypeFull      ReferenceType = "full"
)
