// Package thrift generates a Thrift IDL file from a resolved model.
//
// docs/design/schema-backends.md has the mapping and the reasons for it.
// Three things are worth knowing before reading the output. An enum whose
// variants carry fields is a union of one struct per variant. A newtype is
// a typedef, which is the one schema language here with a named alias that
// costs nothing on the wire. And declarations are written in dependency
// order, since a Thrift compiler reads a file top to bottom.
package thrift

import (
	"context"
	"fmt"
	"math"
	"regexp"
	"strings"

	"github.com/unstoppablemango/tdl/backend/internal/emit"
	"github.com/unstoppablemango/tdl/ir"
	"github.com/unstoppablemango/tdl/plugin"
)

// Name is what this backend is called, in a target block and as
// tdl-gen-thrift on PATH.
const Name = "thrift"

// Backend implements [plugin.Backend].
type Backend struct{}

func (Backend) Describe() plugin.Description {
	str := []ir.LiteralKind{ir.LiteralKind_LITERAL_KIND_STRING}
	return plugin.Description{
		Name:    Name,
		Version: "0.1.0",
		// Each request is answered from the request alone.
		Reuse: true,
		Directives: []*plugin.DirectiveSpec{
			// The dotted namespace, written for every language as
			// `namespace *`. The model's package is the default.
			{Name: "package", MinArgs: 1, MaxArgs: 1, ArgKinds: str},
			// The Thrift name for a declaration, a field, an enum value, or a
			// variant's struct.
			{Name: "name", MinArgs: 1, MaxArgs: 1, ArgKinds: str},
			// The field id of a field or a variant, or an enum value.
			{Name: "number", MinArgs: 1, MaxArgs: 1, ArgKinds: []ir.LiteralKind{ir.LiteralKind_LITERAL_KIND_INT}},
		},
	}
}

var (
	// fieldNumbers is a Thrift field id, which is an i16.
	fieldNumbers = emit.NumberRule{Max: math.MaxInt16}
	enumNumbers  = emit.NumberRule{Max: math.MaxInt32}
)

// scalars maps a prelude primitive to the Thrift type standing for it.
// Thrift has no decimal, UUID, or time type, so each of those is the string
// a consumer parses.
var scalars = map[string]string{
	"string":   "string",
	"int":      "i64",
	"bool":     "bool",
	"bytes":    "binary",
	"decimal":  "string",
	"uuid":     "string",
	"instant":  "string",
	"date":     "string",
	"duration": "string",
}

// keywords are the words the Thrift IDL reserves.
var keywords = map[string]bool{}

func init() {
	for _, k := range strings.Fields(`
		binary bool byte const cpp_include cpp_type double enum exception extends
		false i16 i32 i64 i8 include list map namespace oneway optional required
		senum service set slist string struct throws true typedef union void`) {
		keywords[k] = true
	}
}

var ident = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

type generator struct {
	*emit.Session
}

// Generate returns one .thrift file holding every declaration the model
// owns.
func (Backend) Generate(_ context.Context, req *plugin.Request) (*plugin.Response, error) {
	g := &generator{Session: emit.NewSession(req, "Thrift")}

	ns, nsPos := req.GetModel().GetPackage(), (*ir.Position)(nil)
	if d, ok := g.Block("package"); ok {
		ns, nsPos = d.GetArgs()[0].GetText(), d.GetPosition()
	}
	// The namespace heads the file, so one Thrift refuses is the whole
	// output rather than one declaration to skip.
	if !validNamespace(ns) {
		g.Error(nsPos, "%q is not a Thrift namespace", ns)
		return g.Response(nil), nil
	}

	own := g.Own()
	texts := map[*ir.Decl]string{}
	declared := map[*ir.Decl][]string{}
	skipped := map[*ir.Decl]bool{}
	for _, d := range own {
		text, names, err := g.decl(d)
		if err != nil {
			g.Warn(err)
			skipped[d] = true
			continue
		}
		if text != "" {
			texts[d], declared[d] = text, names
		}
	}

	// A name is claimed only for a declaration that survives, so one that
	// [emit.Session.Cascade] removes for naming a skipped declaration does
	// not hold its name against a later one. Claiming can skip a
	// declaration too, which frees its names and may remove a referrer, so
	// both run until nothing more is removed.
	for {
		g.Cascade(own, skipped)
		if !g.claim(own, texts, declared, skipped) {
			break
		}
	}

	order := g.order(own, func(d *ir.Decl) bool { return texts[d] != "" && !skipped[d] })
	if len(order) == 0 {
		return g.Response(nil), nil
	}

	var b strings.Builder
	b.WriteString("// Code generated by tdl. DO NOT EDIT.\n")
	if ns != "" {
		fmt.Fprintf(&b, "\nnamespace * %s\n", ns)
	}
	for _, d := range order {
		b.WriteString("\n")
		b.WriteString(texts[d])
	}

	path := "model.thrift"
	if ns != "" {
		path = emit.LastSegment(ns) + ".thrift"
	}
	return g.Response([]*plugin.File{{Path: path, Content: []byte(b.String())}}), nil
}

// order is the declarations to emit with each one after everything it
// names, keeping declaration order wherever that already holds. A cycle is
// left in declaration order, which is as close as a file read top to bottom
// can come.
func (g *generator) order(own []*ir.Decl, emitted func(*ir.Decl) bool) []*ir.Decl {
	var out []*ir.Decl
	visited := map[*ir.Decl]bool{}
	var visit func(d *ir.Decl)
	visit = func(d *ir.Decl) {
		if visited[d] {
			return
		}
		visited[d] = true
		for _, ref := range g.References(d) {
			if emitted(ref) {
				visit(ref)
			}
		}
		out = append(out, d)
	}
	for _, d := range own {
		if emitted(d) {
			visit(d)
		}
	}
	return out
}

// decl renders one declaration and the names it declares at file scope, or
// "" for one that declares nothing.
//
// Whether another declaration already took one of those names is not
// decided here: that answer depends on which declarations survive, which
// [emit.Session.Cascade] has yet to say. [generator.claim] decides it.
func (g *generator) decl(d *ir.Decl) (string, []string, error) {
	pos := d.GetMeta().GetPosition()
	name := d.GetMeta().GetName()

	switch {
	case d.GetClass() != nil:
		return "", nil, emit.Unsupported(pos, "%s is a class, and classes are not generated yet", name)
	case d.GetUnit() != nil:
		return "", nil, emit.Unsupported(pos, "%s is a unit, and units are not generated yet", name)
	case d.GetStructure() == nil && d.GetEnumeration() == nil && d.GetNewtype() == nil:
		// An alias is expanded where it is used, and a model's own
		// primitive names an opaque root; neither declares anything.
		return "", nil, nil
	}
	if len(d.Params()) > 0 {
		return "", nil, emit.Unsupported(pos, "%s is parameterized, and generics are not generated yet", name)
	}

	var b strings.Builder
	var declared []string
	var err error
	switch e := d.GetEnumeration(); {
	case d.GetNewtype() != nil:
		declared, err = g.typedef(&b, d)
	case d.GetStructure() != nil:
		declared, err = g.structure(&b, "struct", g.DeclName(d, emit.Pascal), d.GetMeta(), d.Fields())
	case emit.Fielded(e):
		declared, err = g.union(&b, d)
	default:
		declared, err = g.enum(&b, d)
	}
	if err != nil {
		return "", nil, err
	}

	for _, n := range declared {
		if !ident.MatchString(n) {
			return "", nil, emit.Unsupported(pos, "%s would be named %s in Thrift, which is not an identifier", name, n)
		}
		if keywords[n] {
			return "", nil, emit.Unsupported(pos, "%s would be named %s in Thrift, which is a keyword", name, n)
		}
	}
	g.WarnConstraints(d)
	return b.String(), declared, nil
}

// claim gives each surviving declaration the file-scope names it declares,
// skipping one whose name an earlier declaration already took, and reports
// whether it skipped anything.
//
// The names are claimed afresh on every call, because a declaration skipped
// since the last one no longer holds the names it declared.
func (g *generator) claim(own []*ir.Decl, texts map[*ir.Decl]string, declared map[*ir.Decl][]string, skipped map[*ir.Decl]bool) bool {
	names, changed := map[string]string{}, false
	for _, d := range own {
		if skipped[d] || texts[d] == "" {
			continue
		}
		name, taken := d.GetMeta().GetName(), false
		for _, n := range declared[d] {
			other, ok := names[n]
			if !ok {
				continue
			}
			g.Warn(emit.Unsupported(d.GetMeta().GetPosition(),
				"%s would declare %s in Thrift, and %s already does", name, n, other))
			skipped[d], changed, taken = true, true, true
			break
		}
		if taken {
			continue
		}
		for _, n := range declared[d] {
			names[n] = name
		}
	}
	return changed
}

// typedef renders a newtype as a named alias for its base.
func (g *generator) typedef(b *strings.Builder, d *ir.Decl) ([]string, error) {
	ref, err := g.Resolve(d.GetNewtype().GetBase())
	if err != nil {
		return nil, err
	}
	base, err := g.typ(ref)
	if err != nil {
		return nil, err
	}
	name := g.DeclName(d, emit.Pascal)
	comment(b, "", d.GetMeta())
	fmt.Fprintf(b, "typedef %s %s%s\n", base, name, annotation(d.GetMeta()))
	return []string{name}, nil
}

// structure renders a struct or a union body. An entity, a value, and a
// mixin differ in what they mean and not in what they emit.
func (g *generator) structure(b *strings.Builder, keyword, name string, meta *ir.Meta, fields []*ir.Field) ([]string, error) {
	nums, err := g.Numbers(name, emit.FieldMembers(fields), fieldNumbers)
	if err != nil {
		return nil, err
	}

	var body strings.Builder
	seen := map[string]bool{}
	for i, f := range fields {
		ref, err := g.Resolve(f.GetType())
		if err != nil {
			return nil, err
		}
		optional, typ, err := g.fieldType(ref)
		if err != nil {
			return nil, err
		}

		field := g.FieldName(f, asWritten)
		if err := g.member(seen, name, field, f.GetMeta().GetPosition()); err != nil {
			return nil, err
		}

		// A field that is not optional keeps Thrift's default requiredness
		// rather than `required`, which Thrift's own guidance advises
		// against because it can never be relaxed.
		label := ""
		if optional {
			label = "optional "
		}
		comment(&body, "  ", f.GetMeta())
		fmt.Fprintf(&body, "  %d: %s%s %s%s\n", nums[i], label, typ, field, annotation(f.GetMeta()))
	}

	comment(b, "", meta)
	fmt.Fprintf(b, "%s %s {\n%s}%s\n", keyword, name, body.String(), annotation(meta))
	return []string{name}, nil
}

// enum renders an enum whose variants carry no fields. A Thrift enum's
// values are scoped to it, so they carry no prefix.
func (g *generator) enum(b *strings.Builder, d *ir.Decl) ([]string, error) {
	name := g.DeclName(d, emit.Pascal)
	variants := d.GetEnumeration().GetVariants()
	nums, err := g.Numbers(name, emit.VariantMembers(variants), enumNumbers)
	if err != nil {
		return nil, err
	}

	var body strings.Builder
	seen := map[string]bool{}
	for i, v := range variants {
		value := emit.ScreamingSnake(v.GetMeta().GetName())
		if n, ok := g.Text(v.GetDirectives(), "name"); ok {
			value = n
		}
		if err := g.member(seen, name, value, v.GetMeta().GetPosition()); err != nil {
			return nil, err
		}
		comment(&body, "  ", v.GetMeta())
		fmt.Fprintf(&body, "  %s = %d%s\n", value, nums[i], annotation(v.GetMeta()))
	}

	comment(b, "", d.GetMeta())
	fmt.Fprintf(b, "enum %s {\n%s}%s\n", name, body.String(), annotation(d.GetMeta()))
	return []string{name}, nil
}

// union renders an enum where any variant carries fields: a struct per
// variant, named for the enum and the variant, and a union of them. A
// variant with no fields is an empty struct, since a union member is a
// field and a field has a type.
func (g *generator) union(b *strings.Builder, d *ir.Decl) ([]string, error) {
	name := g.DeclName(d, emit.Pascal)
	variants := d.GetEnumeration().GetVariants()
	nums, err := g.Numbers(name, emit.VariantMembers(variants), fieldNumbers)
	if err != nil {
		return nil, err
	}

	declared := []string{name}
	var members strings.Builder
	seen := map[string]bool{}
	for i, v := range variants {
		pos := v.GetMeta().GetPosition()
		structName := name + emit.Pascal(v.GetMeta().GetName())
		if n, ok := g.Text(v.GetDirectives(), "name"); ok {
			structName = n
		}
		if _, err := g.structure(b, "struct", structName, v.GetMeta(), v.GetFields()); err != nil {
			return nil, err
		}
		b.WriteString("\n")
		declared = append(declared, structName)

		field := emit.Camel(v.GetMeta().GetName())
		if err := g.member(seen, name, field, pos); err != nil {
			return nil, err
		}
		fmt.Fprintf(&members, "  %d: %s %s%s\n", nums[i], structName, field, annotation(v.GetMeta()))
	}

	comment(b, "", d.GetMeta())
	fmt.Fprintf(b, "union %s {\n%s}%s\n", name, members.String(), annotation(d.GetMeta()))
	return declared, nil
}

// member claims a name inside a struct, a union, or an enum.
func (g *generator) member(seen map[string]bool, owner, name string, pos *ir.Position) error {
	if !ident.MatchString(name) {
		return emit.Unsupported(pos, "%s.%s is not a Thrift identifier", owner, name)
	}
	if keywords[name] {
		return emit.Unsupported(pos, "%s.%s is a Thrift keyword", owner, name)
	}
	if seen[name] {
		return emit.Unsupported(pos, "%s has two members named %s in Thrift", owner, name)
	}
	seen[name] = true
	return nil
}

// fieldType returns whether a field is optional, and its type.
func (g *generator) fieldType(r *emit.Ref) (bool, string, error) {
	if r.Form != emit.Option && r.Form != emit.Nullable {
		typ, err := g.typ(r)
		return false, typ, err
	}
	if r.Elem.Form == emit.Option || r.Elem.Form == emit.Nullable {
		return false, "", emit.Unsupported(r.Pos, "an optional value holding an optional value has no Thrift form")
	}
	typ, err := g.typ(r.Elem)
	return true, typ, err
}

// typ is the Thrift type for anything but an optional, which only a field
// can be: a Thrift container holds no nulls.
func (g *generator) typ(r *emit.Ref) (string, error) {
	switch r.Form {
	case emit.Prim:
		typ, ok := scalars[r.Name]
		if !ok {
			return "", emit.Unsupported(r.Pos, "primitive %s has no Thrift type", r.Name)
		}
		return typ, nil
	case emit.List, emit.Set:
		elem, err := g.typ(r.Elem)
		if err != nil {
			return "", err
		}
		if r.Form == emit.Set {
			return "set<" + elem + ">", nil
		}
		return "list<" + elem + ">", nil
	case emit.Map:
		key, err := g.typ(r.Key)
		if err != nil {
			return "", err
		}
		val, err := g.typ(r.Elem)
		if err != nil {
			return "", err
		}
		return "map<" + key + ", " + val + ">", nil
	case emit.Option, emit.Nullable:
		return "", emit.Unsupported(r.Pos, "a Thrift container holds no nulls, so an optional value inside one has no Thrift form")
	}
	return g.DeclName(r.Decl, emit.Pascal), nil
}

func asWritten(name string) string { return name }

// comment writes a node's documentation as a doc comment, with its
// deprecation reason when it gave one.
func comment(b *strings.Builder, indent string, meta *ir.Meta) {
	lines := emit.Doc(meta)
	if reason, ok := emit.Deprecated(meta); ok && reason != "" {
		if len(lines) > 0 {
			lines = append(lines, "")
		}
		// A reason is prose and may be written over several lines, each of
		// which needs the comment's prefix.
		lines = append(lines, strings.Split("Deprecated: "+reason, "\n")...)
	}
	if len(lines) == 0 {
		return
	}
	fmt.Fprintf(b, "%s/**\n", indent)
	for _, line := range lines {
		if line == "" {
			fmt.Fprintf(b, "%s *\n", indent)
			continue
		}
		fmt.Fprintf(b, "%s * %s\n", indent, strings.ReplaceAll(line, "*/", "* /"))
	}
	fmt.Fprintf(b, "%s */\n", indent)
}

// annotation is the deprecation annotation Thrift carries through to the
// languages it generates, or "".
func annotation(meta *ir.Meta) string {
	reason, ok := emit.Deprecated(meta)
	if !ok {
		return ""
	}
	return " (deprecated = " + quote(reason) + ")"
}

// quote writes prose as a Thrift string literal.
//
// Thrift's lexer reads `\"` and `\\` inside one, so those two are escaped;
// a control character has no escape a literal can carry and is written as a
// space, which is what a reason spanning lines means on the one line an
// annotation is. The doc comment beside the annotation carries the text as
// it was written.
func quote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch {
		case r == '"' || r == '\\':
			b.WriteByte('\\')
			b.WriteRune(r)
		case r < 0x20 || r == 0x7f:
			b.WriteByte(' ')
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func validNamespace(ns string) bool {
	if ns == "" {
		return true
	}
	for seg := range strings.SplitSeq(ns, ".") {
		if !ident.MatchString(seg) {
			return false
		}
	}
	return true
}
