package thrift_test

import (
	"context"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cloudwego/thriftgo/parser"
	"github.com/cloudwego/thriftgo/semantic"

	"github.com/unstoppablemango/tdl/backend/internal/irtest"
	"github.com/unstoppablemango/tdl/backend/thrift"
	"github.com/unstoppablemango/tdl/ir"
	"github.com/unstoppablemango/tdl/plugin"
)

func generate(t *testing.T, b *irtest.Builder) *plugin.Response {
	t.Helper()
	resp, err := thrift.Backend{}.Generate(context.Background(), &plugin.Request{
		Target: thrift.Name,
		Model:  b.Model,
	})
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	return resp
}

// check returns the response's one file, and asserts Thrift accepts it.
//
// Parsing alone accepts a reference to a type nothing declares, which is
// what a skipped declaration leaves behind, so the symbols are resolved and
// the semantic checks run too.
func check(t *testing.T, resp *plugin.Response) string {
	t.Helper()
	if len(resp.GetFiles()) != 1 {
		t.Fatalf("files = %d, diagnostics = %+v", len(resp.GetFiles()), resp.GetDiagnostics())
	}
	f := resp.GetFiles()[0]
	src := string(f.GetContent())

	ast, err := parser.ParseString(f.GetPath(), src)
	if err != nil {
		t.Errorf("%s does not parse: %v\n%s", f.GetPath(), err, src)
		return src
	}
	if err := semantic.ResolveSymbols(ast); err != nil {
		t.Errorf("%s does not resolve: %v\n%s", f.GetPath(), err, src)
	}
	if warns, err := semantic.NewChecker(semantic.Options{}).CheckAll(ast); err != nil || len(warns) > 0 {
		t.Errorf("%s does not check: %v %v\n%s", f.GetPath(), err, warns, src)
	}
	return src
}

func contains(t *testing.T, src string, wants ...string) {
	t.Helper()
	flat := collapse(src)
	for _, want := range wants {
		if !strings.Contains(flat, collapse(want)) {
			t.Errorf("output missing %q:\n%s", want, src)
		}
	}
}

func absent(t *testing.T, src string, unwanted ...string) {
	t.Helper()
	for _, u := range unwanted {
		if strings.Contains(src, u) {
			t.Errorf("output has %q:\n%s", u, src)
		}
	}
}

func collapse(s string) string { return strings.Join(strings.Fields(s), " ") }

func value(name string, fields ...*ir.Field) *ir.Decl {
	return &ir.Decl{
		Meta: &ir.Meta{Name: name},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{Kind: ir.StructKind_STRUCT_KIND_VALUE, Fields: fields}},
	}
}

func enum(name string, variants ...*ir.Variant) *ir.Decl {
	return &ir.Decl{
		Meta: &ir.Meta{Name: name},
		Node: &ir.Decl_Enumeration{Enumeration: &ir.Enum{Variants: variants}},
	}
}

func variant(name string, fields ...*ir.Field) *ir.Variant {
	return &ir.Variant{Meta: &ir.Meta{Name: name}, Fields: fields}
}

func newtype(name string, base *ir.ID) *ir.Decl {
	return &ir.Decl{Meta: &ir.Meta{Name: name}, Node: &ir.Decl_Newtype{Newtype: &ir.Newtype{Base: base}}}
}

func number(n string) *ir.Directive {
	return &ir.Directive{Name: "number", Target: thrift.Name, Args: []*ir.Literal{{Kind: ir.LiteralKind_LITERAL_KIND_INT, Text: n}}}
}

func TestDescribe(t *testing.T) {
	d := thrift.Backend{}.Describe()
	if d.Name != "thrift" || !d.Reuse {
		t.Errorf("description = %+v", d)
	}
	declared := map[string]bool{}
	for _, spec := range d.Directives {
		declared[spec.GetName()] = true
	}
	for _, want := range []string{"package", "name", "number"} {
		if !declared[want] {
			t.Errorf("directive %q is acted on but not declared", want)
		}
	}
}

func TestStructs(t *testing.T) {
	b := irtest.New("shop.billing")
	b.Own(value("LineItem", irtest.Field("sku", b.Named("string")), irtest.Field("quantity", b.Named("int"))))
	b.Own(value("Order",
		irtest.Field("id", b.Named("uuid")),
		irtest.Field("items", b.Named("List", b.Named("LineItem"))),
		irtest.Field("tags", b.Named("Set", b.Named("string"))),
		irtest.Field("totals", b.Named("Map", b.Named("string"), b.Named("decimal"))),
		irtest.Field("note", b.Named("Option", b.Named("string"))),
		irtest.Field("maybe", b.Named("Nullable", b.Named("List", b.Named("string")))),
		irtest.Field("grid", b.Named("List", b.Named("List", b.Named("int")))),
		irtest.Field("receipt", b.Named("bytes")),
		irtest.Field("placedAt", b.Named("instant")),
	))

	resp := generate(t, b)
	if len(resp.GetDiagnostics()) != 0 {
		t.Errorf("diagnostics = %+v", resp.GetDiagnostics())
	}
	src := check(t, resp)
	if path := resp.GetFiles()[0].GetPath(); path != "billing.thrift" {
		t.Errorf("path = %q", path)
	}
	contains(t, src,
		"// Code generated by tdl. DO NOT EDIT.",
		"namespace * shop.billing",
		"struct LineItem { 1: string sku 2: i64 quantity }",
		"1: string id",
		"2: list<LineItem> items",
		"3: set<string> tags",
		"4: map<string, string> totals",
		"5: optional string note",
		"6: optional list<string> maybe",
		"7: list<list<i64>> grid",
		"8: binary receipt",
		"9: string placedAt",
	)
}

// A Thrift compiler reads a file top to bottom, so a declaration comes
// after everything it names, whatever order the model wrote them in.
func TestDependencyOrder(t *testing.T) {
	b := irtest.New("shop")
	order, item := value("Order"), value("Item")
	b.Own(order)
	b.Own(item)
	b.Own(newtype("Sku", b.Named("string")))
	order.GetStructure().Fields = []*ir.Field{irtest.Field("items", b.Named("List", b.Named("Item")))}
	item.GetStructure().Fields = []*ir.Field{irtest.Field("sku", b.Named("Sku"))}

	src := check(t, generate(t, b))
	atSku, atItem, atOrder := strings.Index(src, "typedef string Sku"), strings.Index(src, "struct Item"), strings.Index(src, "struct Order")
	if atSku < 0 || atItem < 0 || atOrder < 0 || atSku > atItem || atItem > atOrder {
		t.Errorf("declarations are not in dependency order:\n%s", src)
	}
}

// A struct may name itself, and the order does not loop on it.
func TestRecursiveStruct(t *testing.T) {
	b := irtest.New("shop")
	node := value("Node")
	b.Own(node)
	node.GetStructure().Fields = []*ir.Field{irtest.Field("children", b.Named("List", b.Named("Node")))}
	contains(t, check(t, generate(t, b)), "struct Node { 1: list<Node> children }")
}

func TestFieldlessEnum(t *testing.T) {
	b := irtest.New("shop")
	b.Own(enum("Status", variant("Active"), variant("InProgress")))
	b.Own(value("Ticket", irtest.Field("status", b.Named("Status"))))
	contains(t, check(t, generate(t, b)), "enum Status { ACTIVE = 1 IN_PROGRESS = 2 }", "1: Status status")
}

func TestFieldedEnumIsAUnion(t *testing.T) {
	b := irtest.New("shop")
	b.Own(enum("Payment", variant("Card", irtest.Field("last4", b.Named("string"))), variant("Cash")))

	src := check(t, generate(t, b))
	contains(t, src,
		"struct PaymentCard { 1: string last4 }",
		"struct PaymentCash { }",
		"union Payment { 1: PaymentCard card 2: PaymentCash cash }",
	)
}

func TestNewtypeIsATypedef(t *testing.T) {
	b := irtest.New("shop")
	b.Own(newtype("Sku", b.Named("string")))
	b.Own(newtype("Skus", b.Named("List", b.Named("Sku"))))
	b.Own(value("Basket", irtest.Field("skus", b.Named("Skus"))))
	contains(t, check(t, generate(t, b)), "typedef string Sku", "typedef list<Sku> Skus", "1: Skus skus")
}

func TestNumbers(t *testing.T) {
	b := irtest.New("shop")
	pinned := irtest.Field("b", b.Named("string"))
	pinned.Directives = []*ir.Directive{number("10")}
	b.Own(value("Pinned", irtest.Field("a", b.Named("string")), pinned, irtest.Field("c", b.Named("string"))))
	cash := variant("Cash")
	cash.Directives = []*ir.Directive{number("5")}
	b.Own(enum("Payment", variant("Card", irtest.Field("last4", b.Named("string"))), cash))

	contains(t, check(t, generate(t, b)), "1: string a 10: string b 3: string c", "1: PaymentCard card 5: PaymentCash cash")
}

func TestAFieldIdPastI16IsSkipped(t *testing.T) {
	b := irtest.New("shop")
	pinned := irtest.Field("a", b.Named("string"))
	pinned.Directives = []*ir.Directive{number("32768")}
	b.Own(value("Broken", pinned))
	b.Own(value("Fine", irtest.Field("a", b.Named("string"))))

	resp := generate(t, b)
	if len(resp.GetDiagnostics()) != 1 {
		t.Errorf("diagnostics = %+v", resp.GetDiagnostics())
	}
	src := check(t, resp)
	absent(t, src, "struct Broken")
	contains(t, src, "struct Fine")
}

// A Thrift container holds no nulls, so an optional value inside one is a
// warning, and whatever names the skipped declaration is skipped with it.
func TestUnsupportedShapesAreSkipped(t *testing.T) {
	for _, tt := range []struct {
		name string
		typ  func(b *irtest.Builder) *ir.ID
	}{
		{"a list of optionals", func(b *irtest.Builder) *ir.ID { return b.Named("List", b.Named("Option", b.Named("int"))) }},
		{"a map of nullables", func(b *irtest.Builder) *ir.ID {
			return b.Named("Map", b.Named("string"), b.Named("Nullable", b.Named("int")))
		}},
		{"an optional optional", func(b *irtest.Builder) *ir.ID {
			return b.Named("Nullable", b.Named("Option", b.Named("int")))
		}},
	} {
		t.Run(tt.name, func(t *testing.T) {
			b := irtest.New("shop")
			b.Own(value("Fine", irtest.Field("a", b.Named("string"))))
			b.Own(value("Broken", irtest.Field("x", tt.typ(b))))
			b.Own(value("Holder", irtest.Field("broken", b.Named("Broken"))))

			resp := generate(t, b)
			if len(resp.GetDiagnostics()) != 2 {
				t.Errorf("want a warning for Broken and one for Holder: %+v", resp.GetDiagnostics())
			}
			src := check(t, resp)
			absent(t, src, "struct Broken", "struct Holder")
			contains(t, src, "struct Fine")
		})
	}
}

func TestKeywordsAreSkipped(t *testing.T) {
	b := irtest.New("shop")
	b.Own(value("Broken", irtest.Field("list", b.Named("string"))))
	b.Own(value("Fine", irtest.Field("type", b.Named("string"))))

	resp := generate(t, b)
	if len(resp.GetDiagnostics()) != 1 {
		t.Errorf("diagnostics = %+v", resp.GetDiagnostics())
	}
	src := check(t, resp)
	absent(t, src, "struct Broken")
	contains(t, src, "1: string type")
}

func TestConstraintsWarn(t *testing.T) {
	b := irtest.New("shop")
	qty := irtest.Field("quantity", b.Named("int"))
	qty.Constraints = []*ir.Constraint{{Name: "min"}}
	b.Own(value("Line", qty))

	resp := generate(t, b)
	if len(resp.GetDiagnostics()) != 1 {
		t.Errorf("diagnostics = %+v", resp.GetDiagnostics())
	}
	contains(t, check(t, resp), "1: i64 quantity")
}

func TestDocsAndDeprecation(t *testing.T) {
	b := irtest.New("shop")
	old := irtest.Field("fax", b.Named("string"))
	old.Meta.Deprecated = &ir.Deprecation{Reason: "nobody has one"}
	b.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Contact", Doc: []string{"How to reach someone."}, Deprecated: &ir.Deprecation{}},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{Fields: []*ir.Field{old}}},
	})

	contains(t, check(t, generate(t, b)),
		"/** * How to reach someone. */",
		"/** * Deprecated: nobody has one */",
		`1: string fax (deprecated = "nobody has one")`,
		`} (deprecated = "")`,
	)
}

func TestNamespaceDirective(t *testing.T) {
	block := func(ns string) []*ir.TargetBlock {
		return []*ir.TargetBlock{{
			Meta:       &ir.Meta{Name: thrift.Name},
			Directives: []*ir.Directive{{Name: "package", Target: thrift.Name, Args: []*ir.Literal{irtest.Text(ns)}}},
		}}
	}

	b := irtest.New("shop")
	b.Own(value("Note", irtest.Field("body", b.Named("string"))))
	b.Model.Targets = block("acme.billing")
	resp := generate(t, b)
	contains(t, check(t, resp), "namespace * acme.billing")
	if path := resp.GetFiles()[0].GetPath(); path != "billing.thrift" {
		t.Errorf("path = %q", path)
	}

	b.Model.Targets = block("acme billing")
	resp = generate(t, b)
	if len(resp.GetFiles()) != 0 || len(resp.GetDiagnostics()) != 1 ||
		resp.GetDiagnostics()[0].GetSeverity() != plugin.Severity_SEVERITY_ERROR {
		t.Errorf("a namespace Thrift refuses should be an error and nothing else: %+v", resp)
	}
}

// Every case in the conformance corpus generates something Thrift accepts,
// whatever this backend warned about along the way.
func TestConformance(t *testing.T) {
	for _, c := range []string{
		"aliases", "collections", "comments", "constraints", "deprecated", "entity",
		"enum_variants", "mixin_include", "newtype", "targets", "targets_variants", "value",
	} {
		t.Run(c, func(t *testing.T) {
			model := irtest.Conformance(t, filepath.Join("..", "..", "testdata", "conformance", c))
			resp, err := thrift.Backend{}.Generate(context.Background(), &plugin.Request{Target: thrift.Name, Model: model})
			if err != nil {
				t.Fatal(err)
			}
			for _, d := range resp.GetDiagnostics() {
				if d.GetSeverity() == plugin.Severity_SEVERITY_ERROR {
					t.Errorf("error: %s", d.GetMessage())
				}
			}
			if len(resp.GetFiles()) > 0 {
				check(t, resp)
			}
		})
	}
}
