name: Build go
description: Builds go code

inputs:
  path:
    description: Path to the package
    required: true

runs:
  using: composite
  steps:
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.work

    - name: Verify dependencies
      shell: bash
      working-directory: ${{ inputs.path }}
      run: go mod verify

    - name: Build
      shell: bash
      working-directory: ${{ inputs.path }}
      run: make build

    - name: Vet
      shell: bash
      working-directory: ${{ inputs.path }}
      run: make vet

    - name: Lint
      uses: golangci/golangci-lint-action@v5
      working-directory: ${{ inputs.path }}
      with:
        version: v1.57
