name: Build go
description: Builds go code

inputs:
  lib:
    description: Treat as a library.
    default: 'false'
  path:
    description: Path to the package.
    required: true
  module:
    description: Path to the go module.
    required: true

runs:
  using: composite
  steps:
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ inputs.module }}/go.mod
        cache-dependency-path: ${{ inputs.module }}/go.sum

    - name: Verify dependencies
      shell: bash
      working-directory: ${{ inputs.path }}
      run: go mod verify

    - name: Build
      if: inputs.lib == 'true'
      shell: bash
      working-directory: ${{ inputs.path }}
      run: go build ./...

    - name: Build
      if: inputs.lib != 'true'
      shell: bash
      working-directory: ${{ inputs.path }}
      run: make build

    - name: Test
      if: github.event_name == 'pull_request'
      shell: bash
      working-directory: ${{ inputs.path }}
      run: go test ./...

    - name: Vet
      if: github.event_name == 'pull_request'
      shell: bash
      working-directory: ${{ inputs.path }}
      run: go vet ./...

    - name: Lint
      if: github.event_name == 'pull_request'
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60.3
        working-directory: ${{ inputs.path }}
