name: Build go
description: Builds go code

inputs:
  lib:
    description: Treat as a library.
    default: 'false'
  path:
    description: Path to the package.
    required: true
  gomod:
    description: Path to the go.mod file.
    required: true

runs:
  using: composite
  steps:
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ inputs.gomod }}

    - name: Verify dependencies
      shell: bash
      working-directory: ${{ inputs.path }}
      run: go mod verify

    - name: Build
      if: inputs.lib == 'true'
      shell: bash
      working-directory: ${{ inputs.path }}
      run: go build ./...

    - name: Build
      if: inputs.lib != 'true'
      shell: bash
      working-directory: ${{ inputs.path }}
      run: make build

    - name: Vet
      shell: bash
      working-directory: ${{ inputs.path }}
      run: go vet ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.57
        working-directory: ${{ inputs.path }}
