name: Build Bun
description: Builds code using Bun

inputs:
  path:
    description: Path to the package
    required: true

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: package.json

    - name: Restore dependencies
      shell: bash
      working-directory: ${{ inputs.path }}
      run: bun install --frozen-lockfile

    - name: Build
      shell: bash
      working-directory: ${{ inputs.path }}
      run: bun run build

    - name: Test
      if: github.event_name == 'pull_request'
      shell: bash
      working-directory: ${{ inputs.path }}
      run: bun test

    - name: Lint
      if: github.event_name == 'pull_request'
      shell: bash
      # This will likely error on unrelated linting errors...
      # working-directory: ${{ inputs.path }}
      run: bun lint

    - name: Format
      if: github.event_name == 'pull_request'
      uses: dprint/check@v2.3
