name: Build Bun
description: Builds code using Bun

inputs:
  path:
    description: Path to the package
    required: true

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.1.15

    - name: Restore dependencies
      shell: bash
      working-directory: ${{ inputs.path }}
      run: bun install --frozen-lockfile

    - name: Build
      shell: bash
      working-directory: ${{ inputs.path }}
      run: bun run build

    - name: Test
      shell: bash
      working-directory: ${{ inputs.path }}
      run: bun test

    - name: Lint
      shell: bash
      # This will likely error on unrelated linting errors...
      # working-directory: ${{ inputs.path }}
      run: bun lint

    - name: Format
      uses: dprint/check@v2.2
