package golang_test

import (
	"context"
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"slices"
	"sort"
	"strings"
	"testing"

	"github.com/unstoppablemango/tdl/backend/golang"
	"github.com/unstoppablemango/tdl/backend/internal/irtest"
	"github.com/unstoppablemango/tdl/ir"
	"github.com/unstoppablemango/tdl/plugin"
)

func generate(t *testing.T, m *irtest.Builder) *plugin.Response {
	t.Helper()
	resp, err := golang.Backend{}.Generate(context.Background(), &plugin.Request{
		Target: golang.Name,
		Model:  m.Model,
	})
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	return resp
}

// files keys a response by path, and asserts the response is a Go package
// that compiles.
//
// Type checking rather than parsing is the assertion that matters. A
// substring check can pass while the output is something go build refuses,
// and so can parsing: `map[[]byte]struct{}` parses, and an undeclared type
// a skipped declaration left behind parses too.
//
// The whole response is checked as one package, since one file per
// declaration means a struct's field type is usually declared in another
// file.
func files(t *testing.T, resp *plugin.Response) map[string]string {
	t.Helper()
	out := map[string]string{}
	fset := token.NewFileSet()

	var parsed []*ast.File
	for _, f := range resp.GetFiles() {
		src := string(f.GetContent())
		out[f.GetPath()] = src

		file, err := parser.ParseFile(fset, f.GetPath(), src, parser.AllErrors)
		if err != nil {
			t.Errorf("%s is not parseable Go: %v\n%s", f.GetPath(), err, src)
			continue
		}
		parsed = append(parsed, file)
	}
	if len(parsed) != len(resp.GetFiles()) || len(parsed) == 0 {
		return out
	}

	// The source importer reads GOROOT rather than a build cache, so this
	// needs nothing installed and no module on disk. The generated package
	// imports only the standard library.
	conf := types.Config{Importer: importer.ForCompiler(fset, "source", nil)}
	if _, err := conf.Check(parsed[0].Name.Name, fset, parsed, nil); err != nil {
		t.Errorf("the generated package does not type check: %v\n%s", err, strings.Join(sources(out), "\n"))
	}
	return out
}

// sources returns the response's files in a stable order, for a failure to
// print.
func sources(out map[string]string) []string {
	paths := keys(out)
	sort.Strings(paths)
	srcs := make([]string, 0, len(paths))
	for _, p := range paths {
		srcs = append(srcs, "==> "+p+" <==\n"+out[p])
	}
	return srcs
}

// contains asserts on the output with runs of whitespace collapsed, since
// gofmt aligns a struct's field types into columns and the alignment moves
// whenever a sibling field's name changes length.
func contains(t *testing.T, src string, wants ...string) {
	t.Helper()
	flat := collapse(src)
	for _, want := range wants {
		if !strings.Contains(flat, collapse(want)) {
			t.Errorf("output missing %q:\n%s", want, src)
		}
	}
}

func collapse(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

func TestDescribe(t *testing.T) {
	d := golang.Backend{}.Describe()
	// The name is what a target block writes, and the package it lives in
	// is called something else on purpose.
	if d.Name != "go" {
		t.Errorf("name = %q", d.Name)
	}
	if !d.Reuse {
		t.Error("a request is answered from the request alone, so reuse should be declared")
	}

	declared := map[string]bool{}
	for _, spec := range d.Directives {
		declared[spec.GetName()] = true
	}
	for _, want := range []string{"package", "name", "tag", "key"} {
		if !declared[want] {
			t.Errorf("directive %q is acted on but not declared, so the compiler would warn about it", want)
		}
	}
}

func TestStructs(t *testing.T) {
	m := irtest.New("shop.billing")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "LineItem", Doc: []string{"One line on an order."}},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Kind: ir.StructKind_STRUCT_KIND_VALUE,
			Fields: []*ir.Field{
				irtest.Field("sku", m.Named("string")),
				irtest.Field("quantity", m.Named("int")),
			},
		}},
	})

	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Order"},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Kind: ir.StructKind_STRUCT_KIND_ENTITY,
			Fields: []*ir.Field{
				{Meta: &ir.Meta{Name: "id"}, Type: m.Named("string")},
				irtest.Field("placedAt", m.Named("instant")),
				irtest.Field("items", m.Named("List", m.Named("LineItem"))),
				irtest.Field("tags", m.Named("Set", m.Named("string"))),
				irtest.Field("totals", m.Named("Map", m.Named("string"), m.Named("decimal"))),
				irtest.Field("note", m.Named("Option", m.Named("string"))),
			},
		}},
	})

	got := files(t, generate(t, m))

	item, ok := got["line_item.go"]
	if !ok {
		t.Fatalf("no line_item.go in %v", keys(got))
	}
	contains(t, item,
		"// Code generated by tdl. DO NOT EDIT.",
		"package billing",
		"// One line on an order.",
		"type LineItem struct {",
		"Sku string",
		"Quantity int64",
	)

	order, ok := got["order.go"]
	if !ok {
		t.Fatalf("no order.go in %v", keys(got))
	}
	contains(t, order,
		`import "time"`,
		"Id string",
		"PlacedAt time.Time",
		"Items []LineItem",
		"Tags map[string]struct{}",
		"Totals map[string]string",
		"Note *string",
	)
}

// The three struct kinds mean different things and emit the same shape: Go
// has no way to say "identity that survives changes to its contents".
func TestMixinIsAStructToo(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Audit"},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Kind:   ir.StructKind_STRUCT_KIND_MIXIN,
			Fields: []*ir.Field{irtest.Field("createdAt", m.Named("instant"))},
		}},
	})

	got := files(t, generate(t, m))
	contains(t, got["audit.go"], "type Audit struct {", "CreatedAt time.Time")
}

func TestFieldlessEnumIsConstants(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Status"},
		Node: &ir.Decl_Enumeration{Enumeration: &ir.Enum{
			Variants: []*ir.Variant{
				{Meta: &ir.Meta{Name: "Active"}},
				{Meta: &ir.Meta{Name: "Pending"}},
			},
		}},
	})

	got := files(t, generate(t, m))
	src := got["status.go"]
	contains(t, src,
		"type Status string",
		`StatusActive Status = "Active"`,
		`StatusPending Status = "Pending"`,
	)
	if strings.Contains(src, "interface") {
		t.Errorf("a fieldless enum should not be an interface:\n%s", src)
	}
}

func TestVariantWithFieldsIsASealedInterface(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Payment"},
		Node: &ir.Decl_Enumeration{Enumeration: &ir.Enum{
			Variants: []*ir.Variant{
				{Meta: &ir.Meta{Name: "Cash"}},
				{
					Meta:   &ir.Meta{Name: "Card"},
					Fields: []*ir.Field{irtest.Field("last4", m.Named("string"))},
				},
			},
		}},
	})

	got := files(t, generate(t, m))
	src := got["payment.go"]
	contains(t, src,
		"type Payment interface{ isPayment() }",
		"type PaymentCash struct {",
		"func (PaymentCash) isPayment() {}",
		"type PaymentCard struct {",
		"Last4 string",
		"func (PaymentCard) isPayment() {}",
	)
	// One variant carrying fields decides the shape for the whole enum,
	// which is the cost of the split and the reason it is written down.
	if strings.Contains(src, "const (") {
		t.Errorf("an enum with a field-carrying variant should not emit constants:\n%s", src)
	}
}

func TestNewtype(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Sku"},
		Node: &ir.Decl_Newtype{Newtype: &ir.Newtype{Base: m.Named("string")}},
	})

	got := files(t, generate(t, m))
	contains(t, got["sku.go"], "type Sku string")
}

// A newtype's `where` constraints are not enforced yet, and the backend
// says so rather than letting the model believe they are. The type itself
// is still emitted: skipping it would leave every field naming it referring
// to something the package does not declare.
func TestConstrainedNewtypeIsEmittedWithAWarning(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Email", Position: &ir.Position{Filename: irtest.OwnFile, Line: 7}},
		Node: &ir.Decl_Newtype{Newtype: &ir.Newtype{
			Base:             m.Named("string"),
			ValueConstraints: []*ir.Constraint{{Name: "matches"}},
		}},
	})
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Contact"},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Fields: []*ir.Field{irtest.Field("email", m.Named("Email"))},
		}},
	})

	resp := generate(t, m)
	if len(resp.GetDiagnostics()) != 1 {
		t.Fatalf("diagnostics = %+v", resp.GetDiagnostics())
	}
	if line := resp.GetDiagnostics()[0].GetPosition().GetLine(); line != 7 {
		t.Errorf("position line = %d", line)
	}

	got := files(t, resp)
	contains(t, got["email.go"], "type Email string")
	contains(t, got["contact.go"], "Email Email")
}

// Go requires a map key to be comparable, so a Set or a Map that would
// become one it refuses is reported rather than emitted.
func TestIncomparableKeysAreUnsupported(t *testing.T) {
	for _, tt := range []struct {
		name string
		typ  func(m *irtest.Builder) *ir.ID
	}{
		{"set of bytes", func(m *irtest.Builder) *ir.ID { return m.Named("Set", m.Named("bytes")) }},
		{"set of lists", func(m *irtest.Builder) *ir.ID {
			return m.Named("Set", m.Named("List", m.Named("string")))
		}},
		{"map keyed by a list", func(m *irtest.Builder) *ir.ID {
			return m.Named("Map", m.Named("List", m.Named("string")), m.Named("string"))
		}},
		{"map keyed by a struct holding a list", func(m *irtest.Builder) *ir.ID {
			return m.Named("Map", m.Named("Path"), m.Named("string"))
		}},
	} {
		t.Run(tt.name, func(t *testing.T) {
			m := irtest.New("shop")
			m.Own(&ir.Decl{
				Meta: &ir.Meta{Name: "Path"},
				Node: &ir.Decl_Structure{Structure: &ir.Struct{
					Fields: []*ir.Field{irtest.Field("segments", m.Named("List", m.Named("string")))},
				}},
			})
			m.Own(&ir.Decl{
				Meta: &ir.Meta{Name: "Index", Position: &ir.Position{Filename: irtest.OwnFile, Line: 9}},
				Node: &ir.Decl_Structure{Structure: &ir.Struct{
					Fields: []*ir.Field{irtest.Field("by", tt.typ(m))},
				}},
			})

			resp := generate(t, m)
			if len(resp.GetDiagnostics()) != 1 {
				t.Fatalf("diagnostics = %+v", resp.GetDiagnostics())
			}
			got := files(t, resp)
			if _, ok := got["index.go"]; ok {
				t.Errorf("a declaration with an uncompilable field was emitted:\n%s", got["index.go"])
			}
		})
	}
}

// A skipped declaration is one the package does not declare, so whatever
// names it is skipped too, however far away, rather than emitted naming an
// undeclared type.
func TestReferringToASkippedDeclarationSkipsItToo(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Index", Position: &ir.Position{Filename: irtest.OwnFile, Line: 3}},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Fields: []*ir.Field{irtest.Field("by", m.Named("Set", m.Named("bytes")))},
		}},
	})
	// Declared before what it names, so a single pass in declaration order
	// would have rendered it before learning its field is skipped. Its field
	// is attached once Top exists, since a type reference is made by name.
	outer := &ir.Struct{}
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Outer", Position: &ir.Position{Filename: irtest.OwnFile, Line: 5}},
		Node: &ir.Decl_Structure{Structure: outer},
	})
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Top", Position: &ir.Position{Filename: irtest.OwnFile, Line: 7}},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Fields: []*ir.Field{irtest.Field("index", m.Named("Index"))},
		}},
	})
	outer.Fields = []*ir.Field{irtest.Field("top", m.Named("Option", m.Named("Top")))}
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Note"},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Fields: []*ir.Field{irtest.Field("body", m.Named("string"))},
		}},
	})

	resp := generate(t, m)
	if len(resp.GetDiagnostics()) != 3 {
		t.Fatalf("diagnostics = %+v", resp.GetDiagnostics())
	}
	for _, d := range resp.GetDiagnostics() {
		if d.GetSeverity() != plugin.Severity_SEVERITY_WARNING {
			t.Errorf("severity = %v", d.GetSeverity())
		}
	}

	got := files(t, resp)
	if want := []string{"note.go"}; !slices.Equal(keys(got), want) {
		t.Errorf("files = %v, want %v", keys(got), want)
	}
}

// A collection's type argument and an alias's target are expanded rather
// than named, and a skipped declaration reached through either is still one
// the package does not declare.
func TestASkippedDeclarationInsideAnExpansionIsSkipped(t *testing.T) {
	for _, tt := range []struct {
		name string
		typ  func(m *irtest.Builder, index *ir.ID) *ir.ID
	}{
		{"list element", func(m *irtest.Builder, index *ir.ID) *ir.ID { return m.Named("List", index) }},
		{"map value", func(m *irtest.Builder, index *ir.ID) *ir.ID {
			return m.Named("Map", m.Named("string"), index)
		}},
		{"alias target", func(m *irtest.Builder, index *ir.ID) *ir.ID {
			m.Own(&ir.Decl{
				Meta: &ir.Meta{Name: "Lookup"},
				Node: &ir.Decl_Alias{Alias: &ir.Alias{Target: index}},
			})
			return m.Named("Lookup")
		}},
	} {
		t.Run(tt.name, func(t *testing.T) {
			m := irtest.New("shop")
			m.Own(&ir.Decl{
				Meta: &ir.Meta{Name: "Index", Position: &ir.Position{Filename: irtest.OwnFile, Line: 3}},
				Node: &ir.Decl_Structure{Structure: &ir.Struct{
					Fields: []*ir.Field{irtest.Field("by", m.Named("Set", m.Named("bytes")))},
				}},
			})
			m.Own(&ir.Decl{
				Meta: &ir.Meta{Name: "Catalog", Position: &ir.Position{Filename: irtest.OwnFile, Line: 7}},
				Node: &ir.Decl_Structure{Structure: &ir.Struct{
					Fields: []*ir.Field{irtest.Field("index", tt.typ(m, m.Named("Index")))},
				}},
			})
			m.Own(&ir.Decl{
				Meta: &ir.Meta{Name: "Note"},
				Node: &ir.Decl_Structure{Structure: &ir.Struct{
					Fields: []*ir.Field{irtest.Field("body", m.Named("string"))},
				}},
			})

			resp := generate(t, m)
			if len(resp.GetDiagnostics()) != 2 {
				t.Fatalf("diagnostics = %+v", resp.GetDiagnostics())
			}
			for _, d := range resp.GetDiagnostics() {
				if d.GetSeverity() != plugin.Severity_SEVERITY_WARNING {
					t.Errorf("severity = %v", d.GetSeverity())
				}
			}
			// The cascade warns at the declaration being skipped rather than
			// at the reference that reached the skipped one, since a
			// declaration may name it more than once.
			if line := resp.GetDiagnostics()[1].GetPosition().GetLine(); line != 7 {
				t.Errorf("Catalog's warning is at line %d, want Catalog at 7", line)
			}

			got := files(t, resp)
			if want := []string{"note.go"}; !slices.Equal(keys(got), want) {
				t.Errorf("files = %v, want %v", keys(got), want)
			}
		})
	}
}

// Reaching the same declaration twice on separate paths is not a cycle, so
// the walk that stops one has to unwind as it returns.
func TestARepeatedFieldTypeIsNotACycle(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Coord"},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Fields: []*ir.Field{irtest.Field("value", m.Named("int"))},
		}},
	})
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Point"},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Fields: []*ir.Field{
				irtest.Field("x", m.Named("Coord")),
				irtest.Field("y", m.Named("Coord")),
			},
		}},
	})
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Grid"},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Fields: []*ir.Field{irtest.Field("seen", m.Named("Set", m.Named("Point")))},
		}},
	})

	resp := generate(t, m)
	if len(resp.GetDiagnostics()) != 0 {
		t.Fatalf("diagnostics = %+v", resp.GetDiagnostics())
	}
	contains(t, files(t, resp)["grid.go"], "Seen map[Point]struct{}")
}

// A comparable element is still a map, since that is the only Go shape that
// keeps what a Set promises.
func TestComparableSetsStillGenerate(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Sku"},
		Node: &ir.Decl_Newtype{Newtype: &ir.Newtype{Base: m.Named("string")}},
	})
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Basket"},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Fields: []*ir.Field{
				irtest.Field("skus", m.Named("Set", m.Named("Sku"))),
				// A pointer is comparable whatever it points at, so an
				// optional element is a legal key even when its element
				// would not be.
				irtest.Field("maybe", m.Named("Set", m.Named("Option", m.Named("bytes")))),
			},
		}},
	})

	resp := generate(t, m)
	if len(resp.GetDiagnostics()) != 0 {
		t.Fatalf("diagnostics = %+v", resp.GetDiagnostics())
	}
	contains(t, files(t, resp)["basket.go"],
		"Skus map[Sku]struct{}",
		"Maybe map[*[]byte]struct{}",
	)
}

// An alias is transparent, so it is expanded at every use rather than
// declared.
func TestAliasIsExpanded(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Tags"},
		Node: &ir.Decl_Alias{Alias: &ir.Alias{Target: m.Named("List", m.Named("string"))}},
	})
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Post"},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Fields: []*ir.Field{irtest.Field("tags", m.Named("Tags"))},
		}},
	})

	got := files(t, generate(t, m))
	if _, ok := got["tags.go"]; ok {
		t.Error("an alias should not generate a declaration")
	}
	contains(t, got["post.go"], "Tags []string")
}

func TestDirectives(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta:       &ir.Meta{Name: "User"},
		Directives: []*ir.Directive{{Name: "name", Target: "go", Args: []*ir.Literal{irtest.Text("Account")}}},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Fields: []*ir.Field{
				{
					Meta: &ir.Meta{Name: "email"},
					Type: m.Named("string"),
					Directives: []*ir.Directive{
						{Name: "tag", Target: "go", Args: []*ir.Literal{irtest.Text(`json:"email_address"`)}},
						// A model carries directives for every target
						// block, so one that does not filter would read
						// another backend's.
						{Name: "tag", Target: "sql", Args: []*ir.Literal{irtest.Text(`db:"nope"`)}},
					},
				},
			},
		}},
	})
	m.Model.Targets = []*ir.TargetBlock{{
		Meta:       &ir.Meta{Name: "go"},
		Directives: []*ir.Directive{{Name: "package", Target: "go", Args: []*ir.Literal{irtest.Text("github.com/acme/billing")}}},
	}}

	got := files(t, generate(t, m))
	src, ok := got["user.go"]
	if !ok {
		t.Fatalf("no user.go in %v", keys(got))
	}
	contains(t, src,
		"package billing",
		"type Account struct {",
		"`json:\"email_address\"`",
	)
	if strings.Contains(src, "db:") {
		t.Errorf("another target's directive leaked through:\n%s", src)
	}
}

// A package clause is one identifier that every file carries, so a name Go
// will not accept is an error rather than a warning: nothing is generated
// and the host writes nothing.
func TestAKeywordPackageNameIsAnError(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Note"},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Fields: []*ir.Field{irtest.Field("body", m.Named("string"))},
		}},
	})
	m.Model.Targets = []*ir.TargetBlock{{
		Meta: &ir.Meta{Name: "go"},
		Directives: []*ir.Directive{{
			Name:     "package",
			Target:   "go",
			Args:     []*ir.Literal{irtest.Text("github.com/acme/type")},
			Position: &ir.Position{Filename: irtest.OwnFile, Line: 2},
		}},
	}}

	resp := generate(t, m)
	if len(resp.GetFiles()) != 0 {
		t.Errorf("a package clause Go refuses still generated files: %v", keys(files(t, resp)))
	}
	if len(resp.GetDiagnostics()) != 1 {
		t.Fatalf("diagnostics = %+v", resp.GetDiagnostics())
	}
	d := resp.GetDiagnostics()[0]
	if d.GetSeverity() != plugin.Severity_SEVERITY_ERROR {
		t.Errorf("severity = %v, and the host only stops on an error", d.GetSeverity())
	}
	if d.GetPosition().GetLine() != 2 {
		t.Errorf("position = %+v, and the directive is what to point at", d.GetPosition())
	}
}

// A backend says what it cannot handle in a diagnostic rather than by
// returning an error, and a warning does not stop the rest of the model
// from generating.
func TestUnsupportedIsAWarning(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "kg", Position: &ir.Position{Filename: irtest.OwnFile, Line: 4}},
		Node: &ir.Decl_Unit{Unit: &ir.UnitDef{Base: true}},
	})
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Note"},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Fields: []*ir.Field{irtest.Field("body", m.Named("string"))},
		}},
	})

	resp := generate(t, m)
	if len(resp.GetDiagnostics()) != 1 {
		t.Fatalf("diagnostics = %+v", resp.GetDiagnostics())
	}
	d := resp.GetDiagnostics()[0]
	if d.GetSeverity() != plugin.Severity_SEVERITY_WARNING {
		t.Errorf("severity = %v", d.GetSeverity())
	}
	if d.GetPosition().GetLine() != 4 {
		t.Errorf("position = %+v", d.GetPosition())
	}

	got := files(t, resp)
	if _, ok := got["note.go"]; !ok {
		t.Errorf("a warning suppressed the rest of the model: %v", keys(got))
	}
}

// The prelude is merged into the declaration table untagged, so a backend
// that emits per declaration has to tell it apart from the model's own.
func TestPreludeIsNotGenerated(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Note"},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Fields: []*ir.Field{irtest.Field("body", m.Named("string"))},
		}},
	})

	got := files(t, generate(t, m))
	if len(got) != 1 {
		t.Errorf("expected only the model's own declaration, got %v", keys(got))
	}
}

// The prelude is recognized by its whole name and not by how the name ends,
// so a user's file that happens to end the same way is still theirs.
func TestAFileEndingInStdIsNotThePrelude(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Note", Position: &ir.Position{Filename: "my-std.tdl"}},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Fields: []*ir.Field{irtest.Field("body", m.Named("string"))},
		}},
	})

	got := files(t, generate(t, m))
	if _, ok := got["note.go"]; !ok {
		t.Errorf("a user file was mistaken for the prelude: %v", keys(got))
	}
}

// An entity's key is a target directive naming fields, and it becomes a key
// type and a method returning it, so a consumer can index entities without
// reading the .tdl file.
func TestEntityKey(t *testing.T) {
	m := irtest.New("shop")
	m.Own(keyed("LineItem", []*ir.Field{
		irtest.Field("order", m.Named("string")),
		irtest.Field("sku", m.Named("string")),
		irtest.Field("quantity", m.Named("int")),
	}, irtest.Name("order"), irtest.Name("sku")))

	resp := generate(t, m)
	if len(resp.GetDiagnostics()) != 0 {
		t.Errorf("diagnostics = %+v", resp.GetDiagnostics())
	}
	got := files(t, resp)
	contains(t, got["line_item.go"],
		"type LineItemKey struct { Order string Sku string }",
		"func (l LineItem) Key() LineItemKey {",
		"return LineItemKey{Order: l.Order, Sku: l.Sku}",
	)
}

// A key of one field is that field's type, with no struct around it.
func TestSingleFieldKey(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "UserID"},
		Node: &ir.Decl_Newtype{Newtype: &ir.Newtype{Base: m.Named("string")}},
	})
	m.Own(keyed("User", []*ir.Field{
		irtest.Field("id", m.Named("UserID")),
		irtest.Field("email", m.Named("string")),
	}, irtest.Name("id")))

	got := files(t, generate(t, m))
	src := got["user.go"]
	contains(t, src, "func (u User) Key() UserID {", "return u.Id")
	if strings.Contains(src, "UserKey") {
		t.Errorf("a single-field key generated a key type:\n%s", src)
	}
}

// A key the backend cannot generate is a warning at the directive, and the
// entity is still emitted: skipping it would leave every field naming it
// referring to an undeclared type.
func TestKeyIsAWarningWhenItCannotBeGenerated(t *testing.T) {
	cases := []struct {
		name  string
		build func(m *irtest.Builder)
		file  string
	}{
		{"on a value", func(m *irtest.Builder) {
			d := keyed("Money", []*ir.Field{irtest.Field("amount", m.Named("int"))}, irtest.Name("amount"))
			d.GetStructure().Kind = ir.StructKind_STRUCT_KIND_VALUE
			m.Own(d)
		}, "money.go"},
		{"an argument that is not a name", func(m *irtest.Builder) {
			m.Own(keyed("User", []*ir.Field{irtest.Field("id", m.Named("string"))}, irtest.Text("id")))
		}, "user.go"},
		{"a name that is no field", func(m *irtest.Builder) {
			m.Own(keyed("User", []*ir.Field{irtest.Field("id", m.Named("string"))}, irtest.Name("nope")))
		}, "user.go"},
		{"a repeated field", func(m *irtest.Builder) {
			m.Own(keyed("User", []*ir.Field{irtest.Field("id", m.Named("string"))}, irtest.Name("id"), irtest.Name("id")))
		}, "user.go"},
		{"an incomparable field", func(m *irtest.Builder) {
			m.Own(keyed("Blob", []*ir.Field{irtest.Field("hash", m.Named("bytes"))}, irtest.Name("hash")))
		}, "blob.go"},
		{"a field the method would collide with", func(m *irtest.Builder) {
			m.Own(keyed("Secret", []*ir.Field{
				irtest.Field("id", m.Named("string")),
				irtest.Field("key", m.Named("string")),
			}, irtest.Name("id")))
		}, "secret.go"},
		{"a declaration the key type would collide with", func(m *irtest.Builder) {
			m.Own(&ir.Decl{
				Meta: &ir.Meta{Name: "LineItemKey"},
				Node: &ir.Decl_Structure{Structure: &ir.Struct{
					Fields: []*ir.Field{irtest.Field("raw", m.Named("string"))},
				}},
			})
			m.Own(keyed("LineItem", []*ir.Field{
				irtest.Field("order", m.Named("string")),
				irtest.Field("sku", m.Named("string")),
			}, irtest.Name("order"), irtest.Name("sku")))
		}, "line_item.go"},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			m := irtest.New("shop")
			c.build(m)

			resp := generate(t, m)
			if len(resp.GetDiagnostics()) != 1 {
				t.Fatalf("diagnostics = %+v", resp.GetDiagnostics())
			}
			d := resp.GetDiagnostics()[0]
			if d.GetSeverity() != plugin.Severity_SEVERITY_WARNING {
				t.Errorf("severity = %v", d.GetSeverity())
			}
			if d.GetPosition().GetLine() != keyLine {
				t.Errorf("position = %+v, and the directive is what to point at", d.GetPosition())
			}

			got := files(t, resp)
			src, ok := got[c.file]
			if !ok {
				t.Fatalf("the entity was skipped along with its key: %v", keys(got))
			}
			if strings.Contains(src, "Key()") {
				t.Errorf("a key that warned was generated anyway:\n%s", src)
			}
		})
	}
}

// A model carries directives for every target block, and another backend's
// key is not this one's.
func TestKeyFromAnotherTargetIsIgnored(t *testing.T) {
	m := irtest.New("shop")
	d := keyed("User", []*ir.Field{irtest.Field("id", m.Named("string"))}, irtest.Name("id"))
	d.Directives[0].Target = "sql"
	m.Own(d)

	resp := generate(t, m)
	if len(resp.GetDiagnostics()) != 0 {
		t.Errorf("diagnostics = %+v", resp.GetDiagnostics())
	}
	if src := files(t, resp)["user.go"]; strings.Contains(src, "Key()") {
		t.Errorf("another target's key was generated:\n%s", src)
	}
}

// The receiver is derived from the Go name, and `irtest.Name("")` passes the
// compiler's checks, so an empty name has to be a warning rather than an
// index out of range.
func TestKeyOnAnEmptyNameIsAWarning(t *testing.T) {
	m := irtest.New("shop")
	d := keyed("User", []*ir.Field{irtest.Field("id", m.Named("string"))}, irtest.Name("id"))
	d.Directives = append(d.Directives, &ir.Directive{Name: "name", Target: "go", Args: []*ir.Literal{irtest.Text("")}})
	m.Own(d)

	resp := generate(t, m)
	for _, diag := range resp.GetDiagnostics() {
		if diag.GetSeverity() == plugin.Severity_SEVERITY_WARNING && diag.GetPosition().GetLine() == keyLine {
			return
		}
	}
	t.Errorf("no warning at the key directive: %+v", resp.GetDiagnostics())
}

// keyLine is where [keyed] says its directive was written.
const keyLine = 9

// keyed is an entity carrying a key directive for the go target.
func keyed(declName string, fields []*ir.Field, args ...*ir.Literal) *ir.Decl {
	return &ir.Decl{
		Meta: &ir.Meta{Name: declName},
		Directives: []*ir.Directive{{
			Name:     "key",
			Target:   "go",
			Args:     args,
			Position: &ir.Position{Filename: irtest.OwnFile, Line: keyLine},
		}},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{
			Kind:   ir.StructKind_STRUCT_KIND_ENTITY,
			Fields: fields,
		}},
	}
}

func keys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}

// structure is a value declaration, parameterized when ps is not empty.
func structure(declName string, ps []*ir.Param, fields ...*ir.Field) *ir.Decl {
	return &ir.Decl{
		Meta: &ir.Meta{Name: declName},
		Node: &ir.Decl_Structure{Structure: &ir.Struct{Params: ps, Fields: fields}},
	}
}

func noDiagnostics(t *testing.T, resp *plugin.Response) {
	t.Helper()
	if len(resp.GetDiagnostics()) != 0 {
		t.Fatalf("diagnostics = %+v", resp.GetDiagnostics())
	}
}

// onlyWarningAt asserts the response carries one diagnostic, a warning, at
// line; a line of 0 is a use the fixture gave no position.
func onlyWarningAt(t *testing.T, resp *plugin.Response, line int32) {
	t.Helper()
	if len(resp.GetDiagnostics()) != 1 {
		t.Fatalf("diagnostics = %+v", resp.GetDiagnostics())
	}
	d := resp.GetDiagnostics()[0]
	if d.GetSeverity() != plugin.Severity_SEVERITY_WARNING {
		t.Errorf("severity = %v", d.GetSeverity())
	}
	if line != 0 && d.GetPosition().GetLine() != line {
		t.Errorf("position = %+v, want line %d", d.GetPosition(), line)
	}
}

// A parameterized declaration is a Go generic type, and applying it is
// instantiating one.
func TestGenericStruct(t *testing.T) {
	m := irtest.New("shop")
	m.Own(structure("Page", irtest.Params("T"),
		irtest.Field("items", m.Named("List", m.Param("T", 0))),
		irtest.Field("next", m.Named("Option", m.Param("T", 0))),
	))
	m.Own(structure("Order", nil, irtest.Field("id", m.Named("string"))))
	m.Own(structure("Orders", nil,
		irtest.Field("page", m.Named("Page", m.Named("Order"))),
		irtest.Field("byName", m.Named("Map", m.Named("string"), m.Named("Page", m.Named("int")))),
	))

	resp := generate(t, m)
	noDiagnostics(t, resp)
	got := files(t, resp)
	contains(t, got["page.go"], "type Page[T any] struct {", "Items []T", "Next *T")
	contains(t, got["orders.go"], "Page Page[Order]", "ByName map[string]Page[int64]")
}

// A sealed enum's marker method takes the enum's parameters, so a variant of
// one instantiation does not satisfy another.
func TestGenericSealedEnum(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Result"},
		Node: &ir.Decl_Enumeration{Enumeration: &ir.Enum{
			Params: irtest.Params("T"),
			Variants: []*ir.Variant{
				{Meta: &ir.Meta{Name: "Ok"}, Fields: []*ir.Field{irtest.Field("value", m.Param("T", 0))}},
				{Meta: &ir.Meta{Name: "Err"}, Fields: []*ir.Field{irtest.Field("message", m.Named("string"))}},
			},
		}},
	})
	m.Own(structure("Reply", nil, irtest.Field("result", m.Named("Result", m.Named("string")))))

	resp := generate(t, m)
	noDiagnostics(t, resp)
	got := files(t, resp)
	contains(t, got["result.go"],
		"type Result[T any] interface{ isResult(T) }",
		"type ResultOk[T any] struct {",
		"Value T",
		"func (ResultOk[T]) isResult(T) {}",
		"type ResultErr[T any] struct {",
		"func (ResultErr[T]) isResult(T) {}",
	)
	contains(t, got["reply.go"], "Result Result[string]")
}

func TestGenericNewtype(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Ids"},
		Node: &ir.Decl_Newtype{Newtype: &ir.Newtype{Params: irtest.Params("T"), Base: m.Named("List", m.Param("T", 0))}},
	})
	m.Own(structure("User", nil, irtest.Field("friends", m.Named("Ids", m.Named("string")))))

	resp := generate(t, m)
	noDiagnostics(t, resp)
	got := files(t, resp)
	contains(t, got["ids.go"], "type Ids[T any] []T")
	contains(t, got["user.go"], "Friends Ids[string]")
}

// Go refuses a type parameter as the whole right-hand side of a type
// declaration, so a newtype over a bare parameter has no Go shape.
func TestNewtypeOverABareParameterIsAWarning(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Tagged", Position: &ir.Position{Filename: irtest.OwnFile, Line: 3}},
		Node: &ir.Decl_Newtype{Newtype: &ir.Newtype{Params: irtest.Params("T"), Base: m.Param("T", 0)}},
	})
	m.Own(structure("Note", nil, irtest.Field("body", m.Named("string"))))

	resp := generate(t, m)
	onlyWarningAt(t, resp, 3)
	if src, ok := files(t, resp)["tagged.go"]; ok {
		t.Errorf("a newtype over a bare parameter was emitted:\n%s", src)
	}
}

// A fieldless enum is constants, and a constant cannot have a generic type,
// so its parameters are dropped with a warning rather than changing the
// enum's shape.
func TestParameterizedFieldlessEnumDropsItsParams(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Status", Position: &ir.Position{Filename: irtest.OwnFile, Line: 3}},
		Node: &ir.Decl_Enumeration{Enumeration: &ir.Enum{
			Params:   irtest.Params("T"),
			Variants: []*ir.Variant{{Meta: &ir.Meta{Name: "Active"}}, {Meta: &ir.Meta{Name: "Pending"}}},
		}},
	})
	m.Own(structure("Job", nil, irtest.Field("status", m.Named("Status", m.Named("int")))))

	resp := generate(t, m)
	onlyWarningAt(t, resp, 3)
	got := files(t, resp)
	contains(t, got["status.go"], "type Status string", `StatusActive Status = "Active"`)
	contains(t, got["job.go"], "Status Status")
}

// An alias is expanded at every use, so a parameterized one is expanded with
// its arguments substituted for its parameters.
func TestParameterizedAliasIsSubstituted(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Pair"},
		Node: &ir.Decl_Alias{Alias: &ir.Alias{
			Params: irtest.Params("K", "V"),
			Target: m.Named("Map", m.Param("K", 0), m.Param("V", 1)),
		}},
	})
	// An alias of an alias, applying the inner one to its own parameter.
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "ByName"},
		Node: &ir.Decl_Alias{Alias: &ir.Alias{
			Params: irtest.Params("V"),
			Target: m.Named("Pair", m.Named("string"), m.Param("V", 0)),
		}},
	})
	m.Own(structure("Wrap", irtest.Params("T"),
		irtest.Field("direct", m.Named("Pair", m.Named("string"), m.Named("bool"))),
		irtest.Field("nested", m.Named("ByName", m.Named("int"))),
		irtest.Field("generic", m.Named("Pair", m.Named("string"), m.Param("T", 0))),
	))

	resp := generate(t, m)
	noDiagnostics(t, resp)
	got := files(t, resp)
	if _, ok := got["pair.go"]; ok {
		t.Error("an alias should not generate a declaration")
	}
	contains(t, got["wrap.go"],
		"Direct map[string]bool",
		"Nested map[string]int64",
		"Generic map[string]T",
	)
}

func TestAliasGivenTheWrongNumberOfArgumentsIsAWarning(t *testing.T) {
	m := irtest.New("shop")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Pair"},
		Node: &ir.Decl_Alias{Alias: &ir.Alias{
			Params: irtest.Params("K", "V"),
			Target: m.Named("Map", m.Param("K", 0), m.Param("V", 1)),
		}},
	})
	m.Own(structure("Bad", nil, irtest.Field("pair", m.Named("Pair", m.Named("string")))))

	resp := generate(t, m)
	onlyWarningAt(t, resp, 0)
	if src, ok := files(t, resp)["bad.go"]; ok {
		t.Errorf("a declaration with a misapplied alias was emitted:\n%s", src)
	}
}

// A parameter Go cannot express is a warning at the parameter, and the
// declaration taking it is skipped.
func TestParamsGoCannotExpress(t *testing.T) {
	atom := func(a ir.KindAtom) *ir.Kind { return &ir.Kind{Atom: a} }
	arrow := &ir.Kind{Atom: ir.KindAtom_KIND_ATOM_TYPE, Arrow: atom(ir.KindAtom_KIND_ATOM_TYPE)}
	at := &ir.Position{Filename: irtest.OwnFile, Line: 4}

	cases := []struct {
		name  string
		param *ir.Param
		body  func(m *irtest.Builder) *ir.ID
		line  int32
	}{
		{"a higher kind", &ir.Param{Name: "f", Kind: arrow, Position: at}, nil, 4},
		{"a parenthesized higher kind", &ir.Param{Name: "f", Kind: &ir.Kind{Paren: arrow}, Position: at}, nil, 4},
		{"a unit", &ir.Param{Name: "u", Kind: atom(ir.KindAtom_KIND_ATOM_UNIT), Position: at}, nil, 4},
		{"a Go keyword", &ir.Param{Name: "range", Position: at}, nil, 4},
		{"a predeclared type", &ir.Param{Name: "string", Position: at}, nil, 4},
		{"a predeclared constraint", &ir.Param{Name: "any", Position: at}, nil, 4},
		{"the time package", &ir.Param{Name: "time", Position: at}, nil, 4},
		{"a generated declaration", &ir.Param{Name: "Note", Position: at}, nil, 4},
		// The kind is left to inference, and only the use says it is higher.
		{"applied to arguments", &ir.Param{Name: "f"}, func(m *irtest.Builder) *ir.ID {
			return m.Param("f", 0, m.Named("string"))
		}, 0},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			m := irtest.New("shop")
			m.Own(structure("Note", nil, irtest.Field("body", m.Named("string"))))
			body := m.Named("string")
			if c.body != nil {
				body = c.body(m)
			}
			m.Own(structure("Box", []*ir.Param{c.param}, irtest.Field("value", body)))

			resp := generate(t, m)
			onlyWarningAt(t, resp, c.line)
			got := files(t, resp)
			if src, ok := got["box.go"]; ok {
				t.Errorf("a declaration taking %s was emitted:\n%s", c.name, src)
			}
			if _, ok := got["note.go"]; !ok {
				t.Errorf("the rest of the model was not generated: %v", keys(got))
			}
		})
	}
}

// Go needs a map key to be comparable and TDL has no way to say so, so a
// parameter is constrained by what reaches a key.
func TestComparableIsInferred(t *testing.T) {
	m := irtest.New("shop")
	m.Own(structure("Bag", irtest.Params("T"), irtest.Field("items", m.Named("Set", m.Param("T", 0)))))
	m.Own(structure("Index", irtest.Params("K", "V"), irtest.Field("by", m.Named("Map", m.Param("K", 0), m.Param("V", 1)))))
	m.Own(structure("Shelf", irtest.Params("T"), irtest.Field("bag", m.Named("Bag", m.Param("T", 0)))))
	m.Own(structure("Pair", irtest.Params("X"), irtest.Field("x", m.Param("X", 0))))
	m.Own(structure("Pairs", irtest.Params("T"), irtest.Field("seen", m.Named("Set", m.Named("Pair", m.Param("T", 0))))))
	// A pointer is comparable whatever it points at.
	m.Own(structure("Maybe", irtest.Params("T"), irtest.Field("seen", m.Named("Set", m.Named("Option", m.Param("T", 0))))))
	// Declared before what makes it comparable, so one pass in declaration
	// order is not enough. Its field is attached once Late exists.
	early := &ir.Struct{Params: irtest.Params("T")}
	m.Own(&ir.Decl{Meta: &ir.Meta{Name: "Early"}, Node: &ir.Decl_Structure{Structure: early}})
	m.Own(structure("Late", irtest.Params("T"), irtest.Field("items", m.Named("Set", m.Param("T", 0)))))
	early.Fields = []*ir.Field{irtest.Field("late", m.Named("Late", m.Param("T", 0)))}
	m.Own(structure("Uses", nil, irtest.Field("bag", m.Named("Bag", m.Named("string")))))

	resp := generate(t, m)
	noDiagnostics(t, resp)
	got := files(t, resp)
	contains(t, got["bag.go"], "type Bag[T comparable] struct {", "Items map[T]struct{}")
	contains(t, got["index.go"], "type Index[K comparable, V any] struct {")
	contains(t, got["shelf.go"], "type Shelf[T comparable] struct {", "Bag Bag[T]")
	contains(t, got["pair.go"], "type Pair[X any] struct {")
	contains(t, got["pairs.go"], "type Pairs[T comparable] struct {", "Seen map[Pair[T]]struct{}")
	contains(t, got["maybe.go"], "type Maybe[T any] struct {", "Seen map[*T]struct{}")
	contains(t, got["early.go"], "type Early[T comparable] struct {")
	contains(t, got["uses.go"], "Bag Bag[string]")
}

// An argument Go cannot compare, given to a parameter that has to be, is a
// warning at the use, and the declaration using it is skipped.
func TestComparableArgumentsAtUse(t *testing.T) {
	m := irtest.New("shop")
	m.Own(structure("Bag", irtest.Params("T"), irtest.Field("items", m.Named("Set", m.Param("T", 0)))))
	m.Own(structure("Path", nil, irtest.Field("segments", m.Named("List", m.Named("string")))))
	m.Own(structure("Blobs", nil, irtest.Field("bag", m.Named("Bag", m.Named("bytes")))))
	m.Own(structure("Paths", nil, irtest.Field("bag", m.Named("Bag", m.Named("Path")))))
	m.Own(structure("Names", nil, irtest.Field("bag", m.Named("Bag", m.Named("string")))))

	resp := generate(t, m)
	if len(resp.GetDiagnostics()) != 2 {
		t.Fatalf("diagnostics = %+v", resp.GetDiagnostics())
	}
	got := files(t, resp)
	for _, skipped := range []string{"blobs.go", "paths.go"} {
		if src, ok := got[skipped]; ok {
			t.Errorf("%s gives an incomparable argument and was emitted:\n%s", skipped, src)
		}
	}
	contains(t, got["names.go"], "Bag Bag[string]")
}

// A generic entity's key is generic too, and a key field has to be
// comparable, so the parameter it names is.
func TestGenericEntityKey(t *testing.T) {
	m := irtest.New("shop")
	entry := keyed("Entry", []*ir.Field{
		irtest.Field("id", m.Param("T", 0)),
		irtest.Field("note", m.Named("string")),
	}, irtest.Name("id"))
	entry.GetStructure().Params = irtest.Params("T")
	m.Own(entry)

	item := keyed("LineItem", []*ir.Field{
		irtest.Field("order", m.Param("T", 0)),
		irtest.Field("sku", m.Named("string")),
	}, irtest.Name("order"), irtest.Name("sku"))
	item.GetStructure().Params = irtest.Params("T")
	m.Own(item)

	// A parameter spelled like the receiver would be redeclared by it.
	edge := keyed("Edge", []*ir.Field{irtest.Field("id", m.Param("e", 0))}, irtest.Name("id"))
	edge.GetStructure().Params = irtest.Params("e")
	m.Own(edge)

	resp := generate(t, m)
	noDiagnostics(t, resp)
	got := files(t, resp)
	contains(t, got["entry.go"],
		"type Entry[T comparable] struct {",
		"func (e Entry[T]) Key() T {",
		"return e.Id",
	)
	contains(t, got["line_item.go"],
		"type LineItemKey[T comparable] struct {",
		"func (l LineItem[T]) Key() LineItemKey[T] {",
		"return LineItemKey[T]{Order: l.Order, Sku: l.Sku}",
	)
	contains(t, got["edge.go"], "func (r Edge[e]) Key() e {", "return r.Id")
}

// A class is a contract, and conformance to it is declared, so it is an
// interface only the declarations that said so implement: its method is
// unexported, which seals it to the package.
func TestClassIsAMarkerInterface(t *testing.T) {
	m := irtest.New("shop")
	m.Class("Timestamped")
	m.Class("Auditable", "Timestamped")
	m.Own(structure("Order", nil, irtest.Field("id", m.Named("string"))))
	m.Satisfies("Timestamped", "Order")
	m.Satisfies("Auditable", "Order")

	resp := generate(t, m)
	noDiagnostics(t, resp)
	got := files(t, resp)
	contains(t, got["timestamped.go"], "type Timestamped interface { isTimestamped() }")
	contains(t, got["auditable.go"], "type Auditable interface { Timestamped isAuditable() }")
	contains(t, got["order.go"], "func (Order) isTimestamped() {}", "func (Order) isAuditable() {}")
}

func TestMarkersOnEveryShape(t *testing.T) {
	m := irtest.New("shop")
	m.Class("Auditable")
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Status"},
		Node: &ir.Decl_Enumeration{Enumeration: &ir.Enum{
			Variants: []*ir.Variant{{Meta: &ir.Meta{Name: "Active"}}},
		}},
	})
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Payment"},
		Node: &ir.Decl_Enumeration{Enumeration: &ir.Enum{
			Variants: []*ir.Variant{
				{Meta: &ir.Meta{Name: "Cash"}},
				{Meta: &ir.Meta{Name: "Card"}, Fields: []*ir.Field{irtest.Field("last4", m.Named("string"))}},
			},
		}},
	})
	m.Own(&ir.Decl{
		Meta: &ir.Meta{Name: "Sku"},
		Node: &ir.Decl_Newtype{Newtype: &ir.Newtype{Base: m.Named("string")}},
	})
	m.Own(structure("Page", irtest.Params("T"), irtest.Field("items", m.Named("List", m.Param("T", 0)))))
	m.Satisfies("Auditable", "Status", "Payment", "Sku", "Page")

	resp := generate(t, m)
	noDiagnostics(t, resp)
	got := files(t, resp)
	contains(t, got["status.go"], "func (Status) isAuditable() {}")
	// A sealed enum is an interface, which cannot carry a method, so it
	// embeds the class and every variant carries the marker.
	contains(t, got["payment.go"],
		"type Payment interface { Auditable isPayment() }",
		"func (PaymentCash) isAuditable() {}",
		"func (PaymentCard) isAuditable() {}",
	)
	contains(t, got["sku.go"], "func (Sku) isAuditable() {}")
	contains(t, got["page.go"], "func (Page[T]) isAuditable() {}")
}

// A `requires` clause is a Go constraint, since the class it names is an
// interface, and a parameter that also has to be comparable says both.
func TestRequiresBecomesAConstraint(t *testing.T) {
	m := irtest.New("shop")
	m.Class("Timestamped")
	m.Class("Auditable", "Timestamped")
	m.Own(structure("Order", nil, irtest.Field("id", m.Named("string"))))
	m.Satisfies("Timestamped", "Order")
	m.Satisfies("Auditable", "Order")

	envelope := structure("Envelope", irtest.Params("T"), irtest.Field("body", m.Param("T", 0)))
	envelope.GetStructure().Constraints = []*ir.ClassRef{m.Requires("Auditable", 0, m.Param("T", 0))}
	m.Own(envelope)
	stamped := structure("Stamped", irtest.Params("T"), irtest.Field("body", m.Param("T", 0)))
	stamped.GetStructure().Constraints = []*ir.ClassRef{m.Requires("Timestamped", 0, m.Param("T", 0))}
	m.Own(stamped)
	tracked := structure("Tracked", irtest.Params("T"), irtest.Field("seen", m.Named("Set", m.Param("T", 0))))
	tracked.GetStructure().Constraints = []*ir.ClassRef{m.Requires("Auditable", 0, m.Param("T", 0))}
	m.Own(tracked)
	// Auditable requires Timestamped, so a parameter that is Auditable
	// satisfies a constraint naming either.
	forward := structure("Forward", irtest.Params("T"),
		irtest.Field("envelope", m.Named("Envelope", m.Param("T", 0))),
		irtest.Field("stamped", m.Named("Stamped", m.Param("T", 0))),
	)
	forward.GetStructure().Constraints = []*ir.ClassRef{m.Requires("Auditable", 0, m.Param("T", 0))}
	m.Own(forward)
	m.Own(structure("Uses", nil,
		irtest.Field("envelope", m.Named("Envelope", m.Named("Order"))),
		irtest.Field("stamped", m.Named("Stamped", m.Named("Order"))),
		irtest.Field("tracked", m.Named("Tracked", m.Named("Order"))),
	))

	resp := generate(t, m)
	noDiagnostics(t, resp)
	got := files(t, resp)
	contains(t, got["envelope.go"], "type Envelope[T Auditable] struct {")
	contains(t, got["stamped.go"], "type Stamped[T Timestamped] struct {")
	// gofmt spreads an interface of several elements over lines.
	contains(t, got["tracked.go"], "type Tracked[T interface { comparable Auditable }] struct {")
	contains(t, got["forward.go"], "type Forward[T Auditable] struct {")
	contains(t, got["uses.go"], "Envelope Envelope[Order]", "Tracked Tracked[Order]")
}

// The compiler does not check a constraint whose argument is a parameter,
// and Go does, so the backend checks every use and skips what Go would
// refuse.
func TestConstraintViolatedAtUse(t *testing.T) {
	m := irtest.New("shop")
	m.Class("Auditable")
	m.Own(structure("Order", nil, irtest.Field("id", m.Named("string"))))
	m.Satisfies("Auditable", "Order")
	envelope := structure("Envelope", irtest.Params("T"), irtest.Field("body", m.Param("T", 0)))
	envelope.GetStructure().Constraints = []*ir.ClassRef{m.Requires("Auditable", 0, m.Param("T", 0))}
	m.Own(envelope)

	m.Own(structure("Strings", nil, irtest.Field("envelope", m.Named("Envelope", m.Named("string")))))
	m.Own(structure("Outer", irtest.Params("T"), irtest.Field("envelope", m.Named("Envelope", m.Param("T", 0)))))
	m.Own(structure("Good", nil, irtest.Field("envelope", m.Named("Envelope", m.Named("Order")))))

	resp := generate(t, m)
	if len(resp.GetDiagnostics()) != 2 {
		t.Fatalf("diagnostics = %+v", resp.GetDiagnostics())
	}
	got := files(t, resp)
	for _, skipped := range []string{"strings.go", "outer.go"} {
		if src, ok := got[skipped]; ok {
			t.Errorf("%s breaks a constraint and was emitted:\n%s", skipped, src)
		}
	}
	contains(t, got["good.go"], "Envelope Envelope[Order]")
}

// What Go cannot express about a class is a warning where it was written,
// and the rest is generated without it.
func TestClassesGoCannotExpress(t *testing.T) {
	at := &ir.Position{Filename: irtest.OwnFile, Line: 4}
	instance := func(m *irtest.Builder, arg *ir.ID) *ir.Instance {
		return &ir.Instance{
			Meta:  &ir.Meta{Position: at},
			Class: &ir.ClassRef{Class: m.Ref("Auditable"), Args: []*ir.ID{arg}},
		}
	}

	cases := []struct {
		name string
		// build returns the file expected, and what must not be in it.
		build func(m *irtest.Builder) (file, absent string)
	}{
		{"a class taking parameters", func(m *irtest.Builder) (string, string) {
			d := m.Class("Projection")
			d.GetMeta().Position = at
			d.GetClass().Params = irtest.Params("from", "to")
			return "", "projection.go"
		}},
		{"a class with an associated type", func(m *irtest.Builder) (string, string) {
			d := m.Class("Paged")
			d.GetMeta().Position = at
			d.GetClass().AssocTypes = []*ir.AssocType{{Meta: &ir.Meta{Name: "Cursor"}}}
			return "paged.go", ""
		}},
		{"a conditional instance", func(m *irtest.Builder) (string, string) {
			m.Class("Auditable")
			m.Own(structure("Page", irtest.Params("T"), irtest.Field("items", m.Named("List", m.Param("T", 0)))))
			inst := instance(m, m.Named("Page", m.Param("T", 0)))
			inst.Params = irtest.Params("T")
			inst.Requires = []*ir.ClassRef{{Class: m.Ref("Auditable"), Args: []*ir.ID{m.Param("T", 0)}}}
			m.Model.Instances = append(m.Model.Instances, inst)
			return "page.go", "isAuditable"
		}},
		{"an instance for a prelude type", func(m *irtest.Builder) (string, string) {
			m.Class("Auditable")
			m.Model.Instances = append(m.Model.Instances, instance(m, m.Named("string")))
			return "auditable.go", "func (string)"
		}},
		{"an instance for a type in another package", func(m *irtest.Builder) (string, string) {
			m.Class("Auditable")
			m.Model.Instances = append(m.Model.Instances, instance(m, m.Extern("acme.Money")))
			return "auditable.go", "Money"
		}},
		{"a newtype over a pointer", func(m *irtest.Builder) (string, string) {
			m.Class("Auditable")
			m.Own(&ir.Decl{
				Meta: &ir.Meta{Name: "Maybe", Position: at},
				Node: &ir.Decl_Newtype{Newtype: &ir.Newtype{Base: m.Named("Option", m.Named("string"))}},
			})
			m.Satisfies("Auditable", "Maybe")
			return "maybe.go", "isAuditable"
		}},
		{"a newtype over a sealed enum", func(m *irtest.Builder) (string, string) {
			m.Class("Auditable")
			m.Own(&ir.Decl{
				Meta: &ir.Meta{Name: "Payment"},
				Node: &ir.Decl_Enumeration{Enumeration: &ir.Enum{
					Variants: []*ir.Variant{{Meta: &ir.Meta{Name: "Card"}, Fields: []*ir.Field{irtest.Field("last4", m.Named("string"))}}},
				}},
			})
			m.Own(&ir.Decl{
				Meta: &ir.Meta{Name: "Tender", Position: at},
				Node: &ir.Decl_Newtype{Newtype: &ir.Newtype{Base: m.Named("Payment")}},
			})
			m.Satisfies("Auditable", "Tender")
			return "tender.go", "isAuditable"
		}},
		{"a field named like the marker", func(m *irtest.Builder) (string, string) {
			m.Class("Auditable")
			note := structure("Note", nil, &ir.Field{
				Meta:       &ir.Meta{Name: "audit"},
				Type:       m.Named("string"),
				Directives: []*ir.Directive{{Name: "name", Target: "go", Args: []*ir.Literal{irtest.Text("isAuditable")}}},
			})
			note.GetMeta().Position = at
			m.Own(note)
			m.Satisfies("Auditable", "Note")
			return "note.go", "func (Note)"
		}},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			m := irtest.New("shop")
			file, absent := c.build(m)

			resp := generate(t, m)
			onlyWarningAt(t, resp, 4)
			got := files(t, resp)
			if file != "" {
				src, ok := got[file]
				if !ok {
					t.Fatalf("no %s in %v", file, keys(got))
				}
				if absent != "" && strings.Contains(src, absent) {
					t.Errorf("%s holds %q:\n%s", file, absent, src)
				}
			} else if _, ok := got[absent]; ok {
				t.Errorf("%s was emitted: %v", absent, keys(got))
			}
		})
	}
}

// A `requires` clause Go cannot state is a warning at the clause, and the
// declaration is emitted without that constraint, as it is without an
// unenforced `where`.
func TestUnexpressibleRequiresIsDropped(t *testing.T) {
	cases := []struct {
		name  string
		ref   func(m *irtest.Builder) *ir.ClassRef
		diags int
	}{
		{"a prelude class", func(m *irtest.Builder) *ir.ClassRef {
			return m.Requires("Entity", 4, m.Param("T", 0))
		}, 1},
		// The class warns where it is declared, and the clause where it is
		// written.
		{"a class taking parameters", func(m *irtest.Builder) *ir.ClassRef {
			d := m.Class("Projection")
			d.GetMeta().Position = &ir.Position{Filename: irtest.OwnFile, Line: 2}
			d.GetClass().Params = irtest.Params("from", "to")
			return m.Requires("Projection", 4, m.Param("T", 0), m.Named("string"))
		}, 2},
		{"an argument that is not a parameter", func(m *irtest.Builder) *ir.ClassRef {
			m.Class("Auditable")
			return m.Requires("Auditable", 4, m.Named("List", m.Param("T", 0)))
		}, 1},
		{"a class in another package", func(m *irtest.Builder) *ir.ClassRef {
			return &ir.ClassRef{
				Extern:   &ir.ID{Name: "acme.Auditable"},
				Args:     []*ir.ID{m.Param("T", 0)},
				Position: &ir.Position{Filename: irtest.OwnFile, Line: 4},
			}
		}, 1},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			m := irtest.New("shop")
			ref := c.ref(m)
			envelope := structure("Envelope", irtest.Params("T"), irtest.Field("body", m.Param("T", 0)))
			envelope.GetStructure().Constraints = []*ir.ClassRef{ref}
			m.Own(envelope)

			resp := generate(t, m)
			if len(resp.GetDiagnostics()) != c.diags {
				t.Fatalf("diagnostics = %+v", resp.GetDiagnostics())
			}
			atClause := false
			for _, d := range resp.GetDiagnostics() {
				atClause = atClause || d.GetPosition().GetLine() == 4
			}
			if !atClause {
				t.Errorf("no warning at the clause: %+v", resp.GetDiagnostics())
			}
			contains(t, files(t, resp)["envelope.go"], "type Envelope[T any] struct {")
		})
	}
}

// A class a class requires is embedded in its interface, which is what makes
// the requirement hold. One Go cannot embed is dropped, so the interface is
// weaker than the model says, and that is a warning at the clause rather
// than a quieter interface.
func TestUnembeddableSuperIsAWarning(t *testing.T) {
	cases := []struct {
		name  string
		ref   func(m *irtest.Builder) *ir.ClassRef
		diags int
		// absent is the name the interface must not embed.
		absent string
	}{
		{"a prelude class", func(m *irtest.Builder) *ir.ClassRef {
			return m.Requires("Entity", 4)
		}, 1, "Entity"},
		// The class warns where it is declared, and the clause where it is
		// written.
		{"a class taking parameters", func(m *irtest.Builder) *ir.ClassRef {
			d := m.Class("Projection")
			d.GetMeta().Position = &ir.Position{Filename: irtest.OwnFile, Line: 2}
			d.GetClass().Params = irtest.Params("from", "to")
			return m.Requires("Projection", 4)
		}, 2, "Projection"},
		{"a class in another package", func(m *irtest.Builder) *ir.ClassRef {
			return &ir.ClassRef{
				Extern:   &ir.ID{Name: "acme.Auditable"},
				Position: &ir.Position{Filename: irtest.OwnFile, Line: 4},
			}
		}, 1, "Auditable"},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			m := irtest.New("shop")
			ref := c.ref(m)
			timestamped := m.Class("Timestamped")
			timestamped.GetClass().RequiresClasses = []*ir.ClassRef{ref}

			resp := generate(t, m)
			if len(resp.GetDiagnostics()) != c.diags {
				t.Fatalf("diagnostics = %+v", resp.GetDiagnostics())
			}
			atClause := false
			for _, d := range resp.GetDiagnostics() {
				atClause = atClause || d.GetPosition().GetLine() == 4
			}
			if !atClause {
				t.Errorf("no warning at the clause: %+v", resp.GetDiagnostics())
			}

			src := files(t, resp)["timestamped.go"]
			contains(t, src, "type Timestamped interface")
			if strings.Contains(src, c.absent) {
				t.Errorf("the interface embeds %s:\n%s", c.absent, src)
			}
		})
	}
}

// Nothing rejects a cycle in what classes require, and a Go interface cannot
// embed itself, so each class in the cycle is dropped with a warning rather
// than generated into a package that does not compile.
func TestClassRequiresCycle(t *testing.T) {
	at := &ir.Position{Filename: irtest.OwnFile, Line: 4}
	m := irtest.New("shop")
	auditable := m.Class("Auditable")
	auditable.GetMeta().Position = at
	timestamped := m.Class("Timestamped", "Auditable")
	timestamped.GetMeta().Position = at
	auditable.GetClass().RequiresClasses = []*ir.ClassRef{{Class: m.Ref("Timestamped")}}

	m.Own(structure("Order", nil, irtest.Field("id", m.Named("string"))))
	m.Satisfies("Auditable", "Order")
	m.Satisfies("Timestamped", "Order")

	envelope := structure("Envelope", irtest.Params("T"), irtest.Field("body", m.Param("T", 0)))
	envelope.GetStructure().Constraints = []*ir.ClassRef{m.Requires("Auditable", 4, m.Param("T", 0))}
	m.Own(envelope)
	m.Own(structure("Uses", nil, irtest.Field("envelope", m.Named("Envelope", m.Named("Order")))))

	resp := generate(t, m)
	for _, d := range resp.GetDiagnostics() {
		if d.GetSeverity() != plugin.Severity_SEVERITY_WARNING {
			t.Errorf("diagnostic = %+v, want a warning", d)
		}
	}
	got := files(t, resp)
	for _, dropped := range []string{"auditable.go", "timestamped.go"} {
		if src, ok := got[dropped]; ok {
			t.Errorf("%s is in a class cycle and was emitted:\n%s", dropped, src)
		}
	}
	contains(t, got["envelope.go"], "type Envelope[T any] struct {")
	contains(t, got["uses.go"], "Envelope Envelope[Order]")
}
