name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          cache-dependency-path: go.sum
          go-version-file: go.mod

      - run: go build ./...
      - run: go vet ./...
      - run: go test ./...

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          cache-dependency-path: go.sum
          go-version-file: go.mod

      - uses: golangci/golangci-lint-action@v6

  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DavidAnson/markdownlint-cli2-action@v19
