name: CI

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - .idea
      - .vscode
      - .editorconfig
      - .gitignore
      - LICENSE
      - README.md

jobs:
  build:
    name: Build the thing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: make build
      # - run: make test

  goreleaser:
    name: GoReleaser Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: check

  bun:
    name: Bun Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - run: bun install --frozen-lockfile

  md-lint:
    if: false
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - run: bun install --frozen-lockfile
      - run: bun lint:md
