name: cli/um

on:
  pull_request:
    branches: ['main']
    paths:
      - .github/actions/build-go/**
      - .github/workflows/go-cli.yml
      - .github/workflows/cli-um.yml
      - cli/go.*
      - cli/um/**
      - cli/internal/**
      - e2e/**
  push:
    branches: ['main']
    tags: ['v*.*.*']
    paths:
      - .github/actions/build-go/**
      - .github/workflows/go-cli.yml
      - .github/workflows/cli-um.yml
      - cli/go.*
      - cli/um/**
      - cli/internal/**

jobs:
  build:
    name: Go CLI Build
    uses: ./.github/workflows/go-cli.yml
    with:
      name: um

  e2e:
    name: End-to-end Tests
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1
        with:
          version: latest
          github_token: ${{ github.token }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.2'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.15

      - name: Bun install
        run: bun install --frozen-lockfile

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Run end-to-end tests
        run: make e2e
