name: um CLI

on:
  pull_request:
    branches: ['main']
    paths:
      - .github/actions/build-go/**
      - .github/workflows/go-cli.yml
      - .github/workflows/cli-um.yml
      - cli/go.*
      - cli/um/**
      - cli/internal/**
  push:
    branches: ['main']
    tags: ['v*.*.*']
    paths:
      - .github/actions/build-go/**
      - .github/workflows/go-cli.yml
      - .github/workflows/cli-um.yml
      - cli/go.*
      - cli/um/**
      - cli/internal/**

jobs:
  build:
    uses: ./.github/workflows/go-cli.yml
    with:
      name: um
