name: uml2ts package

on:
  pull_request:
    branches: ['main']
    paths:
      - .github/actions/build-bun/**
      - .github/actions/build-docker/**
      - .github/workflows/packages-uml2ts.yml
      - packages/uml2ts/**
  push:
    branches: ['main']
    tags: ['v*.*.*']
    paths:
      - .github/actions/build-cs/**
      - .github/actions/build-docker/**
      - .github/workflows/packages-uml2ts.yml
      - packages/uml2ts/**

jobs:
  build:
    uses: ./.github/workflows/ts/cli.yml
    with:
      name: uml2ts
      docker: true
