name: Packages

on:
  pull_request:
    branches: [main]
    paths:
      - .github/actions/**
      - .github/workflows/packages.yml
      - packages/**
      - pkg/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build-bun
        with:
          path: packages/ts
