name: packages/ts

on:
  pull_request:
    branches: ['main']
    paths:
      - .github/actions/build-bun/**
      - .github/workflows/bun-cli.yml
      - .github/workflows/packages-ts.yml
      - packages/ts/**

jobs:
  build:
    uses: ./.github/workflows/bun-cli.yml
    with:
      name: ts
