name: uml package

on:
  pull_request:
    branches: ['main']
    paths:
      - .github/actions/build-bun/**
      - .github/actions/build-docker/**
      - .github/workflows/packages-uml.yml
      - packages/uml/**
  push:
    branches: ['main']
    tags: ['v*.*.*']
    paths:
      - .github/actions/build-cs/**
      - .github/actions/build-docker/**
      - .github/workflows/packages-uml.yml
      - packages/uml/**

jobs:
  build:
    uses: ./.github/workflows/ts/cli.yml
    with:
      name: uml
