name: packages/uml2ts

on:
  pull_request:
    branches: ['main']
    paths:
      - .github/actions/build-bun/**
      - .github/actions/build-docker/**
      - .github/workflows/bun-cli.yml
      - .github/workflows/packages-uml2ts.yml
      - packages/uml2ts/**

jobs:
  build:
    name: Bun CLI Build
    uses: ./.github/workflows/bun-cli.yml
    with:
      name: uml2ts
      docker: true
