name: proto

on:
  pull_request:
    branches: [main]
    paths:
      - .github/actions/build-proto/**
      - .github/workflows/proto.yml
      - proto/**
      - buf.*
  push:
    branches: [main]
    tags: ['v*.*.*']
    paths:
      - .github/actions/build-proto/**
      - .github/workflows/proto.yml
      - proto/**
      - buf.*

jobs:
  build:
    name: Buf Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build-proto
        with:
          path: proto
