name: CLI

on:
  pull_request:
    branches: ['main']
    paths:
      - .github/actions/build-dotnet/**
      - .github/actions/build-docker/**
      - .github/workflows/src-cli.yml
      - src/Cli*/**
  push:
    branches: ['main']
    tags: ['v*.*.*']
    paths:
      - .github/actions/build-dotnet/**
      - .github/actions/build-docker/**
      - .github/workflows/src-cli.yml
      - src/Cli*/**

env:
  CI: true
  ContinuousIntegrationBuild: true

jobs:
  build-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: ./.github/actions/build-dotnet
        id: build
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          restore-tools: true
          lint: true
          pack: ${{ github.event_name == 'push' }}
          path: src/Cli

    outputs:
      artifact-id: ${{ steps.build.outputs.artifact-id }}

  publish-cli:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: ['build-cli']
    strategy:
      matrix:
        source: ['nuget', 'github']
    env:
      PACKAGE_PATTERN: UnMango.Tdl.*.nupkg
    permissions:
      packages: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nuget

      - name: Publish to NuGet.org
        if: matrix.source == 'nuget'
        run: |
          dotnet nuget push "$PACKAGE_PATTERN" \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --skip-duplicate

      - name: Publish to GitHub Packages
        if: matrix.source == 'github'
        run: |
          dotnet nuget push "$PACKAGE_PATTERN" \
            --source https://nuget.pkg.github.com/${{ github.repository_owner }} \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --skip-duplicate
