name: Typescript CLI tool

on:
  workflow_call:
    inputs:
      name:
        description: The name of the tool.
        type: string
        required: true
      docker:
        description: Whether the tool has a corresponding container.
        type: boolean
        default: false

jobs:
  build-bun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-bun
        with:
          path: packages/${{ inputs.name }}

  build-docker:
    if: inputs.docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool:
          - uml2ts
    steps:
      - uses: actions/checkout@v4
      - run: echo "NAME=$(cat docker/${{ inputs.name }}/.name)" >> "$GITHUB_ENV"
      - uses: ./.github/actions/build-docker
        with:
          file: docker/${{ inputs.name }}/Dockerfile
          images: ghcr.io/${{ github.repository_owner }}/${{ env.NAME }}
          push: ${{ github.event_name != 'pull_request' }}
          token: ${{ secrets.GITHUB_TOKEN }}
